// Klassiker-Basis: Deutsche Hausmannskost (cuisine "Klassisch").
// Etablierte Gerichte mit Herkunft, Mengen für 4 Personen und vollständigen Schritten.
// Felder entsprechen dem Recipe-Modell in docs/ARCHITEKTUR.md, Abschnitt 3.
export default [
  {
    name: "Königsberger Klopse",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Ostpreußen",
    veg: false,
    servings: 4,
    minutes: 60,
    ingredients: [
      "600 g Hackfleisch, gemischt",
      "1 Brötchen vom Vortag",
      "2 Zwiebeln",
      "1 Ei",
      "2 Sardellenfilets",
      "1 l Gemüsebrühe",
      "1 Lorbeerblatt",
      "4 Pimentkörner",
      "40 g Butter",
      "40 g Mehl",
      "100 ml Sahne",
      "1 Eigelb",
      "3 EL Kapern",
      "2 EL Zitronensaft",
      "800 g Kartoffeln",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Brötchen in Wasser einweichen und gut ausdrücken. Eine Zwiebel und die Sardellen fein hacken und mit Hackfleisch, Brötchen, Ei, Salz und Pfeffer zu einem glatten Teig verkneten.",
      "Aus der Masse 12 Klopse formen. Kartoffeln schälen und in Salzwasser 20 Minuten kochen.",
      "Brühe mit der zweiten, halbierten Zwiebel, Lorbeerblatt und Piment aufkochen. Klopse hineingeben und bei schwacher Hitze 15 Minuten ziehen lassen, nicht kochen.",
      "Klopse mit einer Schaumkelle herausheben und warm stellen. Brühe durch ein Sieb gießen und 600 ml abmessen.",
      "Butter in einem Topf schmelzen, Mehl einrühren und 2 Minuten bei mittlerer Hitze anschwitzen. Brühe nach und nach unter Rühren zugießen und 5 Minuten köcheln lassen.",
      "Sahne mit dem Eigelb verquirlen, den Topf vom Herd nehmen und die Mischung einrühren. Kapern und Zitronensaft zugeben, mit Salz und Pfeffer abschmecken.",
      "Klopse in der Soße 3 Minuten erwärmen und mit Salzkartoffeln servieren.",
    ],
    description: "Hackfleischklöße in heller Kapernsoße, ein Klassiker aus Königsberg in Ostpreußen, traditionell mit Salzkartoffeln.",
    source: "klassiker",
  },
  {
    name: "Rinderrouladen mit Rotkohl",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 120,
    ingredients: [
      "4 Rinderrouladen",
      "4 TL mittelscharfer Senf",
      "8 Scheiben durchwachsener Speck",
      "2 Gewürzgurken",
      "3 Zwiebeln",
      "2 EL Butterschmalz",
      "1 EL Tomatenmark",
      "200 ml Rotwein",
      "500 ml Rinderbrühe",
      "1 Lorbeerblatt",
      "1 kg Rotkohl",
      "2 Äpfel",
      "2 EL Butter",
      "3 EL Essig",
      "1 EL Zucker",
      "3 Nelken",
      "800 g Kartoffeln",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Rouladen flach auslegen, salzen, pfeffern und mit Senf bestreichen. Mit je 2 Scheiben Speck, Gurkenvierteln und Zwiebelstreifen von einer Zwiebel belegen, fest aufrollen und mit Küchengarn oder Rouladennadeln verschließen.",
      "Butterschmalz in einem Schmortopf stark erhitzen und die Rouladen rundherum 6 Minuten kräftig anbraten. Herausnehmen.",
      "Die restlichen Zwiebeln würfeln, im Bratfett 3 Minuten anbraten, Tomatenmark einrühren und mit Rotwein ablöschen. Brühe und Lorbeerblatt zugeben, Rouladen einlegen und zugedeckt bei schwacher Hitze 90 Minuten schmoren.",
      "Rotkohl vierteln, Strunk entfernen und fein hobeln. Äpfel schälen und würfeln. Butter in einem Topf schmelzen, Rotkohl und Äpfel 5 Minuten andünsten.",
      "Essig, Zucker, Nelken, Salz und 150 ml Wasser zum Rotkohl geben und zugedeckt bei schwacher Hitze 60 Minuten garen, dabei gelegentlich umrühren.",
      "Kartoffeln schälen und in Salzwasser 20 Minuten kochen.",
      "Rouladen herausnehmen, Garn entfernen. Soße durch ein Sieb gießen, aufkochen, bei Bedarf 5 Minuten einkochen lassen und mit Salz und Pfeffer abschmecken. Rouladen mit Soße, Rotkohl und Salzkartoffeln servieren.",
    ],
    description: "Das klassische deutsche Sonntagsessen: mit Speck, Gurke und Zwiebel gefüllte Rindfleischröllchen, lange geschmort, mit Rotkohl und Salzkartoffeln.",
    source: "klassiker",
  },
  {
    name: "Kartoffelsuppe",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 45,
    ingredients: [
      "1 kg Kartoffeln, mehligkochend",
      "2 Möhren",
      "1 Lauch",
      "150 g Knollensellerie",
      "1 Zwiebel",
      "2 EL Butter",
      "1.5 l Gemüsebrühe",
      "4 Wiener Würstchen",
      "1 Bund Petersilie",
      "1 TL Majoran",
      "Salz",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Kartoffeln, Möhren und Sellerie schälen und in 2 cm große Würfel schneiden. Lauch längs halbieren, waschen und in Ringe schneiden. Zwiebel fein würfeln.",
      "Butter in einem großen Topf erhitzen und die Zwiebel 3 Minuten glasig dünsten. Kartoffeln, Möhren, Sellerie und Lauch zugeben und 3 Minuten mitdünsten.",
      "Brühe angießen, aufkochen und zugedeckt bei mittlerer Hitze 25 Minuten köcheln lassen, bis die Kartoffeln weich sind.",
      "Etwa ein Drittel der Suppe mit dem Pürierstab oder dem Kartoffelstampfer grob zerdrücken, damit sie sämig wird.",
      "Würstchen in Scheiben schneiden, in die Suppe geben und 5 Minuten darin erhitzen.",
      "Mit Majoran, Salz, Pfeffer und Muskat abschmecken, Petersilie hacken und darüberstreuen.",
    ],
    description: "Sämige Suppe aus Kartoffeln und Suppengemüse mit Würstchen, in ganz Deutschland verbreitet und ein typisches Eintopfgericht für den Alltag.",
    source: "klassiker",
  },
  {
    name: "Erbsensuppe",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 90,
    ingredients: [
      "500 g Schälerbsen",
      "200 g durchwachsener Speck",
      "4 Mettenden",
      "2 Möhren",
      "1 Lauch",
      "150 g Knollensellerie",
      "400 g Kartoffeln",
      "1 Zwiebel",
      "2 l Gemüsebrühe",
      "2 Lorbeerblätter",
      "1 TL Majoran",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Schälerbsen in einem Sieb kalt abspülen. Speck in Würfel schneiden, Zwiebel fein würfeln.",
      "Speck in einem großen Topf bei mittlerer Hitze 5 Minuten auslassen, Zwiebel zugeben und 3 Minuten glasig dünsten.",
      "Erbsen, Brühe und Lorbeerblätter zugeben, aufkochen und zugedeckt bei schwacher Hitze 40 Minuten köcheln lassen, gelegentlich umrühren.",
      "Möhren, Sellerie und Kartoffeln schälen und würfeln, Lauch in Ringe schneiden. Alles in die Suppe geben und weitere 25 Minuten köcheln, bis Erbsen und Gemüse weich sind.",
      "Mettenden im Ganzen in die Suppe legen und 10 Minuten darin erhitzen.",
      "Lorbeerblätter entfernen, Mettenden in Scheiben schneiden und zurück in die Suppe geben. Mit Majoran, Salz und Pfeffer abschmecken.",
    ],
    description: "Dicker Eintopf aus Schälerbsen, Speck und Mettenden, ein deftiger deutscher Klassiker für kalte Tage.",
    source: "klassiker",
  },
  {
    name: "Linseneintopf",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 60,
    ingredients: [
      "300 g Tellerlinsen",
      "150 g durchwachsener Speck",
      "4 Wiener Würstchen",
      "2 Möhren",
      "1 Lauch",
      "100 g Knollensellerie",
      "400 g Kartoffeln",
      "1 Zwiebel",
      "1.5 l Gemüsebrühe",
      "2 Lorbeerblätter",
      "3 EL Essig",
      "1 TL Zucker",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Linsen in einem Sieb kalt abspülen. Speck und Zwiebel fein würfeln. Möhren, Sellerie und Kartoffeln schälen und würfeln, Lauch in Ringe schneiden.",
      "Speck in einem großen Topf bei mittlerer Hitze 4 Minuten auslassen, Zwiebel zugeben und 3 Minuten glasig dünsten.",
      "Möhren, Sellerie und Lauch zugeben und 3 Minuten mitdünsten. Linsen, Brühe und Lorbeerblätter einrühren und aufkochen.",
      "Zugedeckt bei schwacher Hitze 20 Minuten köcheln lassen, dann die Kartoffelwürfel zugeben und weitere 20 Minuten garen, bis Linsen und Kartoffeln weich sind.",
      "Würstchen in Scheiben schneiden und 5 Minuten in der Suppe erhitzen.",
      "Lorbeerblätter entfernen und den Eintopf mit Essig, Zucker, Salz und Pfeffer abschmecken.",
    ],
    description: "Deftiger Eintopf aus Tellerlinsen, Suppengemüse, Speck und Würstchen, der mit einem Schuss Essig abgeschmeckt wird.",
    source: "klassiker",
  },
  {
    name: "Rindergulasch",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland, nach ungarischem Vorbild",
    veg: false,
    servings: 4,
    minutes: 150,
    ingredients: [
      "1 kg Rindergulasch",
      "600 g Zwiebeln",
      "3 EL Butterschmalz",
      "2 EL Tomatenmark",
      "2 EL Paprikapulver edelsüß",
      "2 Zehen Knoblauch",
      "1 TL Kümmel",
      "1 TL Majoran",
      "200 ml Rotwein",
      "500 ml Rinderbrühe",
      "2 Lorbeerblätter",
      "500 g Bandnudeln",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Fleisch trocken tupfen und in 3 cm große Würfel schneiden. Zwiebeln und Knoblauch fein würfeln.",
      "Butterschmalz in einem Schmortopf stark erhitzen und das Fleisch in zwei Portionen jeweils 5 Minuten rundherum kräftig anbraten. Herausnehmen.",
      "Zwiebeln im Bratfett bei mittlerer Hitze 10 Minuten goldbraun rösten. Knoblauch und Tomatenmark zugeben und 2 Minuten mitrösten.",
      "Topf vom Herd ziehen, Paprikapulver einrühren und sofort mit Rotwein ablöschen, damit das Paprikapulver nicht bitter wird.",
      "Fleisch, Brühe, Lorbeerblätter, Kümmel und Majoran zugeben, salzen und pfeffern. Zugedeckt bei schwacher Hitze 2 Stunden schmoren, bis das Fleisch zerfällt, dabei gelegentlich umrühren.",
      "Bandnudeln nach Packungsangabe in Salzwasser kochen. Gulasch mit Salz und Pfeffer abschmecken und mit den Nudeln servieren.",
    ],
    description: "Langsam geschmortes Rindfleisch mit viel Zwiebeln und Paprika, in der deutschen Küche seit dem 19. Jahrhundert fest verankert.",
    source: "klassiker",
  },
  {
    name: "Frikadellen mit Kartoffelpüree",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 50,
    ingredients: [
      "600 g Hackfleisch, gemischt",
      "1 Brötchen vom Vortag",
      "1 Zwiebel",
      "1 Ei",
      "1 TL mittelscharfer Senf",
      "1 TL Majoran",
      "3 EL Butterschmalz",
      "1 kg Kartoffeln, mehligkochend",
      "200 ml Milch",
      "50 g Butter",
      "Salz",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Kartoffeln schälen, vierteln und in Salzwasser 20 Minuten weich kochen.",
      "Brötchen in Wasser einweichen und ausdrücken. Zwiebel fein würfeln. Hackfleisch mit Brötchen, Zwiebel, Ei, Senf, Majoran, Salz und Pfeffer gründlich verkneten.",
      "Mit feuchten Händen 8 flache Frikadellen formen.",
      "Butterschmalz in einer großen Pfanne erhitzen und die Frikadellen bei mittlerer Hitze von jeder Seite 6 Minuten braten, bis sie durchgegart und braun sind.",
      "Kartoffeln abgießen und kurz ausdampfen lassen. Milch mit Butter erwärmen, zu den Kartoffeln geben und mit dem Stampfer zu einem glatten Püree verarbeiten.",
      "Püree mit Salz und Muskat abschmecken und mit den Frikadellen servieren.",
    ],
    description: "Gebratene Hackfleischklöße mit cremigem Kartoffelpüree, je nach Region auch Buletten oder Fleischpflanzerl genannt.",
    source: "klassiker",
  },
  {
    name: "Hühnerfrikassee",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 100,
    ingredients: [
      "1 Suppenhuhn",
      "2 Möhren",
      "1 Lauch",
      "100 g Knollensellerie",
      "1 Zwiebel",
      "1 Lorbeerblatt",
      "250 g Champignons",
      "200 g Erbsen, tiefgekühlt",
      "1 Glas Spargel",
      "40 g Butter",
      "40 g Mehl",
      "100 ml Sahne",
      "1 Eigelb",
      "2 EL Zitronensaft",
      "300 g Langkornreis",
      "Salz",
      "Pfeffer",
      "Zucker",
    ],
    steps: [
      "Suppenhuhn mit 2 l kaltem Wasser aufsetzen. Möhren, Sellerie und Lauch grob zerteilen, mit der halbierten Zwiebel, Lorbeerblatt und 1 TL Salz zugeben. Aufkochen und bei schwacher Hitze 70 Minuten köcheln lassen.",
      "Huhn herausnehmen und etwas abkühlen lassen. Brühe durch ein Sieb gießen und 600 ml abmessen. Fleisch von Haut und Knochen lösen und in mundgerechte Stücke zupfen.",
      "Reis nach Packungsangabe in Salzwasser 20 Minuten garen.",
      "Champignons putzen und vierteln. Butter in einem Topf schmelzen, Champignons 4 Minuten anbraten, dann das Mehl darüberstäuben und 2 Minuten anschwitzen.",
      "Brühe nach und nach unter Rühren angießen, aufkochen und 5 Minuten köcheln lassen. Hühnerfleisch, Erbsen und abgetropften Spargel zugeben und 5 Minuten erhitzen.",
      "Sahne mit Eigelb verquirlen, den Topf vom Herd nehmen und die Mischung einrühren. Mit Zitronensaft, Salz, Pfeffer und einer Prise Zucker abschmecken und mit Reis servieren.",
    ],
    description: "Zartes Hühnerfleisch in heller Soße mit Champignons, Erbsen und Spargel, ein Klassiker der bürgerlichen deutschen Küche, klassisch mit Reis serviert.",
    source: "klassiker",
  },
  {
    name: "Kohlrouladen",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 90,
    ingredients: [
      "1 Weißkohl",
      "600 g Hackfleisch, gemischt",
      "1 Brötchen vom Vortag",
      "1 Zwiebel",
      "1 Ei",
      "8 Scheiben durchwachsener Speck",
      "2 EL Butterschmalz",
      "1 EL Tomatenmark",
      "400 ml Rinderbrühe",
      "1 TL Kümmel",
      "100 ml Sahne",
      "1 EL Mehl",
      "800 g Kartoffeln",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Vom Weißkohl 8 große äußere Blätter lösen, in kochendem Salzwasser 5 Minuten blanchieren, kalt abschrecken und die dicke Mittelrippe flach schneiden.",
      "Brötchen einweichen und ausdrücken, Zwiebel fein würfeln. Hackfleisch mit Brötchen, Zwiebel, Ei, Salz und Pfeffer verkneten.",
      "Die Hackmasse auf die Kohlblätter verteilen, Seiten einschlagen, fest aufrollen, mit je einer Speckscheibe umwickeln und mit Küchengarn binden.",
      "Butterschmalz in einem Schmortopf erhitzen und die Rouladen rundherum 6 Minuten anbraten. Tomatenmark kurz mitrösten, Brühe und Kümmel zugeben.",
      "Zugedeckt bei schwacher Hitze 45 Minuten schmoren. Währenddessen Kartoffeln schälen und in Salzwasser 20 Minuten kochen.",
      "Rouladen herausnehmen und warm stellen. Mehl mit der Sahne glatt rühren, in die Soße geben und 3 Minuten unter Rühren köcheln lassen. Mit Salz und Pfeffer abschmecken und alles mit den Salzkartoffeln servieren.",
    ],
    description: "Mit Hackfleisch gefüllte Weißkohlblätter, in Brühe geschmort und mit Speck umwickelt, ein traditionelles Herbst- und Wintergericht in ganz Deutschland.",
    source: "klassiker",
  },
  {
    name: "Senfeier",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Norddeutschland",
    veg: true,
    servings: 4,
    minutes: 35,
    ingredients: [
      "8 Eier",
      "1 kg Kartoffeln",
      "40 g Butter",
      "40 g Mehl",
      "500 ml Milch",
      "200 ml Gemüsebrühe",
      "3 EL mittelscharfer Senf",
      "1 TL Zucker",
      "1 EL Zitronensaft",
      "1 Bund Schnittlauch",
      "Salz",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Kartoffeln schälen und in Salzwasser 20 Minuten kochen.",
      "Eier in kochendem Wasser 8 Minuten wachsweich kochen, abschrecken und pellen.",
      "Butter in einem Topf schmelzen, Mehl einrühren und 2 Minuten bei mittlerer Hitze anschwitzen. Milch und Brühe nach und nach unter Rühren angießen, aufkochen und 5 Minuten köcheln lassen.",
      "Senf, Zucker und Zitronensaft einrühren und die Soße mit Salz, Pfeffer und Muskat abschmecken. Nach dem Senf nicht mehr kochen lassen.",
      "Eier halbieren, in die Soße legen und 2 Minuten erwärmen. Schnittlauch in Röllchen schneiden und darüberstreuen, mit den Salzkartoffeln servieren.",
    ],
    description: "Wachsweiche Eier in heller Senfsoße mit Salzkartoffeln, ein einfaches norddeutsches Alltagsgericht.",
    source: "klassiker",
  },
  {
    name: "Kartoffelpuffer mit Apfelmus",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 50,
    ingredients: [
      "1.5 kg Kartoffeln, festkochend",
      "2 Zwiebeln",
      "2 Eier",
      "3 EL Mehl",
      "150 ml Öl",
      "1 kg Äpfel",
      "2 EL Zucker",
      "1 EL Zitronensaft",
      "½ TL Zimt",
      "Salz",
      "Muskat",
    ],
    steps: [
      "Äpfel schälen, entkernen und würfeln. Mit 50 ml Wasser, Zucker und Zitronensaft zugedeckt bei schwacher Hitze 15 Minuten weich kochen, dann mit einer Gabel zerdrücken und mit Zimt abschmecken.",
      "Kartoffeln und Zwiebeln schälen und fein reiben. Die Masse in ein sauberes Küchentuch geben und kräftig ausdrücken.",
      "Kartoffelmasse mit Eiern, Mehl, 1 TL Salz und Muskat vermengen.",
      "Öl in einer großen Pfanne erhitzen, jeweils 2 EL Masse hineingeben, flach drücken und bei mittlerer Hitze von jeder Seite 4 Minuten goldbraun braten.",
      "Fertige Puffer auf Küchenpapier abtropfen lassen und im Backofen bei 80 °C warm halten, bis alle gebraten sind. Mit dem Apfelmus servieren.",
    ],
    description: "Knusprig gebratene Reibekuchen aus rohen Kartoffeln, die in Deutschland je nach Region Reibekuchen, Reiberdatschi oder Kartoffelpuffer heißen, traditionell mit Apfelmus.",
    source: "klassiker",
  },
  {
    name: "Nudelauflauf mit Schinken",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 50,
    ingredients: [
      "500 g Hörnchennudeln",
      "200 g Kochschinken",
      "200 g Erbsen, tiefgekühlt",
      "1 Zwiebel",
      "1 EL Butter",
      "4 Eier",
      "250 ml Milch",
      "200 ml Sahne",
      "200 g Gouda, gerieben",
      "Salz",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Backofen auf 180 °C Ober- und Unterhitze vorheizen. Nudeln in Salzwasser 2 Minuten kürzer als auf der Packung angegeben kochen und abgießen.",
      "Zwiebel fein würfeln und in der Butter 3 Minuten glasig dünsten. Schinken in Streifen schneiden.",
      "Eier mit Milch und Sahne verquirlen, die Hälfte des Käses unterrühren und mit Salz, Pfeffer und Muskat kräftig würzen.",
      "Nudeln mit Zwiebel, Schinken und Erbsen mischen, in eine gefettete Auflaufform geben und die Eiermilch darübergießen.",
      "Mit dem restlichen Käse bestreuen und im Ofen 30 Minuten backen, bis die Oberfläche goldbraun ist. Vor dem Anschneiden 5 Minuten ruhen lassen.",
    ],
    description: "Überbackene Nudeln mit Schinken, Erbsen und Käse in Eiermilch, ein deutscher Familienklassiker aus der Auflaufform.",
    source: "klassiker",
  },
  {
    name: "Kartoffelgratin",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Frankreich, in Deutschland fest etabliert",
    veg: true,
    servings: 4,
    minutes: 75,
    ingredients: [
      "1.2 kg Kartoffeln, festkochend",
      "300 ml Sahne",
      "200 ml Milch",
      "2 Zehen Knoblauch",
      "100 g Bergkäse, gerieben",
      "1 EL Butter",
      "2 Thymianzweige",
      "Salz",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Backofen auf 180 °C Ober- und Unterhitze vorheizen. Eine Auflaufform mit einer halbierten Knoblauchzehe ausreiben und mit Butter fetten.",
      "Kartoffeln schälen und in 3 mm dünne Scheiben hobeln, nicht waschen, damit die Stärke erhalten bleibt.",
      "Sahne, Milch, den restlichen fein gehackten Knoblauch und die Thymianblättchen in einem Topf aufkochen und mit 1 TL Salz, Pfeffer und Muskat würzen.",
      "Kartoffelscheiben dachziegelartig in die Form schichten und die heiße Sahnemilch darübergießen.",
      "Im Ofen 45 Minuten backen, dann mit dem Käse bestreuen und weitere 15 Minuten backen, bis die Kartoffeln weich und die Oberfläche goldbraun ist. Vor dem Servieren 5 Minuten ruhen lassen.",
    ],
    description: "Dünne Kartoffelscheiben in Sahne und Milch überbacken, aus der französischen Dauphiné stammend und in Deutschland als Hauptgericht mit Salat oder als Beilage verbreitet.",
    source: "klassiker",
  },
  {
    name: "Bratkartoffeln mit Spiegelei",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 50,
    ingredients: [
      "1.2 kg Kartoffeln, festkochend",
      "150 g durchwachsener Speck",
      "2 Zwiebeln",
      "3 EL Butterschmalz",
      "4 Eier",
      "1 TL Kümmel",
      "1 Bund Schnittlauch",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Kartoffeln mit Schale in Salzwasser 20 Minuten kochen, abgießen, 10 Minuten ausdampfen lassen, pellen und in 5 mm dicke Scheiben schneiden. Am besten eignen sich Kartoffeln vom Vortag.",
      "Speck würfeln, Zwiebeln in feine Streifen schneiden.",
      "2 EL Butterschmalz in einer großen Pfanne erhitzen, Kartoffelscheiben hineingeben und bei mittlerer bis starker Hitze 10 Minuten braten, ohne häufig zu wenden, damit sie knusprig werden.",
      "Speck, Zwiebeln und Kümmel zugeben und weitere 8 Minuten braten, bis Speck und Zwiebeln goldbraun sind. Mit Salz und Pfeffer würzen.",
      "In einer zweiten Pfanne das restliche Butterschmalz erhitzen und die Eier bei mittlerer Hitze 4 Minuten zu Spiegeleiern braten, salzen und pfeffern.",
      "Bratkartoffeln mit den Spiegeleiern anrichten und mit Schnittlauchröllchen bestreuen.",
    ],
    description: "Knusprige Bratkartoffeln mit Speck und Zwiebeln, dazu Spiegeleier, das klassische deutsche Resteessen aus gekochten Kartoffeln.",
    source: "klassiker",
  },
  {
    name: "Hackbraten",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 80,
    ingredients: [
      "800 g Hackfleisch, gemischt",
      "2 Brötchen vom Vortag",
      "2 Zwiebeln",
      "2 Eier",
      "2 TL mittelscharfer Senf",
      "1 TL Paprikapulver edelsüß",
      "1 TL Majoran",
      "2 EL Öl",
      "1 EL Tomatenmark",
      "300 ml Rinderbrühe",
      "100 ml Sahne",
      "1 EL Mehl",
      "1 kg Kartoffeln",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Backofen auf 180 °C Ober- und Unterhitze vorheizen. Brötchen in Wasser einweichen und ausdrücken, Zwiebeln fein würfeln.",
      "Hackfleisch mit Brötchen, Zwiebeln, Eiern, Senf, Paprikapulver, Majoran, 1.5 TL Salz und Pfeffer gründlich verkneten und zu einem länglichen Laib formen.",
      "Öl in einem Bräter erhitzen und den Hackbraten rundherum 8 Minuten anbraten. Tomatenmark kurz mitrösten, Brühe angießen.",
      "Den Bräter in den Ofen schieben und den Braten 50 Minuten garen, dabei zweimal mit dem Bratfond übergießen.",
      "Kartoffeln schälen und in Salzwasser 20 Minuten kochen.",
      "Braten herausnehmen und 5 Minuten ruhen lassen. Bratfond auf dem Herd aufkochen, Mehl mit der Sahne glatt rühren, einrühren und 3 Minuten köcheln lassen. Mit Salz und Pfeffer abschmecken, Braten in Scheiben schneiden und mit Soße und Kartoffeln servieren.",
    ],
    description: "Im Ofen gegarter Laib aus gewürztem Hackfleisch mit Bratensoße, in Süddeutschland auch als Faschierter Braten bekannt.",
    source: "klassiker",
  },
  {
    name: "Schweinegeschnetzeltes mit Champignons",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 35,
    ingredients: [
      "600 g Schweinefilet",
      "400 g Champignons",
      "1 Zwiebel",
      "2 EL Butterschmalz",
      "1 EL Mehl",
      "200 ml Gemüsebrühe",
      "200 ml Sahne",
      "1 TL Paprikapulver edelsüß",
      "1 TL mittelscharfer Senf",
      "1 Bund Petersilie",
      "500 g Bandnudeln",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Bandnudeln in reichlich Salzwasser nach Packungsangabe kochen.",
      "Schweinefilet in dünne Streifen schneiden, Champignons putzen und in Scheiben schneiden, Zwiebel fein würfeln.",
      "1 EL Butterschmalz in einer großen Pfanne stark erhitzen und das Fleisch in zwei Portionen jeweils 2 Minuten scharf anbraten, salzen, pfeffern und herausnehmen.",
      "Restliches Butterschmalz in die Pfanne geben, Zwiebel und Champignons bei mittlerer Hitze 5 Minuten braten, bis die Flüssigkeit verdampft ist.",
      "Mehl und Paprikapulver darüberstäuben, kurz anschwitzen, mit Brühe ablöschen und die Sahne zugeben. 5 Minuten sämig einkochen lassen.",
      "Fleisch zurück in die Pfanne geben, Senf einrühren und 2 Minuten erwärmen. Mit Salz und Pfeffer abschmecken, gehackte Petersilie darüberstreuen und mit den Nudeln servieren.",
    ],
    description: "Kurz gebratene Schweinefiletstreifen in cremiger Champignonrahmsoße, ein schnelles Alltagsgericht der deutschen Küche, meist mit Nudeln oder Spätzle.",
    source: "klassiker",
  },
  {
    name: "Matjes nach Hausfrauenart",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Norddeutschland",
    veg: false,
    servings: 4,
    minutes: 40,
    ingredients: [
      "8 Matjesfilets",
      "200 g saure Sahne",
      "200 g Schmand",
      "2 Äpfel",
      "2 Zwiebeln",
      "3 Gewürzgurken",
      "1 TL Zucker",
      "1 EL Zitronensaft",
      "1 Bund Dill",
      "1 kg Kartoffeln",
      "Pfeffer",
    ],
    steps: [
      "Matjesfilets 15 Minuten in kaltem Wasser wässern, dann trocken tupfen und in mundgerechte Stücke schneiden.",
      "Äpfel schälen, entkernen und würfeln, Zwiebeln in feine Ringe schneiden, Gewürzgurken würfeln, Dill fein hacken.",
      "Saure Sahne und Schmand mit Zucker, Zitronensaft und Pfeffer verrühren. Äpfel, Zwiebeln, Gurken und Dill unterheben.",
      "Matjesstücke in die Soße geben, vorsichtig mischen und zugedeckt im Kühlschrank mindestens 2 Stunden durchziehen lassen.",
      "Kartoffeln mit Schale in Salzwasser 20 Minuten kochen, pellen und heiß zu den Matjes servieren.",
    ],
    description: "Matjesfilets in Soße aus saurer Sahne mit Apfel, Zwiebel und Gurke, ein norddeutscher Klassiker zu Pellkartoffeln. Die Zeit gilt ohne das Durchziehen: mindestens 2 Stunden, besser über Nacht.",
    source: "klassiker",
  },
  {
    name: "Gemüseeintopf",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 45,
    ingredients: [
      "600 g Kartoffeln",
      "3 Möhren",
      "1 Lauch",
      "200 g Knollensellerie",
      "1 Kohlrabi",
      "200 g grüne Bohnen, tiefgekühlt",
      "1 Zwiebel",
      "2 EL Butter",
      "1.5 l Gemüsebrühe",
      "1 Lorbeerblatt",
      "1 Bund Petersilie",
      "Salz",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Kartoffeln, Möhren, Sellerie und Kohlrabi schälen und in 2 cm große Würfel schneiden. Lauch längs halbieren, waschen und in Ringe schneiden. Zwiebel fein würfeln.",
      "Butter in einem großen Topf erhitzen und die Zwiebel 3 Minuten glasig dünsten. Möhren, Sellerie und Kohlrabi zugeben und 5 Minuten mitdünsten.",
      "Kartoffeln, Brühe und Lorbeerblatt zugeben, aufkochen und zugedeckt bei mittlerer Hitze 15 Minuten köcheln lassen.",
      "Lauch und Bohnen zugeben und weitere 10 Minuten köcheln, bis alles Gemüse weich ist.",
      "Lorbeerblatt entfernen, mit Salz, Pfeffer und Muskat abschmecken und mit gehackter Petersilie bestreuen.",
    ],
    description: "Bunter Eintopf aus Kartoffeln und Wurzelgemüse in Brühe, ein einfaches vegetarisches Alltagsgericht der deutschen Küche.",
    source: "klassiker",
  },
  {
    name: "Hühnersuppe mit Nudeln",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 120,
    ingredients: [
      "1 Suppenhuhn",
      "2 Möhren",
      "1 Lauch",
      "150 g Knollensellerie",
      "1 Zwiebel",
      "2 Lorbeerblätter",
      "5 Pfefferkörner",
      "200 g Suppennudeln",
      "1 Bund Petersilie",
      "Salz",
      "Muskat",
    ],
    steps: [
      "Suppenhuhn kalt abspülen und in einem großen Topf mit 2.5 l kaltem Wasser aufsetzen. Zwiebel ungeschält halbieren und mit der Schnittfläche in einer Pfanne ohne Fett 3 Minuten dunkel rösten.",
      "Eine Möhre, die Hälfte des Lauchs und den Sellerie grob zerteilen und mit der Zwiebel, Lorbeerblättern, Pfefferkörnern und 1 EL Salz zum Huhn geben. Aufkochen, Schaum abschöpfen und bei schwacher Hitze 90 Minuten köcheln lassen.",
      "Huhn herausnehmen, etwas abkühlen lassen und das Fleisch von Haut und Knochen lösen und zerkleinern. Brühe durch ein Sieb in einen sauberen Topf gießen.",
      "Die restliche Möhre und den restlichen Lauch in feine Streifen schneiden, in der Brühe aufkochen und 5 Minuten garen.",
      "Suppennudeln zugeben und nach Packungsangabe 6 Minuten kochen. Hühnerfleisch in die Suppe geben und erwärmen.",
      "Mit Salz und Muskat abschmecken und mit gehackter Petersilie servieren.",
    ],
    description: "Kräftige Brühe vom Suppenhuhn mit Gemüsestreifen, Hühnerfleisch und Nudeln, die klassische deutsche Hühnersuppe.",
    source: "klassiker",
  },
  {
    name: "Grießbrei",
    category: "Kinderessen",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "1 l Milch",
      "120 g Weichweizengrieß",
      "2 EL Zucker",
      "1 Päckchen Vanillezucker",
      "1 Prise Salz",
      "20 g Butter",
      "1 TL Zimt",
      "1 Glas Sauerkirschen",
    ],
    steps: [
      "Milch mit Butter, Zucker, Vanillezucker und Salz in einem Topf bei mittlerer Hitze zum Kochen bringen.",
      "Grieß unter ständigem Rühren mit dem Schneebesen einrieseln lassen, damit keine Klümpchen entstehen.",
      "Bei schwacher Hitze 3 Minuten unter Rühren köcheln lassen, dann vom Herd nehmen und zugedeckt 5 Minuten quellen lassen.",
      "Grießbrei in Schalen füllen, mit Zimt und etwas Zucker bestreuen und mit den abgetropften Sauerkirschen servieren.",
    ],
    description: "Warmer Brei aus Weichweizengrieß und Milch, ein einfaches süßes Gericht der deutschen Küche, das traditionell mit Zimtzucker oder Kompott gegessen wird.",
    source: "klassiker",
  },
  {
    name: "Milchreis mit Zimt und Zucker",
    category: "Kinderessen",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "1 l Milch",
      "250 g Milchreis",
      "3 EL Zucker",
      "1 Päckchen Vanillezucker",
      "1 Prise Salz",
      "20 g Butter",
      "2 TL Zimt",
    ],
    steps: [
      "Milch mit Butter, 1 EL Zucker, Vanillezucker und Salz in einem Topf aufkochen.",
      "Milchreis einrühren, wieder aufkochen und bei schwacher Hitze zugedeckt 30 Minuten quellen lassen, dabei alle 5 Minuten umrühren, damit nichts ansetzt.",
      "Topf vom Herd nehmen und den Reis zugedeckt 5 Minuten nachziehen lassen, bis die restliche Milch aufgenommen ist.",
      "Den restlichen Zucker mit Zimt mischen. Milchreis in Schalen füllen und mit dem Zimtzucker bestreut servieren.",
    ],
    description: "Cremig in Milch gegarter Rundkornreis mit Zimtzucker, ein süßes Hauptgericht, das in Deutschland seit Generationen gekocht wird.",
    source: "klassiker",
  },
  {
    name: "Eierkuchen mit Speck",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 40,
    ingredients: [
      "250 g Mehl",
      "4 Eier",
      "500 ml Milch",
      "1 Prise Salz",
      "150 g durchwachsener Speck",
      "2 EL Butterschmalz",
      "1 Bund Schnittlauch",
      "Pfeffer",
    ],
    steps: [
      "Mehl, Eier, Milch und Salz mit dem Schneebesen zu einem glatten Teig verrühren und 15 Minuten quellen lassen.",
      "Speck in dünne Streifen schneiden, Schnittlauch in Röllchen schneiden.",
      "Etwas Butterschmalz in einer beschichteten Pfanne erhitzen, ein Viertel des Specks darin 2 Minuten bei mittlerer Hitze anbraten.",
      "Eine Kelle Teig über den Speck gießen, durch Schwenken verteilen und 3 Minuten backen, bis die Unterseite goldbraun ist. Wenden und weitere 2 Minuten backen.",
      "Die restlichen drei Eierkuchen ebenso backen, fertige im Ofen bei 80 °C warm halten. Mit Pfeffer und Schnittlauch bestreut servieren.",
    ],
    description: "Herzhafte Pfannkuchen, in deren Teig Speckstreifen mitgebacken werden, in Norddeutschland als Speckpfannkuchen oder Eierkuchen mit Speck bekannt.",
    source: "klassiker",
  },
  {
    name: "Backfisch mit Kartoffelsalat",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Norddeutschland",
    veg: false,
    servings: 4,
    minutes: 60,
    ingredients: [
      "800 g Kabeljaufilet",
      "2 EL Zitronensaft",
      "150 g Mehl",
      "2 Eier",
      "150 ml helles Bier",
      "1 l Öl",
      "1 kg Kartoffeln, festkochend",
      "3 Gewürzgurken",
      "1 Zwiebel",
      "150 g Mayonnaise",
      "150 g Joghurt",
      "2 EL Gurkenwasser",
      "1 TL mittelscharfer Senf",
      "1 Bund Dill",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Kartoffeln mit Schale in Salzwasser 20 Minuten kochen, abgießen, kurz ausdampfen lassen, pellen und in Scheiben schneiden.",
      "Gurken und Zwiebel fein würfeln. Mayonnaise mit Joghurt, Gurkenwasser, Senf, Salz und Pfeffer verrühren, mit Kartoffeln, Gurken und Zwiebel mischen und mindestens 20 Minuten durchziehen lassen. Gehackten Dill unterheben.",
      "Fisch in 8 Stücke schneiden, mit Zitronensaft beträufeln, salzen und pfeffern. Eier trennen.",
      "Für den Teig 120 g Mehl mit Eigelben, Bier und 1 Prise Salz glatt rühren. Eiweiße steif schlagen und unterheben.",
      "Öl in einem hohen Topf auf 170 °C erhitzen. Fischstücke im restlichen Mehl wenden, durch den Teig ziehen und portionsweise 5 Minuten goldbraun ausbacken.",
      "Backfisch auf Küchenpapier abtropfen lassen und sofort mit dem Kartoffelsalat servieren.",
    ],
    description: "In Bierteig ausgebackener Kabeljau mit Kartoffelsalat auf Mayonnaise-Basis, ein Klassiker der norddeutschen Küche.",
    source: "klassiker",
  },
  {
    name: "Jägerschnitzel",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 40,
    ingredients: [
      "4 Schweineschnitzel",
      "400 g Champignons",
      "1 Zwiebel",
      "3 EL Butterschmalz",
      "1 EL Tomatenmark",
      "1 EL Mehl",
      "300 ml Rinderbrühe",
      "150 ml Sahne",
      "1 TL Paprikapulver edelsüß",
      "1 Bund Petersilie",
      "500 g Spätzle",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Spätzle in Salzwasser nach Packungsangabe garen. Champignons putzen und in Scheiben schneiden, Zwiebel fein würfeln.",
      "Schnitzel zwischen Frischhaltefolie 1 cm dünn klopfen, salzen und pfeffern.",
      "2 EL Butterschmalz in einer großen Pfanne stark erhitzen und die Schnitzel von jeder Seite 3 Minuten braten. Herausnehmen und warm stellen.",
      "Restliches Butterschmalz in die Pfanne geben, Zwiebel und Champignons bei mittlerer Hitze 6 Minuten braten, bis sie Farbe nehmen.",
      "Tomatenmark und Paprikapulver einrühren, Mehl darüberstäuben und kurz anschwitzen. Mit Brühe ablöschen, Sahne zugeben und 5 Minuten sämig einkochen lassen.",
      "Soße mit Salz und Pfeffer abschmecken, Schnitzel darin 2 Minuten erwärmen, mit gehackter Petersilie bestreuen und mit den Spätzle servieren.",
    ],
    description: "Unpaniertes Schweineschnitzel in Champignonrahmsoße, ein Klassiker der deutschen Gasthausküche, der mit Spätzle oder Pommes frites serviert wird.",
    source: "klassiker",
  },
];
