// Klassiker-Basis: Italienische und mediterrane Küche (cuisine "Italienisch" bzw. "Mediterran").
// Etablierte Gerichte mit Herkunft, Mengen für 4 Personen und vollständigen Schritten.
// Felder entsprechen dem Recipe-Modell in docs/ARCHITEKTUR.md, Abschnitt 3.
export default [
  {
    name: "Spaghetti aglio e olio",
    category: "Schnelle Küche",
    cuisine: "Italienisch",
    origin: "Neapel, Kampanien",
    veg: true,
    servings: 4,
    minutes: 20,
    ingredients: [
      "500 g Spaghetti",
      "6 Zehen Knoblauch",
      "120 ml Olivenöl",
      "2 Peperoncini, getrocknet",
      "1 Bund Petersilie",
      "Salz",
    ],
    steps: [
      "Reichlich Wasser in einem großen Topf aufkochen, salzen und die Spaghetti nach Packungsangabe bissfest kochen.",
      "Knoblauch in dünne Scheiben schneiden, Peperoncini zerbröseln und Petersilie fein hacken.",
      "Olivenöl in einer großen Pfanne bei schwacher Hitze erwärmen. Knoblauch und Peperoncini darin 3 bis 4 Minuten langsam goldgelb ziehen lassen, der Knoblauch darf nicht braun werden.",
      "Eine Tasse Nudelwasser abschöpfen, Spaghetti abgießen und in die Pfanne geben.",
      "Alles mit 100 ml Nudelwasser bei mittlerer Hitze 1 Minute schwenken, bis sich eine leicht cremige Emulsion bildet. Petersilie unterheben, mit Salz abschmecken und sofort servieren.",
    ],
    description: "Das schnellste Pastagericht Italiens aus Knoblauch, Olivenöl und Peperoncino, ein Klassiker der neapolitanischen Küche.",
    source: "klassiker",
  },
  {
    name: "Spaghetti alla carbonara",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Rom, Latium",
    veg: false,
    servings: 4,
    minutes: 25,
    ingredients: [
      "500 g Spaghetti",
      "200 g Guanciale",
      "4 Eigelb",
      "2 Eier",
      "120 g Pecorino romano, gerieben",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Reichlich Wasser aufkochen, leicht salzen und die Spaghetti nach Packungsangabe bissfest kochen.",
      "Guanciale in kurze Streifen schneiden und in einer großen Pfanne ohne Fett bei mittlerer Hitze 6 bis 8 Minuten knusprig auslassen. Pfanne vom Herd nehmen.",
      "Eigelb, Eier und 100 g Pecorino mit reichlich grob gemahlenem Pfeffer in einer Schüssel glatt verrühren.",
      "Eine Tasse Nudelwasser abschöpfen. Spaghetti abgießen und in die Pfanne zum Guanciale geben, kurz schwenken.",
      "Die Pfanne vom Herd nehmen, die Eiermasse zügig unterrühren und mit 3 bis 4 EL Nudelwasser cremig rühren. Die Eier dürfen nicht stocken.",
      "Mit dem restlichen Pecorino und Pfeffer bestreuen und sofort servieren.",
    ],
    description: "Der römische Klassiker aus Guanciale, Ei und Pecorino. Die Cremigkeit entsteht allein aus Eiern, Käse und Nudelwasser, ohne Sahne.",
    source: "klassiker",
  },
  {
    name: "Ragù alla bolognese",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Bologna, Emilia-Romagna",
    veg: false,
    servings: 4,
    minutes: 150,
    ingredients: [
      "500 g Tagliatelle",
      "600 g Rinderhackfleisch",
      "100 g Pancetta",
      "1 Zwiebel",
      "2 Möhren",
      "2 Selleriestangen",
      "3 EL Olivenöl",
      "200 ml trockener Rotwein",
      "3 EL Tomatenmark",
      "1 Dose Tomaten, gehackt",
      "300 ml Fleischbrühe",
      "150 ml Milch",
      "80 g Parmesan, gerieben",
      "Salz",
      "Pfeffer",
      "Muskatnuss",
    ],
    steps: [
      "Zwiebel, Möhren und Sellerie fein würfeln, Pancetta klein schneiden.",
      "Olivenöl in einem schweren Topf erhitzen. Pancetta 3 Minuten anbraten, dann das Gemüse zugeben und bei mittlerer Hitze 8 Minuten weich dünsten.",
      "Hackfleisch zugeben und bei starker Hitze krümelig anbraten, bis keine Flüssigkeit mehr im Topf ist, etwa 10 Minuten.",
      "Rotwein angießen und vollständig einkochen lassen. Tomatenmark einrühren und 2 Minuten mitrösten.",
      "Tomaten und Brühe zugeben, salzen und pfeffern. Zugedeckt bei kleinster Hitze mindestens 2 Stunden leise köcheln lassen, dabei gelegentlich umrühren und bei Bedarf etwas Wasser zugießen.",
      "In den letzten 15 Minuten die Milch einrühren und mit Muskat, Salz und Pfeffer abschmecken.",
      "Tagliatelle in reichlich Salzwasser bissfest kochen, abgießen, mit dem Ragù vermengen und mit Parmesan servieren.",
    ],
    description: "Die langsam geschmorte Fleischsoße aus Bologna, traditionell zu Tagliatelle serviert. Sie braucht Zeit, aber wenig Aufmerksamkeit.",
    source: "klassiker",
  },
  {
    name: "Lasagne al forno",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Emilia-Romagna",
    veg: false,
    servings: 4,
    minutes: 120,
    ingredients: [
      "12 Lasagneplatten",
      "500 g Rinderhackfleisch",
      "1 Zwiebel",
      "1 Möhre",
      "1 Selleriestange",
      "3 EL Olivenöl",
      "150 ml trockener Rotwein",
      "2 EL Tomatenmark",
      "2 Dosen Tomaten, gehackt",
      "60 g Butter",
      "60 g Mehl",
      "800 ml Milch",
      "120 g Parmesan, gerieben",
      "Salz",
      "Pfeffer",
      "Muskatnuss",
    ],
    steps: [
      "Zwiebel, Möhre und Sellerie fein würfeln und in Olivenöl bei mittlerer Hitze 8 Minuten andünsten. Hackfleisch zugeben und 10 Minuten krümelig braten.",
      "Mit Rotwein ablöschen und einkochen lassen. Tomatenmark und Tomaten zugeben, salzen und pfeffern und offen 40 Minuten köcheln lassen.",
      "Für die Béchamel Butter in einem Topf schmelzen, Mehl einrühren und 2 Minuten anschwitzen. Milch nach und nach unter Rühren zugießen und 5 Minuten köcheln, bis die Soße dicklich ist. Mit Salz, Pfeffer und Muskat würzen.",
      "Backofen auf 180 Grad Ober- und Unterhitze vorheizen. Eine Auflaufform mit etwas Béchamel ausstreichen.",
      "Abwechselnd Lasagneplatten, Ragù, Béchamel und Parmesan schichten, drei bis vier Lagen. Mit Béchamel und Parmesan abschließen.",
      "Im Ofen 40 Minuten backen, bis die Oberfläche goldbraun ist. Vor dem Anschneiden 10 Minuten ruhen lassen.",
    ],
    description: "Der italienische Ofenklassiker aus Nudelplatten, Ragù und Béchamel, wie er in der Emilia-Romagna gebacken wird.",
    source: "klassiker",
  },
  {
    name: "Pasta al pomodoro",
    category: "Schnelle Küche",
    cuisine: "Italienisch",
    origin: "Italien",
    veg: true,
    servings: 4,
    minutes: 30,
    ingredients: [
      "500 g Spaghetti",
      "2 Dosen Tomaten, geschält",
      "2 Zehen Knoblauch",
      "4 EL Olivenöl",
      "1 Bund Basilikum",
      "60 g Parmesan, gerieben",
      "1 Prise Zucker",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Knoblauch in Scheiben schneiden und in Olivenöl bei schwacher Hitze 2 Minuten anschwitzen, ohne dass er bräunt.",
      "Tomaten mit dem Saft zugeben, mit den Händen oder einem Löffel zerdrücken. Mit Salz, Pfeffer und Zucker würzen und offen bei mittlerer Hitze 20 Minuten einkochen lassen.",
      "Inzwischen Spaghetti in reichlich Salzwasser bissfest kochen und eine Tasse Nudelwasser abschöpfen.",
      "Die Hälfte der Basilikumblätter zerzupfen und in die Soße geben.",
      "Spaghetti abgießen, in die Soße geben und mit etwas Nudelwasser 1 Minute durchschwenken. Mit restlichem Basilikum und Parmesan servieren.",
    ],
    description: "Spaghetti mit der einfachsten italienischen Tomatensoße aus Dosentomaten, Knoblauch und Basilikum, in ganz Italien Alltagsessen und bei Kindern beliebt. Die Soße allein steht unter Tomatensoße.",
    source: "klassiker",
  },
  {
    name: "Pasta e fagioli",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Venetien und Mittelitalien",
    veg: true,
    servings: 4,
    minutes: 50,
    ingredients: [
      "250 g Ditalini",
      "2 Dosen Borlotti-Bohnen",
      "1 Zwiebel",
      "1 Möhre",
      "1 Selleriestange",
      "2 Zehen Knoblauch",
      "4 EL Olivenöl",
      "2 EL Tomatenmark",
      "1.2 l Gemüsebrühe",
      "2 Rosmarinzweige",
      "60 g Parmesan, gerieben",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Zwiebel, Möhre, Sellerie und Knoblauch fein würfeln. Bohnen abgießen und abspülen.",
      "Olivenöl in einem großen Topf erhitzen und das Gemüse mit dem Rosmarin bei mittlerer Hitze 8 Minuten andünsten.",
      "Tomatenmark einrühren, 1 Minute rösten, dann Bohnen und Brühe zugeben. Salzen, pfeffern und 15 Minuten köcheln lassen.",
      "Rosmarinzweige entfernen. Ein Drittel der Suppe mit dem Stabmixer pürieren, damit sie sämig wird.",
      "Ditalini direkt in der Suppe nach Packungsangabe bissfest kochen, dabei öfter umrühren und bei Bedarf Wasser zugießen.",
      "Mit Salz und Pfeffer abschmecken, mit Parmesan und einem Schuss Olivenöl servieren.",
    ],
    description: "Der sämige Eintopf aus Bohnen und kleinen Nudeln, ein Arme-Leute-Essen aus Italien, das in jeder Region etwas anders gekocht wird.",
    source: "klassiker",
  },
  {
    name: "Minestrone",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Norditalien",
    veg: true,
    servings: 4,
    minutes: 60,
    ingredients: [
      "1 Zwiebel",
      "2 Möhren",
      "2 Selleriestangen",
      "2 Kartoffeln",
      "1 Zucchini",
      "200 g grüne Bohnen",
      "200 g Wirsing",
      "1 Dose Cannellini-Bohnen",
      "1 Dose Tomaten, gehackt",
      "1.5 l Gemüsebrühe",
      "120 g Suppennudeln",
      "4 EL Olivenöl",
      "1 Parmesanrinde",
      "60 g Parmesan, gerieben",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Zwiebel, Möhren, Sellerie, Kartoffeln und Zucchini würfeln, grüne Bohnen in Stücke schneiden, Wirsing in Streifen schneiden.",
      "Olivenöl in einem großen Topf erhitzen. Zwiebel, Möhren und Sellerie darin bei mittlerer Hitze 8 Minuten andünsten.",
      "Kartoffeln, grüne Bohnen, Tomaten, Brühe und Parmesanrinde zugeben, salzen und 20 Minuten köcheln lassen.",
      "Zucchini, Wirsing, abgespülte Cannellini-Bohnen und Nudeln zugeben und weitere 12 Minuten kochen, bis die Nudeln gar sind.",
      "Parmesanrinde entfernen, mit Salz und Pfeffer abschmecken und mit geriebenem Parmesan und Olivenöl servieren.",
    ],
    description: "Die dicke italienische Gemüsesuppe mit Bohnen und Nudeln, deren Zutaten sich nach Jahreszeit und Vorrat richten.",
    source: "klassiker",
  },
  {
    name: "Risotto alla milanese",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Mailand, Lombardei",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "400 g Risottoreis",
      "1 Zwiebel",
      "80 g Butter",
      "150 ml trockener Weißwein",
      "1.2 l Gemüsebrühe",
      "1 Päckchen Safranfäden",
      "80 g Parmesan, gerieben",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Brühe in einem Topf erhitzen und heiß halten. Safran in 3 EL heißer Brühe einweichen.",
      "Zwiebel fein würfeln und in 40 g Butter bei mittlerer Hitze 5 Minuten glasig dünsten.",
      "Reis zugeben und 2 Minuten unter Rühren anrösten, bis die Körner glasig sind. Mit Weißwein ablöschen und einkochen lassen.",
      "Nach und nach heiße Brühe schöpflöffelweise zugießen, immer erst, wenn die vorige Menge aufgesogen ist. Dabei häufig rühren, insgesamt etwa 18 Minuten.",
      "Nach 12 Minuten den Safran mit der Einweichflüssigkeit einrühren.",
      "Wenn der Reis bissfest und cremig ist, vom Herd nehmen, restliche Butter und Parmesan unterrühren, salzen, pfeffern und 2 Minuten zugedeckt ruhen lassen.",
    ],
    description: "Das goldgelbe Safranrisotto aus Mailand, traditionell Beilage zum Ossobuco und ebenso als eigenständiges Gericht geschätzt.",
    source: "klassiker",
  },
  {
    name: "Risotto ai funghi",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Norditalien",
    veg: true,
    servings: 4,
    minutes: 45,
    ingredients: [
      "400 g Risottoreis",
      "400 g braune Champignons",
      "20 g Steinpilze, getrocknet",
      "1 Zwiebel",
      "2 Zehen Knoblauch",
      "60 g Butter",
      "3 EL Olivenöl",
      "150 ml trockener Weißwein",
      "1.2 l Gemüsebrühe",
      "80 g Parmesan, gerieben",
      "0.5 Bund Petersilie",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Steinpilze in 200 ml heißem Wasser 20 Minuten einweichen, herausnehmen und hacken. Einweichwasser durch ein feines Sieb zur Brühe gießen und die Brühe heiß halten.",
      "Champignons in Scheiben schneiden und in Olivenöl bei starker Hitze 6 Minuten goldbraun braten, salzen und beiseitestellen.",
      "Zwiebel und Knoblauch fein würfeln und in 30 g Butter 5 Minuten glasig dünsten. Reis zugeben und 2 Minuten anrösten, mit Weißwein ablöschen und einkochen lassen.",
      "Steinpilze zugeben und die heiße Brühe schöpflöffelweise zugießen, immer erst, wenn die vorige Menge aufgesogen ist. Etwa 18 Minuten unter häufigem Rühren garen.",
      "Champignons unterheben, Risotto vom Herd nehmen und restliche Butter sowie Parmesan unterrühren.",
      "Mit Salz und Pfeffer abschmecken, 2 Minuten ruhen lassen und mit gehackter Petersilie servieren.",
    ],
    description: "Pilzrisotto aus Norditalien, bei dem getrocknete Steinpilze für die Tiefe und frische Champignons für den Biss sorgen.",
    source: "klassiker",
  },
  {
    name: "Pizza Margherita",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Neapel, Kampanien",
    veg: true,
    servings: 4,
    minutes: 110,
    ingredients: [
      "600 g Weizenmehl",
      "350 ml Wasser",
      "0.5 Päckchen Trockenhefe",
      "2 TL Salz",
      "2 EL Olivenöl",
      "1 Dose Tomaten, geschält",
      "300 g Mozzarella",
      "1 Bund Basilikum",
      "Salz",
    ],
    steps: [
      "Mehl (Type 405), Trockenhefe und Salz mischen, lauwarmes Wasser und Olivenöl zugeben und 10 Minuten zu einem glatten, elastischen Teig kneten.",
      "Teig zugedeckt an einem warmen Ort 1 Stunde gehen lassen, bis er sich verdoppelt hat. Länger ruhen, zum Beispiel über Nacht im Kühlschrank, verbessert den Teig.",
      "Tomaten abgießen, mit den Händen zerdrücken und mit einer Prise Salz würzen. Mozzarella in Scheiben schneiden und abtropfen lassen.",
      "Backofen mit Blech oder Pizzastein auf höchste Stufe, mindestens 250 Grad, vorheizen.",
      "Teig in 4 Stücke teilen und jedes mit den Händen auf bemehlter Fläche dünn ausziehen, der Rand bleibt etwas dicker.",
      "Böden dünn mit Tomaten bestreichen, mit Mozzarella belegen und nacheinander 8 bis 10 Minuten backen, bis der Rand gebräunt ist. Mit Basilikumblättern und etwas Olivenöl servieren.",
    ],
    description: "Die neapolitanische Pizza in den Farben Italiens aus Tomate, Mozzarella und Basilikum. Der Hefeteig braucht mindestens eine Stunde Ruhe, die Böden werden nacheinander gebacken.",
    source: "klassiker",
  },
  {
    name: "Saltimbocca alla romana",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Rom, Latium",
    veg: false,
    servings: 4,
    minutes: 30,
    ingredients: [
      "8 Kalbsschnitzel, dünn",
      "8 Scheiben Parmaschinken",
      "8 Salbeiblätter",
      "60 g Butter",
      "2 EL Mehl",
      "150 ml trockener Weißwein",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Kalbsschnitzel zwischen Frischhaltefolie dünn klopfen und leicht pfeffern.",
      "Auf jedes Schnitzel eine Scheibe Parmaschinken und ein Salbeiblatt legen und mit einem Zahnstocher feststecken.",
      "Schnitzel auf der Fleischseite leicht mit Mehl bestäuben.",
      "40 g Butter in einer großen Pfanne bei mittlerer bis starker Hitze aufschäumen lassen. Schnitzel zuerst mit der Schinkenseite nach unten 2 Minuten braten, wenden und weitere 1 bis 2 Minuten braten. Herausnehmen und warm stellen.",
      "Weißwein in die Pfanne gießen, Bratensatz lösen und 2 Minuten einkochen lassen. Restliche Butter einrühren und mit Salz abschmecken.",
      "Saltimbocca mit der Soße servieren, dazu passen Risotto oder Brot.",
    ],
    description: "Römische Kalbsschnitzel mit Schinken und Salbei, die so gut schmecken, dass sie laut Namen in den Mund springen.",
    source: "klassiker",
  },
  {
    name: "Insalata caprese",
    category: "Beilagen & Salate",
    cuisine: "Italienisch",
    origin: "Capri, Kampanien",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "4 Tomaten",
      "250 g Büffelmozzarella",
      "1 Bund Basilikum",
      "4 EL Olivenöl",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Tomaten waschen, Stielansatz entfernen und in gleichmäßige Scheiben schneiden.",
      "Mozzarella abtropfen lassen und ebenfalls in Scheiben schneiden.",
      "Tomaten und Mozzarella abwechselnd auf einer Platte dachziegelartig anrichten.",
      "Mit Salz und Pfeffer würzen, Basilikumblätter darüber verteilen und mit Olivenöl beträufeln. 10 Minuten bei Raumtemperatur durchziehen lassen.",
    ],
    description: "Der Salat von der Insel Capri aus Tomate, Mozzarella und Basilikum, der nur mit reifen Tomaten gelingt.",
    source: "klassiker",
  },
  {
    name: "Panzanella",
    category: "Beilagen & Salate",
    cuisine: "Italienisch",
    origin: "Toskana",
    veg: true,
    servings: 4,
    minutes: 25,
    ingredients: [
      "300 g Weißbrot vom Vortag",
      "600 g Tomaten",
      "1 Salatgurke",
      "1 rote Zwiebel",
      "1 Bund Basilikum",
      "6 EL Olivenöl",
      "3 EL Rotweinessig",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Brot in grobe Würfel schneiden und auf einem Blech im Ofen bei 180 Grad 10 Minuten rösten, bis es trocken und leicht gebräunt ist.",
      "Tomaten in Stücke schneiden, dabei den Saft auffangen. Gurke schälen und würfeln, Zwiebel in feine Ringe schneiden.",
      "Olivenöl, Essig, Tomatensaft, Salz und Pfeffer zu einem Dressing verrühren.",
      "Brot, Tomaten, Gurke und Zwiebel in einer Schüssel mischen, Dressing darüber geben und gut vermengen.",
      "Basilikumblätter zerzupfen und unterheben. Salat 15 Minuten ziehen lassen, damit das Brot sich vollsaugt, dann servieren.",
    ],
    description: "Der toskanische Brotsalat aus altbackenem Weißbrot, Tomaten und Zwiebeln, im Sommer ein ganzes Essen.",
    source: "klassiker",
  },
  {
    name: "Gnocchi mit Salbeibutter",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Norditalien",
    veg: true,
    servings: 4,
    minutes: 60,
    ingredients: [
      "1 kg Kartoffeln, mehligkochend",
      "250 g Weizenmehl",
      "1 Ei",
      "100 g Butter",
      "16 Salbeiblätter",
      "80 g Parmesan, gerieben",
      "Salz",
      "Pfeffer",
      "Muskatnuss",
    ],
    steps: [
      "Kartoffeln mit Schale in Salzwasser 25 Minuten weich kochen, abgießen, kurz ausdampfen lassen, noch heiß schälen und durch die Kartoffelpresse drücken.",
      "Kartoffelmasse etwas abkühlen lassen, mit Mehl (Type 405), Ei, 1 TL Salz und Muskat rasch zu einem glatten Teig verkneten, nicht zu lange, sonst wird er zäh.",
      "Teig auf bemehlter Fläche zu fingerdicken Rollen formen, in 2 cm lange Stücke schneiden und nach Wunsch über eine Gabel rollen.",
      "Reichlich Salzwasser aufkochen. Gnocchi portionsweise hineingeben und herausnehmen, sobald sie an die Oberfläche steigen, etwa 2 bis 3 Minuten.",
      "Butter in einer großen Pfanne bei mittlerer Hitze aufschäumen lassen, Salbeiblätter zugeben und 2 Minuten braten, bis die Butter nussig duftet.",
      "Gnocchi in der Salbeibutter schwenken, mit Parmesan und Pfeffer servieren.",
    ],
    description: "Selbst gemachte Kartoffelgnocchi in gebräunter Salbeibutter, ein Klassiker aus Norditalien, der nur wenige Zutaten braucht.",
    source: "klassiker",
  },
  {
    name: "Pollo alla cacciatora",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Toskana und Mittelitalien",
    veg: false,
    servings: 4,
    minutes: 75,
    ingredients: [
      "8 Hähnchenschenkel",
      "1 Zwiebel",
      "2 Zehen Knoblauch",
      "1 Möhre",
      "1 Selleriestange",
      "4 EL Olivenöl",
      "200 ml trockener Rotwein",
      "1 Dose Tomaten, gehackt",
      "100 g schwarze Oliven",
      "2 Rosmarinzweige",
      "1 Lorbeerblatt",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Hähnchenschenkel trocken tupfen, salzen und pfeffern. Zwiebel, Knoblauch, Möhre und Sellerie fein würfeln.",
      "Olivenöl in einem Schmortopf erhitzen und die Schenkel bei starker Hitze rundherum 8 Minuten goldbraun anbraten, herausnehmen.",
      "Gemüse im Bratfett bei mittlerer Hitze 6 Minuten andünsten. Mit Rotwein ablöschen und auf die Hälfte einkochen lassen.",
      "Tomaten, Rosmarin und Lorbeer zugeben, Hähnchen wieder einlegen und zugedeckt bei schwacher Hitze 40 Minuten schmoren.",
      "Oliven zugeben und offen weitere 10 Minuten schmoren, bis die Soße eingedickt ist.",
      "Kräuterzweige entfernen, mit Salz und Pfeffer abschmecken und mit Brot oder Polenta servieren.",
    ],
    description: "Hähnchen nach Jägerart, in Tomaten, Rotwein und Kräutern geschmort, ein ländlicher Klassiker aus Mittelitalien.",
    source: "klassiker",
  },
  {
    name: "Pesto alla genovese",
    category: "Soßen & Dips",
    cuisine: "Italienisch",
    origin: "Genua, Ligurien",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "2 Bund Basilikum",
      "40 g Pinienkerne",
      "1 Zehe Knoblauch",
      "60 g Parmesan, gerieben",
      "30 g Pecorino, gerieben",
      "120 ml Olivenöl",
      "Salz",
    ],
    steps: [
      "Pinienkerne in einer Pfanne ohne Fett bei mittlerer Hitze 3 Minuten hellbraun rösten und abkühlen lassen.",
      "Basilikumblätter abzupfen, waschen und gründlich trocken tupfen.",
      "Knoblauch, Pinienkerne und eine Prise Salz im Mörser oder Mixer fein zerkleinern.",
      "Basilikum zugeben und zu einer groben Paste verarbeiten, dabei nur kurz mixen, damit das Pesto nicht warm wird.",
      "Parmesan und Pecorino unterrühren, Olivenöl nach und nach einarbeiten und mit Salz abschmecken. Reicht für 500 g Pasta, mit etwas Nudelwasser verdünnt.",
    ],
    description: "Die ligurische Basilikumsoße aus Genua, kalt gerührt aus Basilikum, Pinienkernen, Knoblauch, Käse und Olivenöl.",
    source: "klassiker",
  },
  {
    name: "Melanzane alla parmigiana",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Süditalien",
    veg: true,
    servings: 4,
    minutes: 90,
    ingredients: [
      "1.2 kg Auberginen",
      "2 Dosen Tomaten, geschält",
      "2 Zehen Knoblauch",
      "300 g Mozzarella",
      "100 g Parmesan, gerieben",
      "1 Bund Basilikum",
      "150 ml Olivenöl",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Auberginen längs in 1 cm dicke Scheiben schneiden, salzen und 30 Minuten Wasser ziehen lassen, dann trocken tupfen.",
      "Knoblauch in Scheiben schneiden und in 3 EL Olivenöl anschwitzen. Tomaten zugeben, zerdrücken, salzen und 20 Minuten zu einer dicken Soße einkochen. Die Hälfte des Basilikums unterrühren.",
      "Auberginenscheiben portionsweise im restlichen Olivenöl bei mittlerer bis starker Hitze von beiden Seiten je 3 Minuten goldbraun braten und auf Küchenpapier abtropfen lassen.",
      "Backofen auf 180 Grad Ober- und Unterhitze vorheizen. Mozzarella in Scheiben schneiden.",
      "In einer Auflaufform Tomatensoße, Auberginen, Mozzarella, Parmesan und Basilikum schichten, mit Soße und Parmesan abschließen.",
      "Im Ofen 35 Minuten backen, bis die Oberfläche gebräunt ist, und 10 Minuten ruhen lassen.",
    ],
    description: "Der süditalienische Auberginenauflauf mit Tomatensoße, Mozzarella und Parmesan, in Kampanien und Sizilien gleichermaßen zu Hause.",
    source: "klassiker",
  },
  {
    name: "Pasta alla norma",
    category: "Hauptgericht",
    cuisine: "Italienisch",
    origin: "Catania, Sizilien",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "500 g Rigatoni",
      "2 Auberginen",
      "2 Dosen Tomaten, geschält",
      "2 Zehen Knoblauch",
      "120 ml Olivenöl",
      "100 g Ricotta salata, gerieben",
      "1 Bund Basilikum",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Auberginen in 2 cm große Würfel schneiden und salzen. Knoblauch in Scheiben schneiden.",
      "Knoblauch in 3 EL Olivenöl bei schwacher Hitze anschwitzen, Tomaten zugeben und zerdrücken. Salzen, pfeffern und 20 Minuten offen einkochen lassen.",
      "Auberginen trocken tupfen und im restlichen Olivenöl portionsweise bei starker Hitze 6 bis 8 Minuten goldbraun braten, auf Küchenpapier abtropfen lassen.",
      "Rigatoni in reichlich Salzwasser bissfest kochen.",
      "Pasta abgießen, mit der Tomatensoße und zwei Dritteln der Auberginen vermengen. Basilikum zerzupfen und unterheben.",
      "Mit restlichen Auberginen und reichlich Ricotta salata bestreut servieren.",
    ],
    description: "Sizilianische Pasta mit gebratenen Auberginen, Tomatensoße und gesalzenem Ricotta, benannt nach Bellinis Oper Norma.",
    source: "klassiker",
  },
  {
    name: "Ratatouille",
    category: "Hauptgericht",
    cuisine: "Mediterran",
    origin: "Nizza, Provence",
    veg: true,
    servings: 4,
    minutes: 60,
    ingredients: [
      "2 Auberginen",
      "2 Zucchini",
      "2 rote Paprika",
      "600 g Tomaten",
      "2 Zwiebeln",
      "3 Zehen Knoblauch",
      "100 ml Olivenöl",
      "3 Thymianzweige",
      "1 Lorbeerblatt",
      "1 Bund Basilikum",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Auberginen, Zucchini und Paprika in 2 cm große Stücke schneiden, Zwiebeln in Streifen, Knoblauch fein hacken. Tomaten überbrühen, häuten und würfeln.",
      "Auberginen in 3 EL Olivenöl bei starker Hitze 6 Minuten anbraten und herausnehmen. Zucchini und Paprika nacheinander ebenso in je 2 EL Öl anbraten und herausnehmen.",
      "Zwiebeln und Knoblauch im restlichen Öl bei mittlerer Hitze 5 Minuten weich dünsten.",
      "Tomaten, Thymian und Lorbeer zugeben, salzen und 10 Minuten einkochen lassen.",
      "Gebratenes Gemüse zugeben und zugedeckt bei schwacher Hitze 25 Minuten schmoren, bis alles weich ist, aber noch Form hat.",
      "Kräuterzweige entfernen, mit Salz und Pfeffer abschmecken und mit zerzupftem Basilikum servieren, warm oder lauwarm.",
    ],
    description: "Das provenzalische Schmorgemüse aus Auberginen, Zucchini, Paprika und Tomaten, bei dem jede Sorte einzeln angebraten wird.",
    source: "klassiker",
  },
  {
    name: "Quiche Lorraine",
    category: "Hauptgericht",
    cuisine: "Mediterran",
    origin: "Lothringen, Frankreich",
    veg: false,
    servings: 4,
    minutes: 75,
    ingredients: [
      "250 g Weizenmehl",
      "125 g Butter",
      "1 Ei",
      "200 g durchwachsener Speck",
      "4 Eier",
      "200 ml Sahne",
      "200 ml Milch",
      "Salz",
      "Pfeffer",
      "Muskatnuss",
    ],
    steps: [
      "Mehl (Type 405), kalte Butter in Stücken, 1 Ei und 0.5 TL Salz rasch zu einem glatten Mürbeteig verkneten, zur Kugel formen und 30 Minuten kalt stellen.",
      "Backofen auf 200 Grad Ober- und Unterhitze vorheizen. Teig ausrollen, eine Quicheform von 28 cm damit auslegen und einen Rand hochziehen. Boden mehrfach mit der Gabel einstechen.",
      "Teig mit Backpapier und Hülsenfrüchten beschweren und 15 Minuten blindbacken, Papier und Hülsenfrüchte entfernen.",
      "Speck in Streifen schneiden und in einer Pfanne bei mittlerer Hitze 5 Minuten knusprig braten, auf Küchenpapier abtropfen lassen.",
      "Eier, Sahne und Milch verquirlen, mit Salz, Pfeffer und Muskat würzen.",
      "Speck auf dem Boden verteilen, Eiermilch darüber gießen und bei 180 Grad 35 Minuten backen, bis die Füllung gestockt und goldbraun ist. 10 Minuten ruhen lassen.",
    ],
    description: "Der herzhafte Speckkuchen aus Lothringen mit Mürbeteig und Eiersahne, im Original ohne Käse.",
    source: "klassiker",
  },
  {
    name: "Griechischer Bauernsalat",
    category: "Beilagen & Salate",
    cuisine: "Mediterran",
    origin: "Griechenland",
    veg: true,
    servings: 4,
    minutes: 20,
    ingredients: [
      "600 g Tomaten",
      "1 Salatgurke",
      "1 grüne Paprika",
      "1 rote Zwiebel",
      "200 g Feta",
      "100 g Kalamata-Oliven",
      "6 EL Olivenöl",
      "2 EL Rotweinessig",
      "1 TL Oregano, getrocknet",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Tomaten in grobe Stücke schneiden, Gurke längs halbieren und in dicke Scheiben schneiden, Paprika in Ringe, Zwiebel in feine Ringe schneiden.",
      "Gemüse mit den Oliven in einer Schüssel mischen, leicht salzen und pfeffern.",
      "Olivenöl und Essig verrühren und über den Salat geben, vorsichtig vermengen.",
      "Feta im Ganzen oder in großen Stücken obenauf legen, mit Oregano bestreuen und mit etwas Olivenöl beträufeln. Sofort servieren, dazu Weißbrot.",
    ],
    description: "Der griechische Horiatiki aus Tomaten, Gurke, Zwiebel, Oliven und Feta, traditionell ohne Blattsalat.",
    source: "klassiker",
  },
  {
    name: "Souvlaki mit Tzatziki",
    category: "Hauptgericht",
    cuisine: "Mediterran",
    origin: "Griechenland",
    veg: false,
    servings: 4,
    minutes: 45,
    ingredients: [
      "800 g Schweinenacken",
      "6 EL Olivenöl",
      "2 Zitronen",
      "3 Zehen Knoblauch",
      "2 TL Oregano, getrocknet",
      "500 g griechischer Joghurt",
      "1 Salatgurke",
      "1 EL Weißweinessig",
      "4 Fladenbrote",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Fleisch in 3 cm große Würfel schneiden. Mit 4 EL Olivenöl, Saft einer Zitrone, 2 gepressten Knoblauchzehen, Oregano, Salz und Pfeffer mischen und mindestens 30 Minuten marinieren, besser über Nacht.",
      "Für das Tzatziki die Gurke grob reiben, salzen, 10 Minuten ziehen lassen und kräftig ausdrücken. Mit Joghurt, 1 gepressten Knoblauchzehe, Essig, 2 EL Olivenöl, Salz und Pfeffer verrühren und kalt stellen.",
      "Fleisch auf 8 Spieße stecken. Holzspieße vorher 20 Minuten wässern.",
      "Spieße auf dem heißen Grill oder in einer Grillpfanne bei starker Hitze rundherum 10 bis 12 Minuten grillen, bis sie außen gebräunt und innen gar sind.",
      "Fladenbrote kurz mit angrillen. Souvlaki mit Zitronenspalten, Tzatziki und Brot servieren.",
    ],
    description: "Griechische Fleischspieße in Zitronen-Oregano-Marinade mit Tzatziki, das Grillgericht der Tavernen und Straßenstände.",
    source: "klassiker",
  },
  {
    name: "Moussaka",
    category: "Hauptgericht",
    cuisine: "Mediterran",
    origin: "Griechenland",
    veg: false,
    servings: 4,
    minutes: 110,
    ingredients: [
      "1 kg Auberginen",
      "500 g Kartoffeln",
      "600 g Lammhackfleisch",
      "2 Zwiebeln",
      "3 Zehen Knoblauch",
      "100 ml Olivenöl",
      "2 EL Tomatenmark",
      "1 Dose Tomaten, gehackt",
      "100 ml Rotwein",
      "1 TL Zimt",
      "1 TL Oregano, getrocknet",
      "60 g Butter",
      "60 g Mehl",
      "700 ml Milch",
      "2 Eigelb",
      "80 g Parmesan, gerieben",
      "Salz",
      "Pfeffer",
      "Muskatnuss",
    ],
    steps: [
      "Auberginen in 1 cm dicke Scheiben schneiden, salzen, 20 Minuten ziehen lassen und trocken tupfen. Kartoffeln schälen und in dünne Scheiben schneiden.",
      "Auberginen und Kartoffeln mit 6 EL Olivenöl bestreichen, auf Blechen verteilen und bei 200 Grad 20 Minuten im Ofen rösten.",
      "Zwiebeln und Knoblauch fein würfeln und im restlichen Öl 5 Minuten andünsten. Hackfleisch zugeben und 8 Minuten krümelig braten. Tomatenmark einrühren, mit Rotwein ablöschen, Tomaten, Zimt, Oregano, Salz und Pfeffer zugeben und 20 Minuten einkochen lassen.",
      "Butter schmelzen, Mehl einrühren und 2 Minuten anschwitzen. Milch unter Rühren zugießen, 5 Minuten köcheln, vom Herd nehmen und Eigelb, die Hälfte des Käses, Salz, Pfeffer und Muskat einrühren.",
      "Ofen auf 180 Grad stellen. In einer Auflaufform Kartoffeln, die Hälfte der Auberginen, die Hackfleischsoße und die restlichen Auberginen schichten. Béchamel darüber gießen und mit dem restlichen Käse bestreuen.",
      "Im Ofen 45 Minuten backen, bis die Oberfläche goldbraun ist. Vor dem Anschneiden 15 Minuten ruhen lassen.",
    ],
    description: "Der griechische Ofenauflauf aus Auberginen, Kartoffeln, Hackfleischsoße mit Zimt und einer dicken Béchamelhaube.",
    source: "klassiker",
  },
  {
    name: "Paella",
    category: "Hauptgericht",
    cuisine: "Mediterran",
    origin: "Valencia, Spanien",
    veg: false,
    servings: 4,
    minutes: 60,
    ingredients: [
      "400 g Paellareis",
      "600 g Hähnchenschenkel ohne Knochen",
      "200 g grüne Bohnen",
      "1 rote Paprika",
      "2 Tomaten",
      "3 Zehen Knoblauch",
      "6 EL Olivenöl",
      "1.2 l Hühnerbrühe",
      "1 Päckchen Safranfäden",
      "1 TL geräuchertes Paprikapulver",
      "2 Rosmarinzweige",
      "1 Zitrone",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Hähnchen in mundgerechte Stücke schneiden, salzen und pfeffern. Bohnen halbieren, Paprika in Streifen schneiden, Tomaten reiben, Knoblauch hacken. Safran in der heißen Brühe auflösen.",
      "Olivenöl in einer großen flachen Pfanne erhitzen und das Hähnchen bei starker Hitze 8 Minuten goldbraun anbraten.",
      "Bohnen und Paprika zugeben und 5 Minuten mitbraten. Knoblauch, geriebene Tomaten und Paprikapulver zugeben und 3 Minuten einkochen lassen.",
      "Reis einstreuen, kurz umrühren und gleichmäßig verteilen. Heiße Safranbrühe angießen, Rosmarin auflegen und salzen.",
      "Bei starker Hitze 8 Minuten kochen, dann die Hitze reduzieren und weitere 10 Minuten köcheln lassen, ohne umzurühren, bis die Flüssigkeit aufgesogen ist.",
      "Pfanne vom Herd nehmen, mit einem Tuch abdecken und 5 Minuten ruhen lassen. Mit Zitronenspalten servieren.",
    ],
    description: "Die valencianische Reispfanne mit Hähnchen, grünen Bohnen und Safran in einer einfachen Alltagsfassung ohne Meeresfrüchte.",
    source: "klassiker",
  },
  {
    name: "Tortilla española",
    category: "Hauptgericht",
    cuisine: "Mediterran",
    origin: "Spanien",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "800 g Kartoffeln, festkochend",
      "2 Zwiebeln",
      "8 Eier",
      "200 ml Olivenöl",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Kartoffeln schälen und in dünne Scheiben schneiden, Zwiebeln in feine Streifen schneiden.",
      "Olivenöl in einer beschichteten Pfanne von 26 cm erhitzen. Kartoffeln und Zwiebeln darin bei mittlerer Hitze 20 Minuten weich garen, ohne dass sie bräunen, dabei gelegentlich wenden.",
      "Kartoffeln in ein Sieb abgießen und das Öl auffangen. Eier mit Salz und Pfeffer verquirlen und die noch warmen Kartoffeln unterheben, 5 Minuten ziehen lassen.",
      "2 EL des Öls wieder in die Pfanne geben, Eiermasse einfüllen und bei mittlerer bis schwacher Hitze 6 Minuten stocken lassen, bis der Rand fest ist.",
      "Tortilla mit einem großen Teller wenden, zurück in die Pfanne gleiten lassen und weitere 4 Minuten braten. Innen darf sie noch leicht saftig sein.",
      "Lauwarm oder kalt in Stücken servieren, dazu Brot und Salat.",
    ],
    description: "Das spanische Kartoffelomelett aus Kartoffeln, Zwiebeln und Eiern, als Tapa, Hauptgericht und Reiseproviant verbreitet.",
    source: "klassiker",
  },
  {
    name: "Gazpacho",
    category: "Schnelle Küche",
    cuisine: "Mediterran",
    origin: "Andalusien, Spanien",
    veg: true,
    servings: 4,
    minutes: 20,
    ingredients: [
      "1 kg Tomaten",
      "1 Salatgurke",
      "1 grüne Paprika",
      "1 Zehe Knoblauch",
      "60 g Weißbrot vom Vortag",
      "6 EL Olivenöl",
      "2 EL Sherryessig",
      "Salz",
    ],
    steps: [
      "Brot in Wasser einweichen und ausdrücken. Tomaten grob würfeln, Gurke schälen und würfeln, Paprika entkernen und würfeln, Knoblauch schälen.",
      "Alle Zutaten mit Essig und Salz im Mixer 2 Minuten fein pürieren.",
      "Olivenöl bei laufendem Mixer langsam zugießen, bis die Suppe cremig und hell wird.",
      "Suppe durch ein feines Sieb streichen und mit Salz und Essig abschmecken. Bei Bedarf mit kaltem Wasser verdünnen.",
      "Mindestens 2 Stunden kalt stellen und eiskalt servieren, nach Belieben mit fein gewürfelter Gurke, Paprika und Brotwürfeln.",
    ],
    description: "Die kalte andalusische Tomatensuppe aus rohem Gemüse, Brot, Olivenöl und Essig. Die Zubereitung ist kurz, das Kühlen dauert zwei Stunden.",
    source: "klassiker",
  },
];
