// Klassiker-Basis: Moderne Alltagsküche, Frühstück, Kinderessen, Schnelle Küche,
// Beilagen & Salate, Soßen & Dips und Snacks. Etablierte Standards, Mengen für 4 Personen.
// Form siehe docs/ARCHITEKTUR.md, Abschnitt 3 "Recipe" (source "klassiker", origin Pflicht).

export default [
  // ---------------------------------------------------------------- Frühstück
  {
    name: "Porridge",
    category: "Frühstück",
    cuisine: "International",
    origin: "Schottland",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "200 g zarte Haferflocken",
      "500 ml Milch",
      "500 ml Wasser",
      "1 Prise Salz",
      "2 EL Honig",
      "1 TL Zimt",
      "2 Äpfel",
      "4 EL Nüsse, gehackt",
    ],
    steps: [
      "Haferflocken mit Milch, Wasser und Salz in einen Topf geben und unter Rühren aufkochen.",
      "Hitze auf klein stellen und den Brei 8 bis 10 Minuten leise köcheln lassen, dabei regelmäßig umrühren, bis er cremig ist.",
      "Währenddessen die Äpfel waschen, entkernen und in kleine Würfel oder dünne Spalten schneiden.",
      "Topf vom Herd nehmen, Honig und Zimt einrühren und den Porridge 2 Minuten quellen lassen.",
      "In Schalen füllen, mit Apfel und Nüssen bestreuen und warm servieren.",
    ],
    description: "Der schottische Haferbrei, der sich als warmes Frühstück in ganz Europa durchgesetzt hat; cremig gekocht und mit Obst und Nüssen belegt.",
    source: "klassiker",
  },
  {
    name: "Overnight Oats",
    category: "Frühstück",
    cuisine: "International",
    origin: "International",
    veg: true,
    servings: 4,
    minutes: 10,
    ingredients: [
      "200 g kernige Haferflocken",
      "4 EL Chiasamen",
      "500 ml Milch",
      "300 g Naturjoghurt",
      "2 EL Ahornsirup",
      "1 TL Vanillezucker",
      "300 g Beeren",
      "4 EL Mandelblättchen",
    ],
    steps: [
      "Haferflocken, Chiasamen, Milch, Joghurt, Ahornsirup und Vanillezucker in einer Schüssel gründlich verrühren.",
      "Die Masse auf 4 Gläser oder Schraubgläser verteilen und verschließen.",
      "Gläser über Nacht, mindestens 6 Stunden, in den Kühlschrank stellen, damit die Flocken quellen.",
      "Am Morgen kurz umrühren und bei Bedarf einen Schuss Milch unterziehen, falls die Masse zu fest ist.",
      "Beeren waschen, auf die Gläser verteilen und mit Mandelblättchen bestreuen.",
    ],
    description: "Kalt eingeweichte Haferflocken, die über Nacht im Kühlschrank quellen; das moderne Frühstück zum Vorbereiten, die Zubereitungszeit gilt ohne die Nacht im Kühlschrank.",
    source: "klassiker",
  },
  {
    name: "Birchermüsli",
    category: "Frühstück",
    cuisine: "Klassisch",
    origin: "Schweiz",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "200 g zarte Haferflocken",
      "300 ml Milch",
      "300 g Naturjoghurt",
      "3 Äpfel",
      "1 Zitrone",
      "2 EL Honig",
      "60 g Haselnüsse, gehackt",
      "50 g Rosinen",
    ],
    steps: [
      "Haferflocken mit Milch in einer Schüssel verrühren und mindestens 10 Minuten, besser über Nacht, einweichen.",
      "Zitrone auspressen, Äpfel waschen und mit Schale grob reiben und sofort mit dem Zitronensaft vermischen, damit sie nicht braun werden.",
      "Joghurt, Honig und Rosinen unter die eingeweichten Flocken rühren.",
      "Geriebene Äpfel unterheben und das Müsli abschmecken, bei Bedarf noch etwas Milch zugeben.",
      "In Schalen füllen und mit den gehackten Haselnüssen bestreuen.",
    ],
    description: "Das Schweizer Original nach dem Arzt Maximilian Bircher-Benner: eingeweichte Haferflocken mit geriebenem Apfel, Joghurt und Nüssen.",
    source: "klassiker",
  },
  {
    name: "Pancakes",
    category: "Frühstück",
    cuisine: "International",
    origin: "USA",
    veg: true,
    servings: 4,
    minutes: 30,
    ingredients: [
      "300 g Mehl",
      "2 TL Backpulver",
      "2 EL Zucker",
      "1 Prise Salz",
      "2 Eier",
      "350 ml Milch",
      "40 g Butter",
      "Ahornsirup",
      "200 g Blaubeeren",
    ],
    steps: [
      "Mehl, Backpulver, Zucker und Salz in einer Schüssel mischen.",
      "Butter schmelzen, Eier und Milch verquirlen und mit der flüssigen Butter zum Mehl geben, nur kurz zu einem leicht klumpigen Teig verrühren.",
      "Teig 5 Minuten ruhen lassen, dann eine beschichtete Pfanne bei mittlerer Hitze erwärmen und dünn fetten.",
      "Je 1 kleine Kelle Teig in die Pfanne geben und backen, bis an der Oberfläche Blasen entstehen, etwa 2 Minuten.",
      "Wenden und weitere 1 bis 2 Minuten goldbraun backen, fertige Pancakes im Ofen bei 80 °C warm halten.",
      "Gestapelt mit Ahornsirup und Blaubeeren servieren.",
    ],
    description: "Dicke, fluffige Pfannkuchen aus Nordamerika, die mit Backpulver aufgehen und klassisch mit Ahornsirup gegessen werden.",
    source: "klassiker",
  },
  {
    name: "Arme Ritter",
    category: "Frühstück",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 25,
    ingredients: [
      "8 Scheiben Toastbrot",
      "3 Eier",
      "250 ml Milch",
      "4 EL Zucker",
      "1 TL Vanillezucker",
      "1 Prise Salz",
      "40 g Butter",
      "1 TL Zimt",
      "Apfelmus",
    ],
    steps: [
      "Eier mit Milch, der Hälfte des Zuckers, Vanillezucker und Salz in einem tiefen Teller verquirlen.",
      "Die Brotscheiben nacheinander von beiden Seiten in die Eiermilch legen, bis sie sich vollgesogen haben, aber nicht zerfallen.",
      "Butter in einer großen Pfanne bei mittlerer Hitze zerlassen.",
      "Die getränkten Scheiben portionsweise 2 bis 3 Minuten je Seite goldbraun ausbacken.",
      "Restlichen Zucker mit Zimt mischen, die heißen Scheiben darin wenden und mit Apfelmus servieren.",
    ],
    description: "Altbackenes Brot in Eiermilch getränkt und in Butter gebacken; in Frankreich Pain perdu, in den USA French Toast, bei uns seit Jahrhunderten Arme Ritter.",
    source: "klassiker",
  },
  {
    name: "Omelett mit Kräutern",
    category: "Frühstück",
    cuisine: "Klassisch",
    origin: "Frankreich",
    veg: true,
    servings: 4,
    minutes: 20,
    ingredients: [
      "8 Eier",
      "4 EL Milch",
      "1 Bund Schnittlauch",
      "1 Bund Petersilie",
      "1 Bund Kerbel",
      "40 g Butter",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Kräuter waschen, trocken schütteln und fein hacken.",
      "Für jedes Omelett 2 Eier mit 1 EL Milch, Salz und Pfeffer verquirlen und einen Viertel der Kräuter unterrühren.",
      "10 g Butter in einer kleinen beschichteten Pfanne bei mittlerer Hitze schmelzen, bis sie schäumt.",
      "Eiermasse eingießen und mit dem Pfannenwender die stockende Masse vom Rand zur Mitte schieben, bis sie unten gestockt und oben noch leicht cremig ist, etwa 2 Minuten.",
      "Omelett zusammenklappen, auf einen Teller gleiten lassen und die übrigen drei Omeletts genauso zubereiten.",
    ],
    description: "Das klassische französische Kräuteromelett, innen noch leicht cremig, mit Schnittlauch, Petersilie und Kerbel.",
    source: "klassiker",
  },

  // ---------------------------------------------------------------- Kinderessen
  {
    name: "Fischstäbchen mit Kartoffelpüree und Erbsen",
    category: "Kinderessen",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 35,
    ingredients: [
      "16 Fischstäbchen",
      "1 kg Kartoffeln, mehligkochend",
      "200 ml Milch",
      "50 g Butter",
      "Muskat",
      "450 g Tiefkühlerbsen",
      "3 EL Rapsöl",
      "Salz",
      "Pfeffer",
      "1 Zitrone",
    ],
    steps: [
      "Kartoffeln schälen, in Stücke schneiden und in Salzwasser 20 Minuten weich kochen.",
      "Erbsen mit wenig Wasser, etwas Salz und 1 TL Butter in einem kleinen Topf 5 Minuten garen.",
      "Rapsöl in einer großen Pfanne bei mittlerer Hitze erhitzen und die Fischstäbchen 4 bis 5 Minuten je Seite goldbraun braten.",
      "Kartoffeln abgießen, Milch und restliche Butter erhitzen und die Kartoffeln mit dem Stampfer zu einem glatten Püree verarbeiten, mit Salz und Muskat würzen.",
      "Fischstäbchen mit Püree, Erbsen und Zitronenspalten anrichten.",
    ],
    description: "Der Klassiker vom Kindertisch: knusprige Fischstäbchen mit selbst gemachtem Kartoffelpüree und Buttererbsen.",
    source: "klassiker",
  },
  {
    name: "Pfannkuchen",
    category: "Kinderessen",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "300 g Mehl",
      "4 Eier",
      "500 ml Milch",
      "1 EL Zucker",
      "1 Prise Salz",
      "4 EL Butterschmalz",
      "Zucker, zum Bestreuen",
      "Zimt",
      "Apfelmus",
    ],
    steps: [
      "Mehl mit Zucker und Salz in eine Schüssel geben, Eier und die Hälfte der Milch zugeben und mit dem Schneebesen glatt rühren.",
      "Restliche Milch unterrühren, bis ein dünnflüssiger Teig entsteht, und 15 Minuten quellen lassen.",
      "Eine Pfanne bei mittlerer bis starker Hitze erwärmen und etwas Butterschmalz darin zerlassen.",
      "Eine kleine Kelle Teig hineingeben, die Pfanne schwenken, bis der Boden dünn bedeckt ist, und 2 Minuten backen, bis die Unterseite goldbraun ist.",
      "Pfannkuchen wenden, weitere 1 bis 2 Minuten backen und im Ofen bei 80 °C warm halten, bis der Teig verbraucht ist.",
      "Mit Zimt und Zucker bestreut oder mit Apfelmus gefüllt aufrollen und servieren.",
    ],
    description: "Dünne süße Pfannkuchen aus Eierteig, je nach Region auch Eierkuchen oder Palatschinken genannt, mit Zimtzucker oder Apfelmus.",
    source: "klassiker",
  },
  {
    name: "Kartoffelbrei mit Würstchen",
    category: "Kinderessen",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 35,
    ingredients: [
      "1.2 kg Kartoffeln, mehligkochend",
      "250 ml Milch",
      "60 g Butter",
      "Salz",
      "Muskat",
      "8 Wiener Würstchen",
      "1 Glas Gewürzgurken",
      "Senf",
      "Ketchup",
    ],
    steps: [
      "Kartoffeln schälen, in gleich große Stücke schneiden und in Salzwasser 20 Minuten weich kochen.",
      "Milch mit Butter in einem kleinen Topf erwärmen, nicht kochen.",
      "Würstchen in einem Topf mit heißem Wasser 8 Minuten bei kleiner Hitze ziehen lassen, das Wasser darf nicht kochen, sonst platzen sie.",
      "Kartoffeln abgießen, kurz ausdampfen lassen und mit dem Kartoffelstampfer zerdrücken.",
      "Heiße Milch-Butter-Mischung nach und nach unterrühren, bis der Brei cremig ist, und mit Salz und Muskat würzen.",
      "Kartoffelbrei mit Würstchen, Gewürzgurken, Senf und Ketchup servieren.",
    ],
    description: "Einfaches Alltagsessen, das fast jedes Kind mag: cremiger Kartoffelbrei mit heißen Wiener Würstchen und Gurke.",
    source: "klassiker",
  },
  {
    name: "Spaghetti mit Butter und Parmesan",
    category: "Kinderessen",
    cuisine: "Italienisch",
    origin: "Italien",
    veg: true,
    servings: 4,
    minutes: 20,
    ingredients: [
      "500 g Spaghetti",
      "80 g Butter",
      "120 g Parmesan, frisch gerieben",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Reichlich Wasser mit Salz in einem großen Topf zum Kochen bringen.",
      "Spaghetti nach Packungsangabe bissfest kochen und kurz vor dem Abgießen 1 Tasse Nudelwasser abschöpfen.",
      "Butter in Würfeln in eine große vorgewärmte Schüssel geben.",
      "Abgetropfte Spaghetti heiß auf die Butter geben, Parmesan darüberstreuen und mit 2 bis 3 EL Nudelwasser so lange schwenken, bis eine cremige Soße entsteht.",
      "Mit Pfeffer und wenig Salz abschmecken und sofort servieren.",
    ],
    description: "In Italien Pasta al burro e parmigiano: Nudeln, Butter und Parmesan werden mit etwas Kochwasser zu einer cremigen Soße geschwenkt.",
    source: "klassiker",
  },
  {
    name: "Pizzabrötchen",
    category: "Kinderessen",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: false,
    servings: 4,
    minutes: 25,
    ingredients: [
      "6 Brötchen",
      "200 g Schinkenwürfel",
      "200 g Gouda, gerieben",
      "150 g Schmand",
      "1 rote Paprika",
      "1 Zwiebel, klein",
      "1 TL Oregano, getrocknet",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Backofen auf 200 °C Ober- und Unterhitze vorheizen und ein Blech mit Backpapier auslegen.",
      "Paprika und Zwiebel in sehr kleine Würfel schneiden.",
      "Schmand mit Schinken, Käse, Paprika, Zwiebel und Oregano verrühren und mit Salz und Pfeffer würzen.",
      "Brötchen halbieren, die Schnittflächen mit der Masse dick bestreichen und auf das Blech legen.",
      "Im Ofen 12 bis 15 Minuten backen, bis der Käse geschmolzen und leicht gebräunt ist, kurz abkühlen lassen und servieren.",
    ],
    description: "Halbierte Brötchen mit einer Masse aus Schinken, Käse und Schmand überbacken; der Partyklassiker, den Kinder auch zum Abendessen mögen.",
    source: "klassiker",
  },
  {
    name: "Gemüsereis",
    category: "Kinderessen",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 35,
    ingredients: [
      "400 g Langkornreis",
      "2 Möhren",
      "1 rote Paprika",
      "200 g Tiefkühlerbsen",
      "1 Dose Mais",
      "1 Zwiebel",
      "3 EL Rapsöl",
      "200 ml Gemüsebrühe",
      "1 TL edelsüßes Paprikapulver",
      "Salz",
      "Pfeffer",
      "100 g Gouda, gerieben",
    ],
    steps: [
      "Reis nach Packungsangabe in Salzwasser etwa 15 Minuten garen und abgießen.",
      "Zwiebel fein würfeln, Möhren schälen und klein würfeln, Paprika in kleine Stücke schneiden.",
      "Öl in einer großen Pfanne bei mittlerer Hitze erhitzen, Zwiebel und Möhren 5 Minuten anbraten.",
      "Paprika, Erbsen und Mais zugeben, mit Paprikapulver bestäuben und mit Brühe ablöschen, 5 Minuten köcheln lassen, bis das Gemüse gar ist.",
      "Reis unterheben, alles 3 Minuten durchschwenken und mit Salz und wenig Pfeffer abschmecken.",
      "Mit Käse bestreut servieren.",
    ],
    description: "Bunter Reis mit Möhren, Erbsen, Mais und Paprika, mild gewürzt und mit Käse bestreut, für Kinder geeignet; ein Standard der Familienküche.",
    source: "klassiker",
  },

  // ---------------------------------------------------------------- Schnelle Küche
  {
    name: "Pasta mit Tomaten und Mozzarella",
    category: "Schnelle Küche",
    cuisine: "Schnell",
    origin: "Italien",
    veg: true,
    servings: 4,
    minutes: 20,
    ingredients: [
      "500 g Penne",
      "500 g Kirschtomaten",
      "2 Zehen Knoblauch",
      "4 EL Olivenöl",
      "250 g Mozzarella",
      "1 Bund Basilikum",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Penne in reichlich Salzwasser nach Packungsangabe bissfest kochen.",
      "Kirschtomaten halbieren, Knoblauch in dünne Scheiben schneiden, Mozzarella würfeln und Basilikum in Streifen schneiden.",
      "Olivenöl in einer großen Pfanne bei mittlerer Hitze erwärmen und den Knoblauch 1 Minute anschwitzen.",
      "Tomaten zugeben und 5 Minuten schmoren, bis sie weich werden und Saft ziehen, mit Salz und Pfeffer würzen.",
      "Abgegossene Pasta und Mozzarella in die Pfanne geben, kurz schwenken, bis der Käse zu schmelzen beginnt, und mit Basilikum servieren.",
    ],
    description: "Schnelle Pasta mit geschmorten Kirschtomaten, schmelzendem Mozzarella und Basilikum, in 20 Minuten auf dem Tisch.",
    source: "klassiker",
  },
  {
    name: "Thunfisch-Pasta",
    category: "Schnelle Küche",
    cuisine: "Schnell",
    origin: "Italien",
    veg: false,
    servings: 4,
    minutes: 20,
    ingredients: [
      "500 g Spaghetti",
      "2 Dosen Thunfisch",
      "1 Dose Tomaten, stückig",
      "1 Zwiebel",
      "2 Zehen Knoblauch",
      "3 EL Olivenöl",
      "2 EL Kapern",
      "1 Bund Petersilie",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Spaghetti in reichlich Salzwasser nach Packungsangabe bissfest kochen.",
      "Zwiebel und Knoblauch fein würfeln und in Olivenöl bei mittlerer Hitze 3 Minuten glasig dünsten.",
      "Tomaten zugeben und 8 Minuten einkochen lassen, bis die Soße sämig ist.",
      "Thunfisch abtropfen lassen, mit den Kapern in die Soße geben und 2 Minuten erwärmen, mit Salz und Pfeffer abschmecken.",
      "Spaghetti abgießen, mit der Soße mischen und mit gehackter Petersilie bestreuen.",
    ],
    description: "Pasta al tonno, ein italienisches Vorratsgericht aus Dosentomaten, Thunfisch und Kapern.",
    source: "klassiker",
  },
  {
    name: "Flammkuchen",
    category: "Schnelle Küche",
    cuisine: "Schnell",
    origin: "Elsass",
    veg: false,
    servings: 4,
    minutes: 25,
    ingredients: [
      "2 Päckchen Flammkuchenteig aus dem Kühlregal",
      "300 g Schmand",
      "200 g Speckwürfel",
      "2 Zwiebeln",
      "Salz",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Backofen auf 250 °C Ober- und Unterhitze vorheizen, zwei Bleche mit Backpapier bereitlegen.",
      "Zwiebeln in sehr feine Ringe schneiden, Schmand mit Salz, Pfeffer und Muskat verrühren.",
      "Teig ausrollen, auf die Bleche legen und dünn mit Schmand bestreichen, dabei einen schmalen Rand frei lassen.",
      "Zwiebelringe und Speck gleichmäßig darauf verteilen.",
      "Nacheinander auf der untersten Schiene 10 bis 12 Minuten backen, bis der Rand knusprig und braun ist, heiß in Stücke schneiden.",
    ],
    description: "Der elsässische Tarte flambée mit Schmand, Zwiebeln und Speck, hier mit fertigem Teig als schnelles Abendessen.",
    source: "klassiker",
  },
  {
    name: "Gemüse-Omelett",
    category: "Schnelle Küche",
    cuisine: "Schnell",
    origin: "International",
    veg: true,
    servings: 4,
    minutes: 25,
    ingredients: [
      "8 Eier",
      "4 EL Milch",
      "1 rote Paprika",
      "1 Zucchini",
      "150 g Champignons",
      "4 Frühlingszwiebeln",
      "3 EL Olivenöl",
      "100 g Käse, gerieben",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Paprika, Zucchini und Champignons in kleine Stücke schneiden, Frühlingszwiebeln in Ringe schneiden.",
      "Olivenöl in einer großen beschichteten Pfanne bei mittlerer bis starker Hitze erhitzen und das Gemüse 5 bis 6 Minuten anbraten, salzen und pfeffern.",
      "Eier mit Milch, Salz und Pfeffer verquirlen und über das Gemüse gießen, Hitze auf mittel reduzieren.",
      "Stockende Masse am Rand mehrmals zur Mitte schieben, dann 5 Minuten zugedeckt stocken lassen.",
      "Käse darüberstreuen, Deckel wieder auflegen und 2 Minuten schmelzen lassen, das Omelett in Vierteln mit Brot servieren.",
    ],
    description: "Großes Pfannen-Omelett mit Paprika, Zucchini und Champignons, schnell gemacht und ein guter Rest-Verwerter.",
    source: "klassiker",
  },
  {
    name: "Quesadillas",
    category: "Schnelle Küche",
    cuisine: "Schnell",
    origin: "Mexiko",
    veg: true,
    servings: 4,
    minutes: 25,
    ingredients: [
      "8 Weizentortillas",
      "300 g Käse, gerieben",
      "1 Dose Kidneybohnen",
      "1 Dose Mais",
      "1 rote Paprika",
      "4 Frühlingszwiebeln",
      "1 TL Kreuzkümmel, gemahlen",
      "2 EL Rapsöl",
      "Salz",
      "200 g Salsa",
      "150 g saure Sahne",
    ],
    steps: [
      "Bohnen und Mais abspülen und abtropfen lassen, Paprika klein würfeln, Frühlingszwiebeln in Ringe schneiden.",
      "Bohnen, Mais, Paprika und Frühlingszwiebeln mit Kreuzkümmel und etwas Salz mischen.",
      "Je eine Tortilla mit einem Achtel des Käses und einem Viertel der Füllung belegen, mit einem weiteren Achtel Käse abschließen und eine zweite Tortilla darauflegen.",
      "Etwas Öl in einer großen Pfanne bei mittlerer Hitze erwärmen und die Quesadilla 3 Minuten je Seite braten, bis sie goldbraun und der Käse geschmolzen ist.",
      "Die übrigen drei Quesadillas genauso braten, in Viertel schneiden und mit Salsa und saurer Sahne servieren.",
    ],
    description: "Mexikanische Käsetortillas, hier mit Bohnen, Mais und Paprika gefüllt und in der Pfanne knusprig gebraten.",
    source: "klassiker",
  },
  {
    name: "Caesar Salad mit Hähnchen",
    category: "Schnelle Küche",
    cuisine: "International",
    origin: "USA",
    veg: false,
    servings: 4,
    minutes: 30,
    ingredients: [
      "2 Römersalate",
      "600 g Hähnchenbrustfilet",
      "3 EL Olivenöl",
      "4 Scheiben Toastbrot",
      "80 g Parmesan",
      "1 Eigelb",
      "1 TL Dijonsenf",
      "1 Zehe Knoblauch",
      "4 Sardellenfilets",
      "1 Zitrone",
      "1 TL Worcestersauce",
      "120 ml Rapsöl",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Toastbrot würfeln, in 1 EL Olivenöl bei mittlerer Hitze 5 Minuten goldbraun rösten und beiseitestellen.",
      "Hähnchenbrust salzen und pfeffern und in 2 EL Olivenöl bei mittlerer bis starker Hitze 5 bis 6 Minuten je Seite braten, dann 5 Minuten ruhen lassen und in Streifen schneiden.",
      "Für das Dressing Sardellen und Knoblauch fein hacken, mit Eigelb, Senf, Zitronensaft und Worcestersauce verrühren und das Rapsöl langsam unterschlagen, bis die Soße cremig ist.",
      "Die Hälfte des Parmesans fein reiben und unter das Dressing rühren, mit Salz und Pfeffer abschmecken.",
      "Römersalat waschen, in Stücke zupfen und mit dem Dressing vermengen.",
      "Hähnchenstreifen und Croûtons darauf verteilen und mit gehobeltem Parmesan bestreuen.",
    ],
    description: "Der in den 1920er Jahren in Tijuana von Caesar Cardini erfundene Salat aus Römersalat, Croûtons und Parmesan-Dressing, als Hauptgericht mit gebratenem Hähnchen.",
    source: "klassiker",
  },

  // ---------------------------------------------------------------- Hauptgericht modern
  {
    name: "Ofengemüse mit Feta",
    category: "Hauptgericht",
    cuisine: "Vegetarisch",
    origin: "Mediterran",
    veg: true,
    servings: 4,
    minutes: 50,
    ingredients: [
      "800 g Kartoffeln, festkochend",
      "2 Zucchini",
      "2 rote Paprika",
      "2 rote Zwiebeln",
      "300 g Kirschtomaten",
      "6 EL Olivenöl",
      "2 Rosmarinzweige",
      "1 TL Thymian, getrocknet",
      "2 Zehen Knoblauch",
      "400 g Feta",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Backofen auf 220 °C Ober- und Unterhitze vorheizen.",
      "Kartoffeln waschen und in Spalten schneiden, Zucchini und Paprika in grobe Stücke, Zwiebeln in Spalten schneiden, Knoblauch andrücken.",
      "Kartoffeln mit 3 EL Öl, Rosmarin, Salz und Pfeffer auf einem tiefen Blech mischen und 20 Minuten vorbacken.",
      "Restliches Gemüse, Knoblauch und Thymian mit dem übrigen Öl mischen, zu den Kartoffeln geben und weitere 20 Minuten backen.",
      "Feta in dicke Scheiben oder Würfel schneiden, auf das Gemüse legen und 5 bis 8 Minuten mitbacken, bis er weich ist und leicht bräunt.",
      "Mit Pfeffer übermahlen und direkt vom Blech servieren.",
    ],
    description: "Mediterranes Blechgericht aus im Ofen gerösteten Kartoffeln, Paprika, Zucchini und Zwiebeln mit überbackenem Feta; ein moderner Standard der vegetarischen Küche.",
    source: "klassiker",
  },
  {
    name: "Chili con Carne",
    category: "Hauptgericht",
    cuisine: "International",
    origin: "Texas",
    veg: false,
    servings: 4,
    minutes: 60,
    ingredients: [
      "800 g Rinderhackfleisch",
      "2 Zwiebeln",
      "3 Zehen Knoblauch",
      "2 rote Paprika",
      "3 EL Rapsöl",
      "2 EL Tomatenmark",
      "2 Dosen Tomaten, stückig",
      "2 Dosen Kidneybohnen",
      "1 Dose Mais",
      "2 TL Kreuzkümmel, gemahlen",
      "2 TL edelsüßes Paprikapulver",
      "1 TL Chiliflocken",
      "1 TL Oregano, getrocknet",
      "Salz",
      "Pfeffer",
      "150 g saure Sahne",
    ],
    steps: [
      "Zwiebeln, Knoblauch und Paprika würfeln.",
      "Öl in einem großen Topf stark erhitzen und das Hackfleisch portionsweise krümelig anbraten, bis es braun ist.",
      "Zwiebeln, Knoblauch und Paprika zugeben und 5 Minuten mitbraten, dann Tomatenmark und die Gewürze einrühren und 1 Minute rösten.",
      "Tomaten zugeben, salzen und pfeffern und das Chili zugedeckt bei kleiner Hitze 30 Minuten köcheln lassen.",
      "Bohnen und Mais abspülen, unterrühren und weitere 10 Minuten offen köcheln, bis die Soße sämig ist.",
      "Abschmecken und mit einem Klecks saurer Sahne, Brot oder Reis servieren.",
    ],
    description: "Der texanisch-mexikanische Eintopf aus Hackfleisch, Tomaten, Bohnen und Chili, in der heutigen Form mit Kidneybohnen und Mais ein Standard der Alltagsküche.",
    source: "klassiker",
  },
  {
    name: "Chili sin Carne",
    category: "Hauptgericht",
    cuisine: "Vegetarisch",
    origin: "International",
    veg: true,
    servings: 4,
    minutes: 45,
    ingredients: [
      "2 Zwiebeln",
      "3 Zehen Knoblauch",
      "2 rote Paprika",
      "2 Möhren",
      "3 EL Olivenöl",
      "2 EL Tomatenmark",
      "2 Dosen Tomaten, stückig",
      "2 Dosen Kidneybohnen",
      "1 Dose Mais",
      "150 g rote Linsen",
      "400 ml Gemüsebrühe",
      "2 TL Kreuzkümmel, gemahlen",
      "2 TL geräuchertes Paprikapulver",
      "1 TL Chiliflocken",
      "Salz",
      "Pfeffer",
      "1 Bund Koriander",
    ],
    steps: [
      "Zwiebeln und Knoblauch fein würfeln, Paprika und Möhren klein schneiden.",
      "Öl in einem großen Topf bei mittlerer Hitze erhitzen und Zwiebeln, Knoblauch, Möhren und Paprika 6 Minuten anbraten.",
      "Tomatenmark und Gewürze zugeben und 1 Minute unter Rühren rösten.",
      "Tomaten, Linsen und Brühe zugeben, salzen und 20 Minuten bei kleiner Hitze köcheln, bis die Linsen weich sind.",
      "Bohnen und Mais abspülen, unterrühren und weitere 10 Minuten köcheln lassen.",
      "Mit Salz und Pfeffer abschmecken und mit gehacktem Koriander, Reis oder Brot servieren.",
    ],
    description: "Die vegetarische Variante des Chili mit Kidneybohnen, Mais und roten Linsen anstelle von Hackfleisch.",
    source: "klassiker",
  },
  {
    name: "Burger",
    category: "Hauptgericht",
    cuisine: "International",
    origin: "USA",
    veg: false,
    servings: 4,
    minutes: 35,
    ingredients: [
      "700 g Rinderhackfleisch",
      "4 Burgerbrötchen",
      "4 Scheiben Cheddar",
      "2 Tomaten",
      "1 rote Zwiebel",
      "4 Salatblätter",
      "8 Scheiben Gewürzgurke",
      "4 EL Mayonnaise",
      "4 EL Ketchup",
      "2 TL Senf",
      "2 EL Rapsöl",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Hackfleisch ohne weitere Zutaten in 4 gleich große Portionen teilen, locker zu flachen Patties formen, die etwas größer als die Brötchen sind, und in die Mitte eine kleine Mulde drücken.",
      "Tomaten und Zwiebel in Scheiben schneiden, Salat waschen, Mayonnaise, Ketchup und Senf zu einer Soße verrühren.",
      "Öl in einer schweren Pfanne stark erhitzen, Patties erst jetzt kräftig salzen und pfeffern und 3 bis 4 Minuten je Seite braten.",
      "In der letzten Minute je eine Scheibe Cheddar auflegen und mit einem Deckel schmelzen lassen.",
      "Brötchen halbieren und mit der Schnittfläche nach unten 1 Minute in der Pfanne oder im Toaster rösten.",
      "Untere Hälften mit Soße bestreichen, mit Salat, Patty, Tomate, Zwiebel und Gurke belegen und mit der oberen Hälfte abschließen.",
    ],
    description: "Der amerikanische Hamburger mit selbst geformten Rinderpatties, Cheddar und klassischem Belag im gerösteten Brötchen.",
    source: "klassiker",
  },
  {
    name: "Tacos mit Hackfleisch",
    category: "Hauptgericht",
    cuisine: "International",
    origin: "Mexiko",
    veg: false,
    servings: 4,
    minutes: 35,
    ingredients: [
      "600 g Rinderhackfleisch",
      "12 Taco-Schalen",
      "1 Zwiebel",
      "2 Zehen Knoblauch",
      "2 EL Rapsöl",
      "1 EL Tomatenmark",
      "2 TL Kreuzkümmel, gemahlen",
      "2 TL edelsüßes Paprikapulver",
      "1 TL Oregano, getrocknet",
      "0.5 TL Chilipulver",
      "150 ml Wasser",
      "200 g Cheddar, gerieben",
      "0.5 Eisbergsalat",
      "3 Tomaten",
      "150 g saure Sahne",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Zwiebel und Knoblauch fein würfeln, Tomaten würfeln, Salat in feine Streifen schneiden.",
      "Öl in einer Pfanne stark erhitzen und das Hackfleisch 5 Minuten krümelig anbraten.",
      "Zwiebel und Knoblauch zugeben, 3 Minuten mitbraten, dann Tomatenmark und die Gewürze einrühren.",
      "Mit Wasser ablöschen und 10 Minuten bei mittlerer Hitze köcheln, bis die Flüssigkeit fast verkocht ist, mit Salz und Pfeffer abschmecken.",
      "Taco-Schalen nach Packungsangabe im Ofen bei 180 °C 5 Minuten erwärmen.",
      "Schalen mit Hackfleisch füllen und Salat, Tomaten, Käse und saure Sahne zum Selbstbelegen dazustellen.",
    ],
    description: "Knusprige Taco-Schalen mit gewürztem Hackfleisch, Salat, Tomaten und Käse, in der Tex-Mex-Küche fester Standard.",
    source: "klassiker",
  },
  {
    name: "Bowl mit Hähnchen, Quinoa und Gemüse",
    category: "Hauptgericht",
    cuisine: "International",
    origin: "International",
    veg: false,
    servings: 4,
    minutes: 40,
    ingredients: [
      "600 g Hähnchenbrustfilet",
      "300 g Quinoa",
      "600 ml Gemüsebrühe",
      "2 Süßkartoffeln",
      "1 Brokkoli",
      "2 Avocados",
      "200 g Kirschtomaten",
      "5 EL Olivenöl",
      "1 TL edelsüßes Paprikapulver",
      "1 Zitrone",
      "150 g Naturjoghurt",
      "1 Zehe Knoblauch",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Backofen auf 200 °C vorheizen, Süßkartoffeln schälen, würfeln, mit 2 EL Öl, Salz und Pfeffer mischen und 25 Minuten im Ofen rösten.",
      "Quinoa in einem Sieb heiß abspülen, mit der Brühe aufkochen und zugedeckt bei kleiner Hitze 15 Minuten garen, dann 5 Minuten quellen lassen.",
      "Brokkoli in Röschen teilen und in Salzwasser 4 Minuten bissfest kochen, abgießen und kalt abschrecken.",
      "Hähnchenbrust in Streifen schneiden, mit Paprikapulver, Salz und Pfeffer würzen und in 2 EL Öl bei starker Hitze 6 bis 8 Minuten rundum braten.",
      "Joghurt mit gepresstem Knoblauch, 1 EL Zitronensaft, restlichem Öl, Salz und Pfeffer zu einem Dressing verrühren.",
      "Quinoa auf 4 Schalen verteilen, Hähnchen, Süßkartoffeln, Brokkoli, halbierte Tomaten und Avocadospalten nebeneinander anrichten und mit dem Dressing beträufeln.",
    ],
    description: "Die moderne Schüsselmahlzeit mit Quinoa als Basis, gebratenem Hähnchen, Ofensüßkartoffeln, Brokkoli und Avocado, abgerundet mit Joghurtdressing.",
    source: "klassiker",
  },

  // ---------------------------------------------------------------- Beilagen & Salate
  {
    name: "Kartoffelpüree",
    category: "Beilagen & Salate",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 30,
    ingredients: [
      "1 kg Kartoffeln, mehligkochend",
      "250 ml Milch",
      "60 g Butter",
      "Salz",
      "Muskat",
    ],
    steps: [
      "Kartoffeln schälen, in gleich große Stücke schneiden und in Salzwasser 20 Minuten weich kochen.",
      "Milch mit Butter in einem kleinen Topf erwärmen, aber nicht kochen lassen.",
      "Kartoffeln abgießen und im offenen Topf 1 Minute ausdampfen lassen.",
      "Kartoffeln mit dem Stampfer oder durch die Presse zerkleinern, keinen Mixer verwenden, sonst wird das Püree klebrig.",
      "Heiße Milch-Butter-Mischung nach und nach unterrühren, bis die gewünschte Konsistenz erreicht ist, und mit Salz und Muskat abschmecken.",
    ],
    description: "Die klassische Beilage aus mehligen Kartoffeln, heißer Milch und Butter, mit Muskat abgeschmeckt.",
    source: "klassiker",
  },
  {
    name: "Ofenkartoffeln",
    category: "Beilagen & Salate",
    cuisine: "Klassisch",
    origin: "International",
    veg: true,
    servings: 4,
    minutes: 45,
    ingredients: [
      "1.2 kg Kartoffeln, festkochend",
      "4 EL Olivenöl",
      "2 Rosmarinzweige",
      "1 TL edelsüßes Paprikapulver",
      "2 Zehen Knoblauch",
      "1 TL Salz, grob",
      "Pfeffer",
    ],
    steps: [
      "Backofen auf 220 °C Ober- und Unterhitze vorheizen und ein Blech mit Backpapier auslegen.",
      "Kartoffeln gründlich waschen, nicht schälen, und in gleich dicke Spalten schneiden.",
      "Rosmarinnadeln hacken, Knoblauch andrücken und beides mit Öl, Paprikapulver, Salz und Pfeffer in einer Schüssel mischen.",
      "Kartoffelspalten in der Marinade wenden und mit der Schnittfläche nach unten ohne Überlappung auf dem Blech verteilen.",
      "35 Minuten backen, nach 20 Minuten einmal wenden, bis die Spalten außen knusprig und innen weich sind.",
    ],
    description: "Knusprige Kartoffelspalten mit Schale, Rosmarin und Olivenöl aus dem Ofen; die unkomplizierte Beilage zu Fleisch, Fisch oder Dips.",
    source: "klassiker",
  },
  {
    name: "Grüner Salat mit Vinaigrette",
    category: "Beilagen & Salate",
    cuisine: "Klassisch",
    origin: "Frankreich",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "2 Kopfsalate",
      "1 Schalotte",
      "1 TL Dijonsenf",
      "2 EL Weißweinessig",
      "6 EL Olivenöl",
      "1 Prise Zucker",
      "Salz",
      "Pfeffer",
      "1 Bund Schnittlauch",
    ],
    steps: [
      "Salat in Blätter zerteilen, gründlich waschen und in der Salatschleuder trocken schleudern.",
      "Schalotte sehr fein würfeln und mit Senf, Essig, Zucker, Salz und Pfeffer in einer Schüssel verrühren.",
      "Olivenöl in dünnem Strahl unterschlagen, bis eine gebundene Vinaigrette entsteht.",
      "Schnittlauch in feine Röllchen schneiden und unter die Vinaigrette rühren.",
      "Salatblätter erst kurz vor dem Servieren mit der Vinaigrette mischen, damit sie knackig bleiben.",
    ],
    description: "Blattsalat mit der klassischen französischen Vinaigrette aus Senf, Essig und Öl im Verhältnis 1 zu 3.",
    source: "klassiker",
  },
  {
    name: "Gurkensalat mit Dill",
    category: "Beilagen & Salate",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "2 Salatgurken",
      "1 Bund Dill",
      "200 g saure Sahne",
      "2 EL Weißweinessig",
      "1 TL Zucker",
      "1 TL Salz",
      "Pfeffer",
    ],
    steps: [
      "Gurken waschen und mit dem Gurkenhobel oder Messer in sehr dünne Scheiben schneiden.",
      "Scheiben mit dem Salz mischen und 10 Minuten Wasser ziehen lassen, dann leicht ausdrücken.",
      "Dill fein hacken und mit saurer Sahne, Essig, Zucker und Pfeffer zu einem Dressing verrühren.",
      "Gurkenscheiben unter das Dressing heben, abschmecken und kühl servieren.",
    ],
    description: "Dünn gehobelte Gurke in einem Dressing aus saurer Sahne und frischem Dill; der klassische Sommersalat zu Kartoffeln und Fisch.",
    source: "klassiker",
  },
  {
    name: "Krautsalat",
    category: "Beilagen & Salate",
    cuisine: "Klassisch",
    origin: "Süddeutschland",
    veg: false,
    servings: 4,
    minutes: 25,
    ingredients: [
      "1 kg Weißkohl",
      "1 TL Kümmel",
      "1 TL Salz",
      "1 TL Zucker",
      "4 EL Weißweinessig",
      "4 EL Sonnenblumenöl",
      "100 g Speckwürfel",
      "Pfeffer",
    ],
    steps: [
      "Weißkohl vierteln, Strunk entfernen und den Kohl mit dem Hobel oder Messer in sehr feine Streifen schneiden.",
      "Kohl mit Salz, Zucker und Kümmel in einer Schüssel kräftig mit den Händen kneten, bis er weich wird und Saft zieht, etwa 3 Minuten.",
      "Speckwürfel in einer Pfanne bei mittlerer Hitze knusprig auslassen.",
      "Essig und Öl mit dem heißen Speck samt Fett über den Kohl geben und gut vermengen.",
      "Mit Pfeffer abschmecken und mindestens 30 Minuten durchziehen lassen, besser über Nacht.",
    ],
    description: "Süddeutscher Krautsalat aus fein gehobeltem Weißkohl, mit Kümmel geknetet und mit heißem Speck und Essig angemacht.",
    source: "klassiker",
  },

  // ---------------------------------------------------------------- Soßen & Dips
  {
    name: "Tomatensoße",
    category: "Soßen & Dips",
    cuisine: "Italienisch",
    origin: "Italien",
    veg: true,
    servings: 4,
    minutes: 35,
    ingredients: [
      "2 Dosen Tomaten, geschält",
      "1 Zwiebel",
      "2 Zehen Knoblauch",
      "4 EL Olivenöl",
      "1 TL Zucker",
      "1 Bund Basilikum",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Zwiebel und Knoblauch fein würfeln und in Olivenöl bei kleiner bis mittlerer Hitze 5 Minuten glasig dünsten, ohne Farbe zu nehmen.",
      "Tomaten mit Saft zugeben und mit dem Kochlöffel grob zerdrücken.",
      "Zucker, Salz und Pfeffer zugeben und die Soße bei kleiner Hitze 25 Minuten offen köcheln lassen, dabei gelegentlich umrühren.",
      "Basilikumblätter zerzupfen und unterrühren, Soße nach Wunsch glatt pürieren und abschmecken.",
    ],
    description: "Das Grundrezept der italienischen Küche: geschälte Dosentomaten mit Zwiebel, Knoblauch und Olivenöl langsam eingekocht, reicht für 500 g Pasta.",
    source: "klassiker",
  },
  {
    name: "Béchamelsoße",
    category: "Soßen & Dips",
    cuisine: "Klassisch",
    origin: "Frankreich",
    veg: true,
    servings: 4,
    minutes: 20,
    ingredients: [
      "50 g Butter",
      "50 g Mehl",
      "750 ml Milch",
      "Salz",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Butter in einem Topf bei mittlerer Hitze schmelzen, Mehl einrühren und 2 Minuten unter Rühren anschwitzen, ohne dass es braun wird.",
      "Kalte Milch nach und nach mit dem Schneebesen einrühren, damit keine Klümpchen entstehen.",
      "Soße unter Rühren aufkochen und bei kleiner Hitze 10 Minuten leise köcheln lassen, bis der Mehlgeschmack verschwunden ist und die Soße sämig ist.",
      "Mit Salz, Pfeffer und frisch geriebenem Muskat abschmecken.",
    ],
    description: "Eine der Grundsoßen der französischen Küche aus Mehlschwitze und Milch; Basis für Lasagne, Aufläufe und Käsesoßen.",
    source: "klassiker",
  },
  {
    name: "Tzatziki",
    category: "Soßen & Dips",
    cuisine: "Mediterran",
    origin: "Griechenland",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "500 g griechischer Joghurt",
      "1 Salatgurke",
      "2 Zehen Knoblauch",
      "2 EL Olivenöl",
      "1 EL Weißweinessig",
      "1 TL Salz",
      "Pfeffer",
      "1 Bund Dill",
    ],
    steps: [
      "Gurke schälen, grob reiben, mit dem Salz mischen und 10 Minuten ziehen lassen.",
      "Geriebene Gurke in einem sauberen Küchentuch kräftig ausdrücken, damit das Tzatziki nicht wässrig wird.",
      "Knoblauch pressen und mit Joghurt, Olivenöl und Essig verrühren.",
      "Gurke und gehackten Dill unterheben, mit Pfeffer und bei Bedarf Salz abschmecken und mindestens 30 Minuten kalt stellen.",
    ],
    description: "Der griechische Joghurtdip mit ausgedrückter Gurke und Knoblauch, zu Gegrilltem, Brot und Gemüse.",
    source: "klassiker",
  },
  {
    name: "Guacamole",
    category: "Soßen & Dips",
    cuisine: "International",
    origin: "Mexiko",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "3 Avocados, reif",
      "1 Limette",
      "1 rote Zwiebel, klein",
      "1 Tomate",
      "1 Zehe Knoblauch",
      "0.5 Bund Koriander",
      "1 Prise Kreuzkümmel, gemahlen",
      "Salz",
      "Chiliflocken",
    ],
    steps: [
      "Avocados halbieren, Kern entfernen, Fruchtfleisch mit dem Löffel herauslösen und sofort mit dem Limettensaft beträufeln.",
      "Zwiebel und Knoblauch sehr fein hacken, Tomate entkernen und klein würfeln, Koriander hacken.",
      "Avocado mit der Gabel grob zerdrücken, so dass noch Stücke bleiben.",
      "Zwiebel, Knoblauch, Tomate und Koriander unterheben und mit Salz, Kreuzkümmel und Chiliflocken abschmecken.",
      "Sofort servieren oder mit Frischhaltefolie direkt auf der Oberfläche abgedeckt kühl stellen.",
    ],
    description: "Der mexikanische Avocadodip mit Limette, Zwiebel und Koriander, zu Tortillachips, Tacos und Burgern.",
    source: "klassiker",
  },
  {
    name: "Kräuterquark",
    category: "Soßen & Dips",
    cuisine: "Klassisch",
    origin: "Deutschland",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "500 g Magerquark",
      "100 ml Milch",
      "1 Bund Schnittlauch",
      "1 Bund Petersilie",
      "0.5 Bund Dill",
      "1 Zehe Knoblauch",
      "2 EL Leinöl",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Quark mit Milch und Leinöl glatt rühren, bis er cremig ist.",
      "Kräuter waschen, trocken schütteln und fein hacken, Knoblauch pressen.",
      "Kräuter und Knoblauch unter den Quark rühren.",
      "Mit Salz und Pfeffer abschmecken und 15 Minuten durchziehen lassen.",
    ],
    description: "Frischer Quark mit Schnittlauch, Petersilie und Dill; klassisch zu Pellkartoffeln, Brot oder als Dip für Gemüse.",
    source: "klassiker",
  },

  // ---------------------------------------------------------------- Snacks
  {
    name: "Bruschetta",
    category: "Snacks",
    cuisine: "Italienisch",
    origin: "Mittelitalien",
    veg: true,
    servings: 4,
    minutes: 20,
    ingredients: [
      "1 Ciabatta",
      "500 g Tomaten",
      "2 Zehen Knoblauch",
      "5 EL Olivenöl",
      "1 Bund Basilikum",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Tomaten waschen, entkernen und in kleine Würfel schneiden, Basilikum in Streifen schneiden.",
      "Tomaten mit Basilikum, 3 EL Olivenöl, Salz und Pfeffer mischen und 10 Minuten ziehen lassen.",
      "Ciabatta in 2 cm dicke Scheiben schneiden und im Ofen unter dem Grill oder in der Pfanne von beiden Seiten goldbraun rösten.",
      "Knoblauchzehen halbieren und die heißen Brotscheiben mit der Schnittfläche abreiben, dann mit dem restlichen Öl beträufeln.",
      "Tomatenmischung auf den Scheiben verteilen und sofort servieren.",
    ],
    description: "Geröstetes, mit Knoblauch abgeriebenes Weißbrot mit Tomaten und Basilikum; der italienische Snack aus Mittelitalien.",
    source: "klassiker",
  },
  {
    name: "Gemüsesticks mit Dip",
    category: "Snacks",
    cuisine: "Vegetarisch",
    origin: "International",
    veg: true,
    servings: 4,
    minutes: 20,
    ingredients: [
      "4 Möhren",
      "1 Salatgurke",
      "2 Paprika",
      "4 Selleriestangen",
      "200 g Kirschtomaten",
      "300 g Naturjoghurt",
      "150 g Frischkäse",
      "1 Zehe Knoblauch",
      "1 Bund Schnittlauch",
      "1 TL Zitronensaft",
      "Salz",
      "Pfeffer",
    ],
    steps: [
      "Joghurt und Frischkäse glatt rühren, Knoblauch pressen, Schnittlauch fein schneiden und beides unterrühren.",
      "Dip mit Zitronensaft, Salz und Pfeffer abschmecken und kalt stellen.",
      "Möhren schälen, Paprika entkernen, Sellerie waschen und alles zusammen mit der Gurke in fingerlange Stifte schneiden.",
      "Gemüsesticks und Kirschtomaten auf einer Platte um die Dipschale herum anrichten.",
    ],
    description: "Rohes Gemüse in Stiften mit einem Joghurt-Frischkäse-Dip; der einfache Snack für Kinder, Gäste und den Fernsehabend.",
    source: "klassiker",
  },
  {
    name: "Bananenbrot",
    category: "Snacks",
    cuisine: "International",
    origin: "USA",
    veg: true,
    servings: 4,
    minutes: 70,
    ingredients: [
      "3 Bananen, reif",
      "100 g Butter",
      "120 g Zucker",
      "2 Eier",
      "250 g Mehl",
      "1 TL Natron",
      "1 Prise Salz",
      "1 TL Zimt",
      "80 g Walnüsse, gehackt",
    ],
    steps: [
      "Backofen auf 180 °C Ober- und Unterhitze vorheizen und eine Kastenform mit Backpapier auslegen.",
      "Bananen mit der Gabel zu Mus zerdrücken.",
      "Weiche Butter mit Zucker cremig rühren, Eier einzeln unterrühren und das Bananenmus zugeben.",
      "Mehl mit Natron, Salz und Zimt mischen, kurz unter die Masse rühren und die Walnüsse unterheben.",
      "Teig in die Form füllen und 55 Minuten backen, bis ein Holzstäbchen sauber herauskommt.",
      "10 Minuten in der Form abkühlen lassen, dann auf einem Gitter auskühlen und in Scheiben schneiden.",
    ],
    description: "Saftiger Rührkuchen aus überreifen Bananen und Walnüssen in der Kastenform, aus den USA, inzwischen Standard in jedem Café.",
    source: "klassiker",
  },
];
