// Klassiker-Basis: Naher Osten, Indien und Asien.
// Etablierte Gerichte aus Levante, Türkei, Indien, Thailand, Indonesien, China, Japan und Korea, Mengen für 4 Personen.
// Form siehe docs/ARCHITEKTUR.md, Abschnitt 3 "Recipe" (source "klassiker", origin Pflicht).

export default [
  // ---------- Naher Osten ----------
  {
    name: "Shakshuka",
    category: "Hauptgericht",
    cuisine: "Naher Osten",
    origin: "Nordafrika und Israel",
    veg: true,
    servings: 4,
    minutes: 35,
    ingredients: [
      "2 Zwiebeln",
      "2 rote Paprika",
      "3 Zehen Knoblauch",
      "3 EL Olivenöl",
      "2 TL Kreuzkümmel, gemahlen",
      "2 TL Paprikapulver, edelsüß",
      "0.5 TL Chiliflocken",
      "2 Dosen Tomaten, gehackt",
      "1 TL Zucker",
      "Salz",
      "Pfeffer",
      "8 Eier",
      "150 g Feta",
      "1 Bund Petersilie",
      "2 Fladenbrote",
    ],
    steps: [
      "Zwiebeln und Paprika in Streifen schneiden, Knoblauch fein hacken.",
      "Olivenöl in einer großen Pfanne erhitzen und Zwiebeln und Paprika bei mittlerer Hitze 8 Minuten weich dünsten, Knoblauch und Gewürze zugeben und 1 Minute mitrösten.",
      "Tomaten und Zucker zugeben, mit Salz und Pfeffer würzen und offen bei mittlerer Hitze 10 Minuten dicklich einkochen lassen.",
      "Mit dem Löffel acht Mulden in die Soße drücken, je ein Ei hineingleiten lassen und mit Salz bestreuen.",
      "Deckel auflegen und bei kleiner Hitze 6 bis 8 Minuten garen, bis das Eiweiß fest und das Eigelb noch weich ist.",
      "Feta darüberbröseln, mit gehackter Petersilie bestreuen und direkt aus der Pfanne mit Fladenbrot servieren.",
    ],
    description: "In Tomaten-Paprika-Soße pochierte Eier, ein Alltagsgericht aus Nordafrika, das über Israel bekannt wurde und dort zum Frühstück wie zum Abendessen auf den Tisch kommt.",
    source: "klassiker",
  },
  {
    name: "Falafel mit Tahinsoße",
    category: "Hauptgericht",
    cuisine: "Naher Osten",
    origin: "Levante",
    veg: true,
    servings: 4,
    minutes: 45,
    ingredients: [
      "400 g Kichererbsen, getrocknet",
      "1 Zwiebel",
      "4 Zehen Knoblauch",
      "1 Bund Petersilie",
      "1 Bund Koriander",
      "2 TL Kreuzkümmel, gemahlen",
      "1 TL Koriander, gemahlen",
      "1 TL Salz",
      "1 TL Backpulver",
      "2 EL Mehl",
      "1 l Pflanzenöl",
      "150 g Tahin",
      "2 Zitronen",
      "4 Fladenbrote",
      "4 Tomaten",
      "0.5 Salatgurke",
    ],
    steps: [
      "Kichererbsen am Vortag in reichlich kaltem Wasser 12 Stunden einweichen, dann abgießen und gut abtropfen lassen; sie werden roh verarbeitet, nicht gekocht.",
      "Kichererbsen mit Zwiebel, 3 Zehen Knoblauch, Petersilie, Koriandergrün, Gewürzen und Salz in der Küchenmaschine zu einer grobkörnigen Masse hacken, Backpulver und Mehl untermischen und 15 Minuten kalt stellen.",
      "Für die Soße Tahin mit dem Saft von 1.5 Zitronen, der restlichen gepressten Knoblauchzehe, 1 TL Salz und etwa 100 ml kaltem Wasser glatt rühren, bis eine cremige, hellbeige Soße entsteht.",
      "Öl in einem Topf auf 175 °C erhitzen; aus der Masse mit feuchten Händen walnussgroße Bällchen formen und fest zusammendrücken.",
      "Falafel portionsweise 4 bis 5 Minuten goldbraun frittieren, mit der Schaumkelle herausheben und auf Küchenpapier abtropfen lassen.",
      "Tomaten und Gurke würfeln, Fladenbrot kurz erwärmen und mit Falafel, Gemüse und Tahinsoße füllen, restliche Zitrone in Spalten dazu reichen.",
    ],
    description: "Frittierte Kichererbsenbällchen mit Sesamsoße, das bekannteste Straßenessen der Levante. Die Masse wird aus rohen Kichererbsen gemacht, die über Nacht 12 Stunden einweichen müssen.",
    source: "klassiker",
  },
  {
    name: "Hummus",
    category: "Soßen & Dips",
    cuisine: "Naher Osten",
    origin: "Levante",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "2 Dosen Kichererbsen",
      "5 EL Tahin",
      "2 Zitronen",
      "2 Zehen Knoblauch",
      "1 TL Kreuzkümmel, gemahlen",
      "1 TL Salz",
      "100 ml Wasser",
      "4 EL Olivenöl",
      "1 TL Paprikapulver, edelsüß",
      "4 Fladenbrote",
    ],
    steps: [
      "Kichererbsen in ein Sieb gießen, kalt abspülen und gut abtropfen lassen, 2 EL für die Garnitur beiseitelegen.",
      "Tahin mit dem Saft beider Zitronen im Mixer 1 Minute cremig aufschlagen, dadurch wird der Hummus besonders luftig.",
      "Kichererbsen, geschälten Knoblauch, Kreuzkümmel und Salz zugeben und 2 bis 3 Minuten sehr fein pürieren.",
      "Nach und nach das kalte Wasser einlaufen lassen, bis eine glatte, streichfähige Creme entsteht, und mit Salz und Zitrone abschmecken.",
      "Hummus auf einem flachen Teller verstreichen, mit dem Löffelrücken eine Mulde ziehen, mit Olivenöl begießen, mit Paprikapulver und den zurückbehaltenen Kichererbsen garnieren und mit warmem Fladenbrot servieren.",
    ],
    description: "Die cremige Kichererbsen-Sesam-Paste der Levante, dort Grundbestandteil jeder Mezze-Tafel und Beilage zu Falafel und Fladenbrot.",
    source: "klassiker",
  },
  {
    name: "Tabouleh",
    category: "Beilagen & Salate",
    cuisine: "Naher Osten",
    origin: "Libanon",
    veg: true,
    servings: 4,
    minutes: 30,
    ingredients: [
      "80 g Bulgur, fein",
      "4 Bund Petersilie",
      "1 Bund Minze",
      "4 Tomaten",
      "4 Frühlingszwiebeln",
      "2 Zitronen",
      "6 EL Olivenöl",
      "1 TL Salz",
      "Pfeffer",
      "0.5 TL Piment, gemahlen",
    ],
    steps: [
      "Bulgur in eine Schüssel geben, mit 100 ml kochendem Wasser übergießen und zugedeckt 15 Minuten quellen lassen.",
      "Petersilie und Minze waschen, trocken schleudern, dicke Stiele entfernen und die Blätter mit einem scharfen Messer sehr fein schneiden, nicht hacken, damit sie nicht matschig werden.",
      "Tomaten entkernen und in kleine Würfel schneiden, Frühlingszwiebeln in feine Ringe schneiden.",
      "Zitronensaft mit Olivenöl, Salz, Pfeffer und Piment zu einem Dressing verrühren.",
      "Bulgur mit der Gabel auflockern, mit Kräutern, Tomaten und Frühlingszwiebeln mischen, Dressing unterheben und vor dem Servieren 10 Minuten durchziehen lassen.",
    ],
    description: "Der libanesische Petersiliensalat mit wenig Bulgur, viel Zitrone und Minze; im Original dominiert das Kraut, nicht das Getreide.",
    source: "klassiker",
  },
  {
    name: "Köfte",
    category: "Hauptgericht",
    cuisine: "Naher Osten",
    origin: "Türkei",
    veg: false,
    servings: 4,
    minutes: 40,
    ingredients: [
      "800 g Rinderhackfleisch",
      "1 Zwiebel",
      "2 Zehen Knoblauch",
      "2 Scheiben Weißbrot",
      "1 Ei",
      "1 Bund Petersilie",
      "2 TL Kreuzkümmel, gemahlen",
      "1 TL Paprikapulver, edelsüß",
      "1 TL Pul Biber",
      "1.5 TL Salz",
      "Pfeffer",
      "3 EL Olivenöl",
      "500 g Joghurt",
      "4 Fladenbrote",
      "4 Tomaten",
      "2 rote Zwiebeln",
    ],
    steps: [
      "Altbackenes Weißbrot in Wasser einweichen und fest ausdrücken; Zwiebel und Knoblauch sehr fein reiben, Petersilie fein hacken.",
      "Hackfleisch mit Brot, Ei, Zwiebel, Knoblauch, Petersilie, Gewürzen, Salz und Pfeffer mindestens 5 Minuten kräftig kneten, bis die Masse bindet, und 15 Minuten kalt stellen.",
      "Aus der Masse mit feuchten Händen 16 längliche, leicht flache Röllchen formen.",
      "Olivenöl in einer großen Pfanne erhitzen und die Köfte bei mittlerer bis starker Hitze 4 Minuten pro Seite braten, bis sie außen dunkelbraun und innen gar sind.",
      "Tomaten in Scheiben, rote Zwiebeln in Ringe schneiden und mit etwas Salz mischen; Joghurt mit einer Prise Salz glatt rühren.",
      "Köfte mit Tomaten, Zwiebeln, Joghurt und warmem Fladenbrot anrichten.",
    ],
    description: "Türkische Hackfleischröllchen mit Kreuzkümmel und Petersilie, gebraten oder gegrillt, in der Türkei das Standardgericht jeder Imbiss- und Hausküche.",
    source: "klassiker",
  },
  {
    name: "Türkische Linsensuppe",
    category: "Hauptgericht",
    cuisine: "Naher Osten",
    origin: "Türkei",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "300 g rote Linsen",
      "1 Zwiebel",
      "1 Möhre",
      "1 Kartoffel",
      "2 Zehen Knoblauch",
      "2 EL Olivenöl",
      "1 EL Tomatenmark",
      "1 TL Kreuzkümmel, gemahlen",
      "1 TL Paprikapulver, edelsüß",
      "1.5 l Gemüsebrühe",
      "Salz",
      "Pfeffer",
      "2 EL Butter",
      "1 TL Pul Biber",
      "1 TL Minze, getrocknet",
      "2 Zitronen",
    ],
    steps: [
      "Linsen in einem Sieb kalt abspülen; Zwiebel, Möhre, Kartoffel und Knoblauch schälen und grob würfeln.",
      "Gemüse in Olivenöl bei mittlerer Hitze 5 Minuten anschwitzen, Tomatenmark, Kreuzkümmel und Paprikapulver zugeben und 1 Minute mitrösten.",
      "Linsen und Brühe zugeben, aufkochen und zugedeckt bei kleiner Hitze 20 Minuten köcheln, bis Linsen und Gemüse zerfallen.",
      "Suppe mit dem Stabmixer fein pürieren, mit Salz und Pfeffer abschmecken und bei Bedarf mit etwas Wasser verdünnen.",
      "Butter in einem kleinen Topf schmelzen, Pul Biber und Minze einrühren und sofort vom Herd nehmen.",
      "Suppe in Schalen füllen, mit der Gewürzbutter beträufeln und mit Zitronenspalten servieren, der Saft wird erst am Tisch hineingepresst.",
    ],
    description: "Mercimek Çorbası, die pürierte rote Linsensuppe der Türkei, mit Minzbutter und Zitrone; sie steht in fast jeder türkischen Lokanta auf der Karte.",
    source: "klassiker",
  },

  // ---------- Indien ----------
  {
    name: "Dal Tadka",
    category: "Hauptgericht",
    cuisine: "Indisch",
    origin: "Nordindien",
    veg: true,
    servings: 4,
    minutes: 45,
    ingredients: [
      "400 g rote Linsen",
      "1.2 l Wasser",
      "1 TL Kurkuma",
      "1.5 TL Salz",
      "2 Tomaten",
      "3 EL Ghee",
      "1 TL Kreuzkümmelsamen",
      "1 TL Senfkörner",
      "2 Zwiebeln",
      "4 Zehen Knoblauch",
      "30 g Ingwer",
      "2 grüne Chilis",
      "1 TL Garam Masala",
      "0.5 TL Chilipulver",
      "1 Bund Koriander",
      "2 Zitronen",
      "400 g Basmatireis",
    ],
    steps: [
      "Linsen gründlich waschen, mit Wasser, Kurkuma und Salz aufkochen, Schaum abschöpfen und halb zugedeckt bei kleiner Hitze 20 Minuten weich kochen, dabei gelegentlich umrühren.",
      "Parallel den Basmatireis waschen und in der 1.5-fachen Menge Salzwasser zugedeckt 12 Minuten garen, dann 5 Minuten nachquellen lassen.",
      "Tomaten würfeln, in die Linsen rühren und weitere 5 Minuten köcheln, bis das Dal sämig ist.",
      "Für das Tadka Zwiebeln fein würfeln, Knoblauch, Ingwer und Chilis fein hacken.",
      "Ghee in einer kleinen Pfanne stark erhitzen, Kreuzkümmel- und Senfkörner zugeben und einige Sekunden springen lassen, dann Zwiebeln 5 Minuten goldbraun braten.",
      "Knoblauch, Ingwer, Chilis, Garam Masala und Chilipulver zugeben, 1 Minute rösten und das heiße Gewürzöl sofort über das Dal gießen.",
      "Dal mit Zitronensaft und Salz abschmecken, mit gehacktem Koriander bestreuen und mit Reis servieren.",
    ],
    description: "Weich gekochte Linsen, am Schluss mit in heißem Ghee gerösteten Gewürzen übergossen; dieses Tadka gibt dem nordindischen Alltagsgericht seinen Namen.",
    source: "klassiker",
  },
  {
    name: "Chana Masala",
    category: "Hauptgericht",
    cuisine: "Indisch",
    origin: "Punjab, Nordindien",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "3 Dosen Kichererbsen",
      "2 Zwiebeln",
      "4 Zehen Knoblauch",
      "30 g Ingwer",
      "2 grüne Chilis",
      "3 EL Pflanzenöl",
      "1 TL Kreuzkümmelsamen",
      "1 Dose Tomaten, gehackt",
      "2 TL Koriander, gemahlen",
      "1 TL Kreuzkümmel, gemahlen",
      "1 TL Kurkuma",
      "1 TL Chilipulver",
      "2 TL Garam Masala",
      "1 TL Amchur",
      "1.5 TL Salz",
      "1 Bund Koriander",
      "400 g Basmatireis",
    ],
    steps: [
      "Reis waschen und in der 1.5-fachen Menge Salzwasser zugedeckt 12 Minuten garen, dann 5 Minuten nachquellen lassen.",
      "Zwiebeln fein würfeln, Knoblauch, Ingwer und Chilis zu einer Paste reiben oder sehr fein hacken; Kichererbsen abgießen und abspülen.",
      "Öl in einem Topf erhitzen, Kreuzkümmelsamen 20 Sekunden rösten, Zwiebeln zugeben und bei mittlerer Hitze 8 Minuten goldbraun braten.",
      "Knoblauch-Ingwer-Chili-Paste zugeben und 2 Minuten rösten, dann Koriander, Kreuzkümmel, Kurkuma und Chilipulver einrühren und 30 Sekunden mitrösten.",
      "Tomaten und Salz zugeben und 8 Minuten einkochen, bis sich das Öl am Rand absetzt.",
      "Kichererbsen und 250 ml Wasser zugeben, 10 Minuten köcheln und einige Kichererbsen mit dem Löffel andrücken, damit die Soße bindet.",
      "Garam Masala und Amchur einrühren, mit Salz abschmecken, mit Koriander bestreuen und mit Reis servieren.",
    ],
    description: "Kichererbsen in würziger Tomaten-Zwiebel-Soße, ein Standardgericht aus dem Punjab, das mit Reis, Naan oder Bhatura gegessen wird.",
    source: "klassiker",
  },
  {
    name: "Butter Chicken",
    category: "Hauptgericht",
    cuisine: "Indisch",
    origin: "Delhi, Nordindien",
    veg: false,
    servings: 4,
    minutes: 70,
    ingredients: [
      "800 g Hähnchenschenkelfleisch ohne Knochen",
      "150 g Joghurt",
      "2 TL Garam Masala",
      "1 TL Kurkuma",
      "1 TL Chilipulver",
      "2 TL Kreuzkümmel, gemahlen",
      "6 Zehen Knoblauch",
      "40 g Ingwer",
      "2 Zitronen",
      "60 g Butter",
      "2 EL Pflanzenöl",
      "1 Zwiebel",
      "4 Kardamomkapseln",
      "2 Dosen Tomaten, gehackt",
      "1 EL Zucker",
      "1 TL Bockshornkleeblätter, getrocknet",
      "200 ml Sahne",
      "1.5 TL Salz",
      "400 g Basmatireis",
      "1 Bund Koriander",
    ],
    steps: [
      "Hähnchen in mundgerechte Stücke schneiden und mit Joghurt, 1 TL Garam Masala, Kurkuma, Chilipulver, 1 TL Kreuzkümmel, der Hälfte des geriebenen Knoblauchs und Ingwers, Saft von 1 Zitrone und 1 TL Salz mindestens 30 Minuten marinieren.",
      "Reis waschen und in der 1.5-fachen Menge Salzwasser zugedeckt 12 Minuten garen, dann 5 Minuten nachquellen lassen.",
      "Öl in einer großen Pfanne stark erhitzen, Hähnchen portionsweise 3 Minuten pro Seite scharf anbraten, bis es Röststellen hat, und herausnehmen.",
      "In derselben Pfanne 30 g Butter schmelzen, fein gewürfelte Zwiebel und Kardamom bei mittlerer Hitze 6 Minuten weich dünsten, restlichen Knoblauch und Ingwer sowie restlichen Kreuzkümmel 1 Minute mitrösten.",
      "Tomaten, Zucker und restliches Salz zugeben und 15 Minuten einkochen lassen, Kardamom entfernen und die Soße mit dem Stabmixer fein pürieren.",
      "Sahne, restliche Butter, restliches Garam Masala und zwischen den Händen zerriebene Bockshornkleeblätter einrühren, Hähnchen zugeben und 10 Minuten bei kleiner Hitze fertig garen.",
      "Mit Zitronensaft und Salz abschmecken, mit Koriander bestreuen und mit Reis servieren.",
    ],
    description: "Murgh Makhani, mariniertes Hähnchen in samtiger Tomaten-Butter-Soße, in den 1950er-Jahren im Restaurant Moti Mahal in Delhi entstanden.",
    source: "klassiker",
  },
  {
    name: "Palak Paneer",
    category: "Hauptgericht",
    cuisine: "Indisch",
    origin: "Punjab, Nordindien",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "800 g Blattspinat",
      "400 g Paneer",
      "3 EL Ghee",
      "2 Zwiebeln",
      "4 Zehen Knoblauch",
      "30 g Ingwer",
      "2 grüne Chilis",
      "1 TL Kreuzkümmelsamen",
      "2 Tomaten",
      "1 TL Koriander, gemahlen",
      "0.5 TL Kurkuma",
      "1 TL Garam Masala",
      "100 ml Sahne",
      "1.5 TL Salz",
      "1 Zitrone",
      "4 Naan",
    ],
    steps: [
      "Spinat waschen, in reichlich kochendem Salzwasser 2 Minuten blanchieren, in Eiswasser abschrecken, ausdrücken und mit den Chilis fein pürieren.",
      "Paneer in 2 cm große Würfel schneiden und in 1 EL Ghee bei mittlerer Hitze rundum 5 Minuten goldbraun braten, herausnehmen.",
      "Zwiebeln fein würfeln, Knoblauch und Ingwer reiben, Tomaten fein würfeln.",
      "Restliches Ghee erhitzen, Kreuzkümmelsamen 20 Sekunden rösten, Zwiebeln 6 Minuten goldgelb braten, Knoblauch und Ingwer 1 Minute mitrösten.",
      "Tomaten, Koriander, Kurkuma und Salz zugeben und 5 Minuten einkochen, bis eine dicke Masse entsteht.",
      "Spinatpüree einrühren, 5 Minuten köcheln, dann Sahne, Garam Masala und Paneer zugeben und 3 Minuten erwärmen.",
      "Mit Zitronensaft und Salz abschmecken und mit warmem Naan servieren.",
    ],
    description: "Gebratener Frischkäse in cremigem Spinatpüree mit Knoblauch und Ingwer, eines der bekanntesten vegetarischen Gerichte Nordindiens.",
    source: "klassiker",
  },
  {
    name: "Aloo Gobi",
    category: "Hauptgericht",
    cuisine: "Indisch",
    origin: "Punjab, Nordindien",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "600 g Kartoffeln, festkochend",
      "1 Blumenkohl",
      "4 EL Pflanzenöl",
      "1 TL Kreuzkümmelsamen",
      "1 Zwiebel",
      "3 Zehen Knoblauch",
      "30 g Ingwer",
      "1 grüne Chili",
      "2 Tomaten",
      "1 TL Kurkuma",
      "2 TL Koriander, gemahlen",
      "0.5 TL Chilipulver",
      "1 TL Garam Masala",
      "1.5 TL Salz",
      "1 Bund Koriander",
      "4 Chapati",
    ],
    steps: [
      "Kartoffeln schälen und in 2 cm große Würfel schneiden, Blumenkohl in kleine Röschen teilen; Zwiebel fein würfeln, Knoblauch, Ingwer und Chili fein hacken, Tomaten würfeln.",
      "Öl in einer großen Pfanne mit Deckel erhitzen, Kreuzkümmelsamen 20 Sekunden rösten, Zwiebel 5 Minuten goldgelb braten, Knoblauch, Ingwer und Chili 1 Minute mitrösten.",
      "Kurkuma, Koriander und Chilipulver einrühren, Kartoffeln zugeben und 3 Minuten unter Rühren anbraten.",
      "Blumenkohl, Tomaten, Salz und 100 ml Wasser zugeben, Deckel auflegen und bei kleiner Hitze 20 Minuten garen, dabei alle 5 Minuten vorsichtig wenden.",
      "Deckel abnehmen, Garam Masala einrühren und 3 Minuten offen braten, bis die Flüssigkeit verdampft ist und das Gemüse leicht Farbe nimmt.",
      "Mit Salz abschmecken, mit Koriander bestreuen und mit Chapati servieren.",
    ],
    description: "Trocken geschmortes Kartoffel-Blumenkohl-Gemüse mit Kurkuma und Kreuzkümmel, ein Hausmannsgericht aus dem Punjab.",
    source: "klassiker",
  },
  {
    name: "Chicken Tikka Masala",
    category: "Hauptgericht",
    cuisine: "Indisch",
    origin: "Britisch-indische Küche",
    veg: false,
    servings: 4,
    minutes: 70,
    ingredients: [
      "800 g Hähnchenbrust",
      "200 g Joghurt",
      "2 Zitronen",
      "6 Zehen Knoblauch",
      "40 g Ingwer",
      "3 TL Garam Masala",
      "2 TL Kreuzkümmel, gemahlen",
      "2 TL Koriander, gemahlen",
      "1 TL Kurkuma",
      "2 TL Paprikapulver, edelsüß",
      "1 TL Chilipulver",
      "3 EL Pflanzenöl",
      "2 Zwiebeln",
      "2 EL Tomatenmark",
      "1 Dose Tomaten, gehackt",
      "200 ml Sahne",
      "1 TL Zucker",
      "2 TL Salz",
      "1 Bund Koriander",
      "400 g Basmatireis",
    ],
    steps: [
      "Hähnchen in 3 cm große Würfel schneiden und mit Joghurt, Saft von 1 Zitrone, der Hälfte des geriebenen Knoblauchs und Ingwers, 1 TL Garam Masala, je 1 TL Kreuzkümmel und Koriander, Kurkuma, 1 TL Paprikapulver und 1 TL Salz mindestens 30 Minuten marinieren.",
      "Reis waschen und in der 1.5-fachen Menge Salzwasser zugedeckt 12 Minuten garen, dann 5 Minuten nachquellen lassen.",
      "Backofengrill auf höchste Stufe vorheizen, Hähnchen auf ein Blech mit Backpapier legen und 10 Minuten grillen, bis es dunkle Röststellen hat, einmal wenden.",
      "Öl in einem Topf erhitzen, fein gewürfelte Zwiebeln bei mittlerer Hitze 8 Minuten goldbraun braten, restlichen Knoblauch und Ingwer 1 Minute mitrösten.",
      "Tomatenmark, restliche Gewürze und Chilipulver 1 Minute rösten, Tomaten, Zucker und restliches Salz zugeben und 10 Minuten einkochen.",
      "Soße mit dem Stabmixer glatt pürieren, Sahne einrühren, Hähnchen samt Bratsaft zugeben und 5 Minuten bei kleiner Hitze ziehen lassen.",
      "Mit Zitronensaft und Salz abschmecken, mit Koriander bestreuen und mit Reis servieren.",
    ],
    description: "Gegrillte Hähnchenwürfel in cremiger Tomaten-Gewürz-Soße, in indischen Restaurants Großbritanniens entstanden und heute weltweit ein Standard der indischen Küche.",
    source: "klassiker",
  },

  // ---------- Asien ----------
  {
    name: "Pad Thai",
    category: "Hauptgericht",
    cuisine: "Asiatisch",
    origin: "Thailand",
    veg: false,
    servings: 4,
    minutes: 35,
    ingredients: [
      "400 g Reisbandnudeln",
      "400 g Garnelen, geschält",
      "200 g fester Tofu",
      "4 Eier",
      "4 Zehen Knoblauch",
      "4 Schalotten",
      "4 EL Pflanzenöl",
      "4 EL Fischsoße",
      "4 EL Tamarindenpaste",
      "3 EL Palmzucker",
      "1 TL Chiliflocken",
      "200 g Sojasprossen",
      "1 Bund Schnittknoblauch",
      "80 g Erdnüsse, geröstet",
      "2 Limetten",
    ],
    steps: [
      "Reisnudeln 20 Minuten in warmem Wasser einweichen, bis sie biegsam sind, dann abgießen.",
      "Fischsoße, Tamarindenpaste und Palmzucker in einem kleinen Topf unter Rühren erwärmen, bis der Zucker gelöst ist; Tofu würfeln, Knoblauch und Schalotten fein hacken, Erdnüsse grob hacken, Schnittknoblauch in 4 cm lange Stücke schneiden.",
      "2 EL Öl in einem Wok sehr stark erhitzen, Tofu 3 Minuten goldbraun braten, Garnelen zugeben und 2 Minuten mitbraten, alles herausnehmen.",
      "Restliches Öl erhitzen, Knoblauch und Schalotten 30 Sekunden anbraten, Eier hineinschlagen und unter Rühren stocken lassen.",
      "Nudeln und Soße zugeben und 3 Minuten unter ständigem Wenden braten, bis die Nudeln die Soße aufgenommen haben und weich sind.",
      "Tofu, Garnelen, Chiliflocken, die Hälfte der Sprossen und den Schnittknoblauch zugeben und 1 Minute durchschwenken.",
      "Mit Erdnüssen, restlichen Sprossen und Limettenspalten anrichten.",
    ],
    description: "Gebratene Reisnudeln mit Tamarinde, Fischsoße, Ei und Erdnüssen, seit den 1940er-Jahren das Nationalgericht Thailands und sein bekanntestes Straßenessen.",
    source: "klassiker",
  },
  {
    name: "Grünes Thai-Curry mit Hähnchen",
    category: "Hauptgericht",
    cuisine: "Asiatisch",
    origin: "Zentralthailand",
    veg: false,
    servings: 4,
    minutes: 35,
    ingredients: [
      "700 g Hähnchenbrust",
      "4 EL grüne Currypaste",
      "2 Dosen Kokosmilch",
      "2 EL Pflanzenöl",
      "300 g Thai-Auberginen",
      "1 Glas Bambussprossen",
      "1 rote Paprika",
      "3 EL Fischsoße",
      "1 EL Palmzucker",
      "4 Kaffirlimettenblätter",
      "1 Bund Thai-Basilikum",
      "1 rote Chili",
      "400 g Jasminreis",
    ],
    steps: [
      "Jasminreis waschen und in der 1.25-fachen Menge Wasser zugedeckt 12 Minuten garen, dann 10 Minuten nachquellen lassen.",
      "Hähnchen in dünne Streifen schneiden, Auberginen vierteln, Paprika in Streifen schneiden, Bambussprossen abtropfen lassen.",
      "Öl in einem Wok erhitzen und die Currypaste mit dem festen Teil einer Dose Kokosmilch bei mittlerer Hitze 3 Minuten rösten, bis sie duftet und sich das Öl absetzt.",
      "Hähnchen zugeben und 3 Minuten unter Rühren anbraten, bis es außen weiß ist.",
      "Restliche Kokosmilch, Fischsoße, Palmzucker und Limettenblätter zugeben, aufkochen und 5 Minuten köcheln lassen.",
      "Auberginen, Bambussprossen und Paprika zugeben und 6 Minuten garen, bis das Gemüse bissfest und das Hähnchen durch ist.",
      "Mit Fischsoße abschmecken, Thai-Basilikum unterrühren, mit Chiliringen bestreuen und mit Jasminreis servieren.",
    ],
    description: "Gaeng Kiao Wan, das grüne Kokoscurry aus Zentralthailand mit Thai-Auberginen und Basilikum; die Schärfe kommt aus grünen Chilis in der Paste.",
    source: "klassiker",
  },
  {
    name: "Nasi Goreng",
    category: "Hauptgericht",
    cuisine: "Asiatisch",
    origin: "Indonesien",
    veg: false,
    servings: 4,
    minutes: 30,
    ingredients: [
      "400 g Jasminreis",
      "400 g Hähnchenbrust",
      "4 Schalotten",
      "4 Zehen Knoblauch",
      "2 rote Chilis",
      "2 TL Garnelenpaste",
      "4 EL Pflanzenöl",
      "4 EL Ketjap Manis",
      "2 EL Sojasoße",
      "3 Möhren",
      "200 g Weißkohl",
      "4 Eier",
      "4 Frühlingszwiebeln",
      "1 Salatgurke",
      "4 EL Röstzwiebeln",
      "1 Päckchen Krupuk",
    ],
    steps: [
      "Reis am Vortag kochen und offen im Kühlschrank auskühlen lassen, nur kalter, trockener Reis wird beim Braten körnig.",
      "Schalotten, Knoblauch, Chilis und Garnelenpaste im Mörser oder Mixer zu einer Paste verarbeiten; Hähnchen in kleine Würfel, Möhren in feine Stifte, Kohl in feine Streifen schneiden.",
      "2 EL Öl im Wok stark erhitzen, Hähnchen 4 Minuten rundum braten und herausnehmen.",
      "Restliches Öl erhitzen, Gewürzpaste 2 Minuten rösten, Möhren und Kohl zugeben und 3 Minuten braten.",
      "Reis zugeben, mit Ketjap Manis und Sojasoße beträufeln und 5 Minuten unter Wenden braten, bis alles gleichmäßig braun ist, Hähnchen untermischen.",
      "In einer zweiten Pfanne vier Spiegeleier braten.",
      "Nasi Goreng mit Frühlingszwiebelringen und Röstzwiebeln bestreuen, mit je einem Spiegelei, Gurkenscheiben und Krupuk servieren.",
    ],
    description: "Indonesischer gebratener Reis mit süßer Sojasoße, Garnelenpaste und Spiegelei, das Nationalgericht des Landes; der Reis wird dafür am Vortag gekocht und kalt verarbeitet.",
    source: "klassiker",
  },
  {
    name: "Gebratene Nudeln mit Gemüse",
    category: "Schnelle Küche",
    cuisine: "Asiatisch",
    origin: "Südchina",
    veg: true,
    servings: 4,
    minutes: 25,
    ingredients: [
      "400 g chinesische Eiernudeln",
      "4 EL Pflanzenöl",
      "4 Zehen Knoblauch",
      "30 g Ingwer",
      "2 Möhren",
      "1 rote Paprika",
      "200 g Zuckerschoten",
      "200 g Pak Choi",
      "150 g Sojasprossen",
      "4 Frühlingszwiebeln",
      "4 EL helle Sojasoße",
      "1 EL dunkle Sojasoße",
      "2 EL vegetarische Austernsoße",
      "1 TL Zucker",
      "2 TL Sesamöl",
      "Pfeffer",
    ],
    steps: [
      "Nudeln nach Packungsangabe in kochendem Wasser garen, kalt abschrecken, abtropfen lassen und mit 1 EL Öl mischen, damit sie nicht kleben.",
      "Knoblauch und Ingwer fein hacken, Möhren und Paprika in feine Streifen, Pak Choi in Streifen, Frühlingszwiebeln in 4 cm lange Stücke schneiden; beide Sojasoßen, Austernsoße, Zucker und Sesamöl verrühren.",
      "2 EL Öl im Wok sehr stark erhitzen, Nudeln hineingeben und 3 Minuten ohne viel Rühren braten, bis sie unten knusprig sind, dann herausnehmen.",
      "Restliches Öl erhitzen, Knoblauch und Ingwer 20 Sekunden anbraten, Möhren und Paprika 2 Minuten, Zuckerschoten und Pak Choi weitere 2 Minuten pfannenrühren.",
      "Nudeln, Soße, Sprossen und Frühlingszwiebeln zugeben und 2 Minuten unter Wenden braten, bis alles heiß und gleichmäßig überzogen ist.",
      "Mit Pfeffer abschmecken und sofort servieren.",
    ],
    description: "Chow Mein, die in Südchina und der Kantonküche verbreiteten, im Wok knusprig gebratenen Eiernudeln mit Gemüse und Sojasoße.",
    source: "klassiker",
  },
  {
    name: "Teriyaki-Lachs mit Reis",
    category: "Schnelle Küche",
    cuisine: "Asiatisch",
    origin: "Japan",
    veg: false,
    servings: 4,
    minutes: 30,
    ingredients: [
      "800 g Lachsfilet mit Haut",
      "400 g Sushireis",
      "6 EL Sojasoße",
      "6 EL Mirin",
      "4 EL Sake",
      "2 EL Zucker",
      "20 g Ingwer",
      "1 EL Pflanzenöl",
      "2 EL Sesam",
      "4 Frühlingszwiebeln",
      "300 g Brokkoli",
    ],
    steps: [
      "Reis waschen, bis das Wasser klar bleibt, mit 500 ml Wasser aufkochen, zugedeckt bei kleinster Hitze 12 Minuten garen und 10 Minuten nachquellen lassen.",
      "Sojasoße, Mirin, Sake, Zucker und geriebenen Ingwer in einem kleinen Topf aufkochen und 5 Minuten leicht sirupartig einkochen lassen.",
      "Brokkoli in Röschen teilen und in Salzwasser 4 Minuten bissfest kochen, abgießen.",
      "Lachs in vier Stücke teilen, trocken tupfen, Öl in einer beschichteten Pfanne erhitzen und die Stücke auf der Hautseite bei mittlerer bis starker Hitze 4 Minuten braten, wenden und 2 Minuten weiterbraten.",
      "Teriyakisoße in die Pfanne gießen und den Lachs darin 2 Minuten glasieren, dabei immer wieder mit Soße übergießen.",
      "Reis in Schalen füllen, Lachs und Brokkoli daraufsetzen, mit restlicher Soße beträufeln und mit Sesam und Frühlingszwiebelringen bestreuen.",
    ],
    description: "Lachs in einer Glasur aus Sojasoße, Mirin und Sake, nach japanischer Teriyaki-Art in der Pfanne glänzend eingekocht, dazu Reis und Gemüse.",
    source: "klassiker",
  },
  {
    name: "Bibimbap",
    category: "Hauptgericht",
    cuisine: "Asiatisch",
    origin: "Korea",
    veg: false,
    servings: 4,
    minutes: 60,
    ingredients: [
      "400 g Rundkornreis",
      "400 g Rinderhackfleisch",
      "6 EL Sojasoße",
      "2 EL Zucker",
      "4 Zehen Knoblauch",
      "4 EL Sesamöl",
      "300 g Blattspinat",
      "2 Möhren",
      "1 Zucchini",
      "200 g Sojasprossen",
      "200 g Shiitake",
      "4 Eier",
      "3 EL Pflanzenöl",
      "4 EL Gochujang",
      "1 EL Reisessig",
      "2 EL Sesam",
      "Salz",
    ],
    steps: [
      "Reis waschen, mit 500 ml Wasser aufkochen, zugedeckt bei kleinster Hitze 12 Minuten garen und 10 Minuten nachquellen lassen.",
      "Hackfleisch mit 3 EL Sojasoße, 1 EL Zucker, 2 gepressten Zehen Knoblauch und 1 EL Sesamöl mischen und 10 Minuten marinieren.",
      "Spinat 1 Minute blanchieren, ausdrücken und mit 1 EL Sojasoße, 1 EL Sesamöl und etwas Salz mischen; Sprossen 3 Minuten blanchieren und ebenso würzen.",
      "Möhren und Zucchini in feine Stifte, Shiitake in Scheiben schneiden und nacheinander in je 1 EL Pflanzenöl bei starker Hitze 2 bis 3 Minuten braten, jeweils leicht salzen und getrennt beiseitestellen.",
      "Hackfleisch in derselben Pfanne 5 Minuten krümelig braten; für die Soße Gochujang mit restlichem Zucker, 2 EL Sojasoße, Reisessig und 1 EL Sesamöl glatt rühren.",
      "Vier Spiegeleier braten, das Eigelb soll flüssig bleiben.",
      "Reis in vier Schalen füllen, Fleisch und Gemüse in Häufchen darauf anordnen, je ein Spiegelei in die Mitte setzen, mit Sesam bestreuen und die Soße dazu reichen; am Tisch wird alles kräftig vermischt.",
    ],
    description: "Koreanische Reisschale mit getrennt gewürztem Gemüse, mariniertem Fleisch, Spiegelei und scharfer Gochujang-Soße, die erst am Tisch vermischt wird.",
    source: "klassiker",
  },
  {
    name: "Mapo Tofu",
    category: "Hauptgericht",
    cuisine: "Asiatisch",
    origin: "Sichuan, China",
    veg: false,
    servings: 4,
    minutes: 30,
    ingredients: [
      "800 g Seidentofu",
      "250 g Schweinehackfleisch",
      "3 EL Pflanzenöl",
      "3 EL Doubanjiang",
      "1 EL fermentierte schwarze Bohnen",
      "4 Zehen Knoblauch",
      "30 g Ingwer",
      "2 TL Sichuanpfeffer",
      "1 EL Chiliflocken",
      "400 ml Hühnerbrühe",
      "2 EL Sojasoße",
      "1 TL Zucker",
      "2 EL Speisestärke",
      "4 Frühlingszwiebeln",
      "400 g Jasminreis",
    ],
    steps: [
      "Reis waschen und in der 1.25-fachen Menge Wasser zugedeckt 12 Minuten garen, dann 10 Minuten nachquellen lassen.",
      "Tofu in 2 cm große Würfel schneiden und in leicht gesalzenem, siedendem Wasser 2 Minuten ziehen lassen, damit er fest wird, dann vorsichtig abgießen.",
      "Sichuanpfeffer in einer trockenen Pfanne 1 Minute rösten und im Mörser fein zerstoßen; Knoblauch und Ingwer fein hacken, schwarze Bohnen grob hacken, Stärke mit 4 EL Wasser anrühren.",
      "Öl im Wok erhitzen und das Hackfleisch bei starker Hitze 3 Minuten krümelig und knusprig braten.",
      "Hitze reduzieren, Doubanjiang, schwarze Bohnen, Knoblauch, Ingwer und Chiliflocken zugeben und 2 Minuten rösten, bis das Öl rot ist.",
      "Brühe, Sojasoße und Zucker zugeben, aufkochen, Tofu einlegen und 5 Minuten leise köcheln lassen, dabei nur durch Schwenken bewegen.",
      "Stärke einrühren und kurz aufkochen, bis die Soße bindet, mit Sichuanpfeffer und Frühlingszwiebelringen bestreuen und mit Reis servieren.",
    ],
    description: "Seidentofu mit Hackfleisch in scharfer, roter Bohnenpasten-Soße mit betäubendem Sichuanpfeffer, eines der berühmtesten Gerichte der Sichuan-Küche.",
    source: "klassiker",
  },
  {
    name: "Kung Pao Hühnchen",
    category: "Hauptgericht",
    cuisine: "Asiatisch",
    origin: "Sichuan, China",
    veg: false,
    servings: 4,
    minutes: 35,
    ingredients: [
      "700 g Hähnchenbrust",
      "3 EL Sojasoße",
      "2 EL Shaoxing-Reiswein",
      "3 TL Speisestärke",
      "3 EL Chinkiang-Essig",
      "2 EL Zucker",
      "1 TL dunkle Sojasoße",
      "100 ml Hühnerbrühe",
      "4 EL Pflanzenöl",
      "10 Chilis, getrocknet",
      "2 TL Sichuanpfeffer",
      "4 Zehen Knoblauch",
      "30 g Ingwer",
      "6 Frühlingszwiebeln",
      "100 g Erdnüsse, geröstet",
      "400 g Jasminreis",
    ],
    steps: [
      "Reis waschen und in der 1.25-fachen Menge Wasser zugedeckt 12 Minuten garen, dann 10 Minuten nachquellen lassen.",
      "Hähnchen in 2 cm große Würfel schneiden und mit 1 EL Sojasoße, 1 EL Reiswein und 2 TL Stärke 15 Minuten marinieren.",
      "Für die Soße restliche Sojasoße, restlichen Reiswein, Essig, Zucker, dunkle Sojasoße, Brühe und restliche Stärke verrühren; Knoblauch und Ingwer in Scheiben, das Weiße der Frühlingszwiebeln in 2 cm lange Stücke schneiden.",
      "2 EL Öl im Wok sehr stark erhitzen, Hähnchen 4 Minuten braten, bis es leicht gebräunt ist, und herausnehmen.",
      "Restliches Öl erhitzen, Chilis und Sichuanpfeffer bei mittlerer Hitze 30 Sekunden rösten, bis die Chilis dunkel werden, Knoblauch, Ingwer und Frühlingszwiebeln 1 Minute mitbraten.",
      "Hähnchen zurück in den Wok geben, Soße nochmals umrühren und zugießen und 1 bis 2 Minuten unter Wenden kochen, bis sie glänzend bindet.",
      "Erdnüsse unterheben, mit dem Grün der Frühlingszwiebeln bestreuen und mit Reis servieren.",
    ],
    description: "Gong Bao Ji Ding, gebratene Hähnchenwürfel mit getrockneten Chilis, Sichuanpfeffer und Erdnüssen in süß-saurer Soße, benannt nach einem Gouverneur Sichuans im 19. Jahrhundert.",
    source: "klassiker",
  },
  {
    name: "Satay-Spieße mit Erdnusssoße",
    category: "Hauptgericht",
    cuisine: "Asiatisch",
    origin: "Indonesien und Malaysia",
    veg: false,
    servings: 4,
    minutes: 55,
    ingredients: [
      "800 g Hähnchenschenkelfleisch ohne Knochen",
      "16 Holzspieße",
      "4 Schalotten",
      "4 Zehen Knoblauch",
      "2 Zitronengrasstangen",
      "30 g Ingwer",
      "2 TL Kurkuma",
      "2 TL Koriander, gemahlen",
      "1 TL Kreuzkümmel, gemahlen",
      "3 EL Ketjap Manis",
      "4 EL Pflanzenöl",
      "1 TL Salz",
      "200 g Erdnussbutter",
      "250 ml Kokosmilch",
      "2 EL Sambal Oelek",
      "1 EL Palmzucker",
      "2 Limetten",
      "1 Salatgurke",
      "400 g Jasminreis",
    ],
    steps: [
      "Holzspieße 30 Minuten wässern; Hähnchen in 2 cm große Würfel schneiden.",
      "Schalotten, Knoblauch, das Weiche vom Zitronengras und Ingwer fein hacken und mit Kurkuma, Koriander, Kreuzkümmel, 2 EL Ketjap Manis, 2 EL Öl und Salz zur Marinade mischen, das Fleisch darin mindestens 30 Minuten marinieren.",
      "Reis waschen und in der 1.25-fachen Menge Wasser zugedeckt 12 Minuten garen, dann 10 Minuten nachquellen lassen.",
      "Für die Soße Erdnussbutter mit Kokosmilch, Sambal Oelek, Palmzucker, restlichem Ketjap Manis und dem Saft 1 Limette in einem Topf unter Rühren 5 Minuten erhitzen, bis sie cremig ist, mit Salz abschmecken.",
      "Fleisch auf die Spieße stecken, mit restlichem Öl bestreichen und auf dem Grill oder in einer Grillpfanne bei starker Hitze 8 bis 10 Minuten rundum braten, bis es außen dunkel gebräunt und innen gar ist.",
      "Spieße mit Erdnusssoße, Gurkenscheiben, Limettenspalten und Reis servieren.",
    ],
    description: "Gegrillte marinierte Fleischspieße mit Erdnusssoße, das Straßenessen Indonesiens und Malaysias, hier in der weit verbreiteten Hähnchen-Variante Sate Ayam.",
    source: "klassiker",
  },
  {
    name: "Gebackene Frühlingsrollen",
    category: "Snacks",
    cuisine: "Asiatisch",
    origin: "China",
    veg: true,
    servings: 4,
    minutes: 50,
    ingredients: [
      "16 Frühlingsrollenblätter",
      "50 g Glasnudeln",
      "300 g Weißkohl",
      "2 Möhren",
      "150 g Shiitake",
      "150 g Sojasprossen",
      "4 Frühlingszwiebeln",
      "3 Zehen Knoblauch",
      "20 g Ingwer",
      "3 EL Pflanzenöl",
      "3 EL Sojasoße",
      "1 TL Zucker",
      "2 TL Sesamöl",
      "Pfeffer",
      "1 EL Speisestärke",
      "150 ml süße Chilisoße",
    ],
    steps: [
      "Glasnudeln 10 Minuten in heißem Wasser einweichen, abgießen und mit der Schere in kurze Stücke schneiden; Kohl und Möhren in feine Streifen, Shiitake in Scheiben, Frühlingszwiebeln in Ringe schneiden, Knoblauch und Ingwer fein hacken.",
      "1 EL Öl im Wok stark erhitzen, Knoblauch und Ingwer 20 Sekunden anbraten, Kohl, Möhren und Pilze 4 Minuten pfannenrühren, Sprossen, Frühlingszwiebeln, Glasnudeln, Sojasoße, Zucker, Sesamöl und Pfeffer zugeben und 1 Minute mischen.",
      "Füllung auf einem Blech ausbreiten und 15 Minuten vollständig auskühlen lassen; Stärke mit 2 EL Wasser anrühren.",
      "Backofen auf 200 °C Ober- und Unterhitze vorheizen; je ein Blatt mit einer Ecke zu sich legen, 2 EL Füllung in den unteren Teil geben, die untere Ecke darüberklappen, die Seiten einschlagen, fest aufrollen und die letzte Ecke mit Stärkewasser festkleben.",
      "Rollen mit Abstand auf ein Blech mit Backpapier legen, rundum mit restlichem Öl bestreichen und 20 Minuten backen, nach 10 Minuten wenden, bis sie goldbraun und knusprig sind.",
      "Heiß mit süßer Chilisoße servieren.",
    ],
    description: "Knusprige Teigrollen mit Gemüse-Glasnudel-Füllung, ein chinesischer Klassiker zum Frühlingsfest, hier statt frittiert im Ofen gebacken.",
    source: "klassiker",
  },
  {
    name: "Miso-Suppe",
    category: "Schnelle Küche",
    cuisine: "Asiatisch",
    origin: "Japan",
    veg: true,
    servings: 4,
    minutes: 15,
    ingredients: [
      "1.2 l Wasser",
      "10 g Kombu",
      "10 g Shiitake, getrocknet",
      "4 EL helle Misopaste",
      "300 g Seidentofu",
      "3 EL Wakame, getrocknet",
      "4 Frühlingszwiebeln",
    ],
    steps: [
      "Kombu und getrocknete Shiitake in das kalte Wasser legen, langsam erhitzen und kurz vor dem Kochen den Kombu herausnehmen; die Brühe 5 Minuten leise ziehen lassen, dann Pilze herausnehmen und in Streifen schneiden.",
      "Wakame in einer Schale mit kaltem Wasser 5 Minuten einweichen und abgießen; Tofu in 1 cm große Würfel, Frühlingszwiebeln in feine Ringe schneiden.",
      "Brühe auf kleine Hitze stellen, Misopaste in einer Kelle mit etwas Brühe glatt rühren und einrühren, die Suppe darf jetzt nicht mehr kochen, sonst verliert das Miso sein Aroma.",
      "Tofu, Wakame und Pilzstreifen zugeben und 2 Minuten erwärmen.",
      "In Schalen füllen und mit Frühlingszwiebeln bestreuen.",
    ],
    description: "Die japanische Alltagssuppe aus Dashi-Brühe und Misopaste mit Tofu und Wakame, in Japan Teil fast jeder Mahlzeit vom Frühstück bis zum Abendessen.",
    source: "klassiker",
  },
  {
    name: "Gyoza",
    category: "Snacks",
    cuisine: "Asiatisch",
    origin: "Japan",
    veg: false,
    servings: 4,
    minutes: 50,
    ingredients: [
      "40 Gyoza-Teigblätter",
      "400 g Schweinehackfleisch",
      "250 g Chinakohl",
      "4 Frühlingszwiebeln",
      "3 Zehen Knoblauch",
      "20 g Ingwer",
      "2 EL Sojasoße",
      "1 EL Sake",
      "2 TL Sesamöl",
      "1 TL Zucker",
      "1 TL Salz",
      "Pfeffer",
      "3 EL Pflanzenöl",
      "4 EL Reisessig",
      "1 TL Chiliöl",
    ],
    steps: [
      "Chinakohl sehr fein hacken, mit 1 TL Salz mischen, 10 Minuten stehen lassen und kräftig ausdrücken; Frühlingszwiebeln fein schneiden, Knoblauch und Ingwer reiben.",
      "Hackfleisch mit Kohl, Frühlingszwiebeln, Knoblauch, Ingwer, 1 EL Sojasoße, Sake, Sesamöl, Zucker und Pfeffer 3 Minuten kräftig verkneten, bis die Masse klebrig wird.",
      "Je 1 gehäuften TL bis 1 EL Füllung, etwa 15 g, in die Mitte eines Teigblatts setzen, den Rand mit Wasser befeuchten, zum Halbmond zusammenklappen und den Rand mit 4 bis 5 Falten fest verschließen.",
      "1 EL Öl in einer beschichteten Pfanne mit Deckel erhitzen, ein Drittel der Gyoza mit der flachen Seite nach unten einsetzen und bei mittlerer bis starker Hitze 2 Minuten braten, bis der Boden goldbraun ist.",
      "100 ml Wasser angießen, sofort den Deckel auflegen und 5 Minuten dämpfen, dann Deckel abnehmen und das restliche Wasser 1 Minute verdampfen lassen; mit den weiteren Portionen ebenso verfahren.",
      "Restliche Sojasoße mit Reisessig und Chiliöl zu einem Dip verrühren und die Gyoza mit der knusprigen Seite nach oben damit servieren.",
    ],
    description: "Japanische Teigtaschen mit Schweinefleisch-Kohl-Füllung, in der Pfanne erst gebraten und dann gedämpft, so dass der Boden knusprig und die Oberseite weich ist.",
    source: "klassiker",
  },
];
