// Klassiker-Basis: Schwäbische und süddeutsche Küche.
// Etablierte Gerichte aus Schwaben, Bayern und Österreich, Mengen für 4 Personen.
// Form siehe docs/ARCHITEKTUR.md, Abschnitt 3 "Recipe" (source "klassiker", origin Pflicht).

export default [
  {
    name: "Käsespätzle",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: true,
    servings: 4,
    minutes: 50,
    ingredients: [
      "400 g Mehl",
      "4 Eier",
      "150 ml Wasser",
      "1 TL Salz",
      "250 g Bergkäse, gerieben",
      "3 Zwiebeln",
      "3 EL Butter",
      "Pfeffer",
      "Muskat",
      "1 Bund Schnittlauch",
    ],
    steps: [
      "Mehl, Eier, Salz und Wasser mit dem Kochlöffel zu einem zähen Teig schlagen, bis er Blasen wirft, und 10 Minuten ruhen lassen.",
      "Zwiebeln in feine Ringe schneiden und in 2 EL Butter bei mittlerer Hitze etwa 15 Minuten goldbraun rösten, dabei öfter wenden.",
      "Einen großen Topf Salzwasser aufkochen, den Teig portionsweise durch den Spätzlehobel drücken oder vom Brett schaben und die aufsteigenden Spätzle nach 1 Minute mit der Schaumkelle herausheben.",
      "Backofen auf 100 °C vorheizen, eine Auflaufform mit der restlichen Butter fetten und Spätzle und Käse abwechselnd einschichten, mit Pfeffer und Muskat würzen und mit Käse abschließen.",
      "Form 10 Minuten in den Ofen stellen, bis der Käse geschmolzen ist und Fäden zieht.",
      "Mit Röstzwiebeln und geschnittenem Schnittlauch bestreuen und mit grünem Salat servieren.",
    ],
    description: "Der schwäbische Klassiker aus geschichteten Spätzle, würzigem Bergkäse und Röstzwiebeln, traditionell mit grünem Salat.",
    source: "klassiker",
  },
  {
    name: "Linsen mit Spätzle und Saitenwürstle",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 75,
    ingredients: [
      "400 g Tellerlinsen",
      "100 g Räucherspeck",
      "2 Zwiebeln",
      "2 Möhren",
      "150 g Knollensellerie",
      "2 EL Butterschmalz",
      "2 EL Mehl",
      "1.2 l Gemüsebrühe",
      "2 Lorbeerblätter",
      "3 EL Weinessig",
      "1 EL Zucker",
      "Salz",
      "Pfeffer",
      "8 Saitenwürstle",
      "500 g Spätzle",
    ],
    steps: [
      "Linsen in einem Sieb kalt abspülen; Speck, Zwiebeln, Möhren und Sellerie fein würfeln.",
      "Speck und Zwiebeln in Butterschmalz bei mittlerer Hitze 5 Minuten anschwitzen, Möhren und Sellerie 5 Minuten mitdünsten.",
      "Mehl darüberstäuben und unter Rühren 2 Minuten hellbraun anrösten, dann nach und nach die Brühe angießen und glatt rühren.",
      "Linsen und Lorbeerblätter zugeben und zugedeckt bei kleiner Hitze 40 bis 45 Minuten köcheln, bis die Linsen weich sind, gelegentlich umrühren.",
      "Lorbeer entfernen und die Linsen süßsauer mit Essig, Zucker, Salz und Pfeffer abschmecken.",
      "Saitenwürstle in heißem Wasser 10 Minuten ziehen lassen, nicht kochen, damit sie nicht platzen.",
      "Spätzle in kochendem Salzwasser 2 Minuten erhitzen, abgießen und mit Linsen und Würstle anrichten.",
    ],
    description: "Das schwäbische Nationalgericht: süßsauer abgeschmeckte Linsen mit Spätzle und Saitenwürstle, den dünnen Wiener Würstchen aus Schwaben.",
    source: "klassiker",
  },
  {
    name: "Maultaschen in der Brühe",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 100,
    ingredients: [
      "400 g Mehl",
      "6 Eier",
      "1 TL Salz",
      "2 EL Wasser",
      "2 Brötchen vom Vortag",
      "100 ml Milch",
      "1 Zwiebel",
      "1 EL Butter",
      "300 g Blattspinat, tiefgekühlt",
      "250 g Hackfleisch, gemischt",
      "150 g Kalbsbrät",
      "1 Bund Petersilie",
      "Pfeffer",
      "Muskat",
      "2 l Rinderbrühe",
      "1 Bund Schnittlauch",
    ],
    steps: [
      "Mehl, 4 Eier, Salz und Wasser zu einem glatten, festen Nudelteig kneten, in Folie wickeln und 30 Minuten ruhen lassen.",
      "Brötchen in Scheiben schneiden und in der Milch einweichen; Zwiebel fein würfeln und in Butter 3 Minuten glasig dünsten; Spinat auftauen, kräftig ausdrücken und hacken; Petersilie hacken.",
      "Hackfleisch, Brät, ausgedrückte Brötchen, Zwiebel, Spinat, Petersilie und 2 Eier gründlich vermengen und kräftig mit Salz, Pfeffer und Muskat würzen.",
      "Teig in Portionen 2 mm dünn zu etwa 12 cm breiten Bahnen ausrollen, die Füllung auf die untere Hälfte streichen, die Ränder mit Wasser bestreichen und die obere Hälfte darüberklappen und andrücken.",
      "Mit einem Kochlöffelstiel alle 6 cm quer eindrücken und die Maultaschen mit dem Teigrad voneinander trennen.",
      "Brühe aufkochen, Maultaschen hineingeben und bei kleiner Hitze 12 bis 15 Minuten ziehen lassen, die Brühe darf nicht sprudelnd kochen.",
      "Maultaschen mit Brühe in tiefen Tellern anrichten und mit Schnittlauchröllchen bestreuen.",
    ],
    description: "Die schwäbische Teigtasche mit Spinat-Hackfleisch-Füllung, hier klassisch in der Brühe serviert, wie sie traditionell am Gründonnerstag auf den Tisch kommt.",
    source: "klassiker",
  },
  {
    name: "Geröstete Maultaschen mit Ei",
    category: "Schnelle Küche",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 20,
    ingredients: [
      "8 Maultaschen",
      "2 Zwiebeln",
      "2 EL Butterschmalz",
      "4 Eier",
      "50 ml Milch",
      "Salz",
      "Pfeffer",
      "1 Bund Schnittlauch",
    ],
    steps: [
      "Maultaschen in 1 cm breite Streifen schneiden, Zwiebeln in feine Ringe schneiden.",
      "Butterschmalz in einer großen Pfanne erhitzen und die Zwiebeln bei mittlerer Hitze 5 Minuten goldgelb braten.",
      "Maultaschenstreifen zugeben und bei mittlerer bis starker Hitze 6 bis 8 Minuten unter gelegentlichem Wenden knusprig anrösten.",
      "Eier mit Milch, Salz und Pfeffer verquirlen, gleichmäßig über die Maultaschen gießen und bei kleiner Hitze 3 Minuten stocken lassen, dabei einmal wenden.",
      "Mit Schnittlauchröllchen bestreuen und mit Kartoffelsalat oder grünem Salat servieren.",
    ],
    description: "Die zweite klassische Zubereitung der Maultaschen: in Streifen mit Zwiebeln knusprig gebraten und mit Ei gebunden, ursprünglich eine Resteverwertung vom Vortag.",
    source: "klassiker",
  },
  {
    name: "Gaisburger Marsch",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 165,
    ingredients: [
      "800 g Rindfleisch zum Kochen",
      "2 l Wasser",
      "4 Zwiebeln",
      "1 Bund Suppengrün",
      "2 Lorbeerblätter",
      "1 TL Pfefferkörner",
      "Salz",
      "600 g Kartoffeln",
      "300 g Mehl",
      "3 Eier",
      "100 ml Wasser",
      "3 EL Butter",
      "Pfeffer",
      "Muskat",
      "1 Bund Schnittlauch",
    ],
    steps: [
      "Eine Zwiebel halbieren und mit der Schnittfläche in einer trockenen Pfanne dunkel rösten; Suppengrün putzen und grob schneiden.",
      "Rindfleisch mit 2 l kaltem Wasser, Zwiebel, Suppengrün, Lorbeer und Pfefferkörnern aufsetzen, aufkochen, abschäumen und bei kleiner Hitze 2 Stunden leise simmern lassen, nach 1 Stunde salzen.",
      "Inzwischen Mehl, Eier, 100 ml Wasser und 1 TL Salz zu einem zähen Spätzleteig schlagen, 10 Minuten ruhen lassen und portionsweise in kochendes Salzwasser schaben, aufsteigende Spätzle herausheben.",
      "Fleisch aus der Brühe nehmen und in 2 cm große Würfel schneiden, die Brühe durch ein Sieb gießen und zurück in den Topf geben.",
      "Kartoffeln schälen, würfeln und in der Brühe bei mittlerer Hitze 15 Minuten garen.",
      "Die restlichen Zwiebeln in Ringe schneiden und in Butter bei mittlerer Hitze 15 Minuten goldbraun rösten.",
      "Fleisch und Spätzle in der Brühe erhitzen, mit Salz, Pfeffer und Muskat abschmecken und in tiefen Tellern mit Röstzwiebeln und Schnittlauch servieren.",
    ],
    description: "Kräftiger Eintopf aus dem Stuttgarter Stadtteil Gaisburg: Rindfleisch, Kartoffeln und Spätzle in Brühe, mit Röstzwiebeln bedeckt.",
    source: "klassiker",
  },
  {
    name: "Schupfnudeln mit Sauerkraut",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 90,
    ingredients: [
      "1 kg Kartoffeln, mehligkochend",
      "200 g Mehl",
      "2 Eigelb",
      "Salz",
      "Muskat",
      "800 g Sauerkraut",
      "150 g durchwachsener Speck",
      "1 Zwiebel",
      "3 EL Schweineschmalz",
      "1 TL Kümmel",
      "2 Lorbeerblätter",
      "200 ml Gemüsebrühe",
      "1 TL Zucker",
    ],
    steps: [
      "Kartoffeln in der Schale 25 Minuten weich kochen, pellen, heiß durch die Kartoffelpresse drücken und 10 Minuten ausdampfen lassen.",
      "Kartoffelmasse mit Mehl, Eigelb, 1 TL Salz und Muskat zügig zu einem glatten Teig verkneten, zu daumendicken Rollen formen, 2 cm breite Stücke abschneiden und mit den Händen zu fingerlangen Nudeln mit spitzen Enden rollen.",
      "Speck und Zwiebel würfeln und in 1 EL Schmalz bei mittlerer Hitze 5 Minuten auslassen, Sauerkraut, Kümmel, Lorbeer, Zucker und Brühe zugeben und zugedeckt 30 Minuten bei kleiner Hitze schmoren.",
      "Schupfnudeln portionsweise in siedendes Salzwasser geben und 3 Minuten ziehen lassen, bis sie oben schwimmen, dann abtropfen lassen.",
      "Restliches Schmalz in einer großen Pfanne erhitzen und die Schupfnudeln bei mittlerer Hitze 8 Minuten rundum goldbraun braten.",
      "Schupfnudeln unter das Sauerkraut heben oder getrennt anrichten und sofort servieren.",
    ],
    description: "Fingerdicke Kartoffelnudeln, in Schmalz gebraten und mit geschmortem Sauerkraut serviert, ein Herbst- und Winteressen aus Schwaben.",
    source: "klassiker",
  },
  {
    name: "Zwiebelrostbraten",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 45,
    ingredients: [
      "800 g Rumpsteak",
      "4 Zwiebeln",
      "3 EL Butterschmalz",
      "1 EL Mehl",
      "200 ml Rotwein",
      "300 ml Rinderbrühe",
      "1 TL Senf",
      "1 EL Butter",
      "Salz",
      "Pfeffer",
      "500 g Spätzle",
    ],
    steps: [
      "Zwiebeln in feine Ringe schneiden und in 2 EL Butterschmalz bei mittlerer Hitze 15 Minuten goldbraun rösten, leicht salzen und warm stellen.",
      "Rumpsteak in 4 Scheiben schneiden, den Fettrand mehrmals einschneiden, trocken tupfen und im restlichen Butterschmalz bei starker Hitze pro Seite 2 bis 3 Minuten braten.",
      "Steaks salzen, pfeffern und im Ofen bei 80 °C warm halten.",
      "Mehl in den Bratensatz stäuben, kurz anrösten, mit Rotwein ablöschen und auf die Hälfte einkochen, Brühe angießen und 5 Minuten köcheln lassen.",
      "Die Hälfte der Röstzwiebeln und den Senf in die Soße rühren, kalte Butter unterschwenken und mit Salz und Pfeffer abschmecken.",
      "Spätzle in kochendem Salzwasser 2 Minuten erhitzen, abgießen und mit den Steaks, der Soße und den restlichen Röstzwiebeln anrichten.",
    ],
    description: "Kurz gebratenes Rumpsteak mit einer Haube aus knusprigen Röstzwiebeln und dunkler Soße, das Sonntagsgericht der schwäbischen Wirtshausküche, klassisch mit Spätzle.",
    source: "klassiker",
  },
  {
    name: "Schwäbischer Kartoffelsalat",
    category: "Beilagen & Salate",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: true,
    servings: 4,
    minutes: 60,
    ingredients: [
      "1 kg Kartoffeln, festkochend",
      "1 Zwiebel",
      "250 ml Gemüsebrühe",
      "4 EL Weißweinessig",
      "1 TL Senf",
      "1 TL Zucker",
      "Salz",
      "Pfeffer",
      "5 EL Sonnenblumenöl",
      "1 Bund Schnittlauch",
    ],
    steps: [
      "Kartoffeln in der Schale 20 bis 25 Minuten gar kochen, kurz abkühlen lassen, pellen und noch warm in dünne Scheiben schneiden.",
      "Zwiebel sehr fein würfeln, Brühe erhitzen und mit Zwiebel, Essig, Senf, Zucker, Salz und Pfeffer verrühren.",
      "Die heiße Marinade über die warmen Kartoffelscheiben gießen, vorsichtig mischen und 30 Minuten ziehen lassen, dabei zweimal wenden.",
      "Öl unterheben, nochmals mit Salz, Pfeffer und Essig abschmecken; der Salat soll saftig und nicht trocken sein.",
      "Mit Schnittlauchröllchen bestreut lauwarm servieren.",
    ],
    description: "Der schwäbische Kartoffelsalat wird ohne Mayonnaise mit heißer Brühe, Essig und Öl angemacht und lauwarm gegessen.",
    source: "klassiker",
  },
  {
    name: "Flädlesuppe",
    category: "Schnelle Küche",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 30,
    ingredients: [
      "150 g Mehl",
      "250 ml Milch",
      "3 Eier",
      "Salz",
      "1 Bund Petersilie",
      "2 EL Butterschmalz",
      "1.5 l Rinderbrühe",
      "Pfeffer",
      "Muskat",
      "1 Bund Schnittlauch",
    ],
    steps: [
      "Mehl, Milch, Eier und 1 Prise Salz zu einem glatten, dünnflüssigen Teig rühren und 10 Minuten quellen lassen; Petersilie hacken und unterrühren.",
      "In einer beschichteten Pfanne mit wenig Butterschmalz nacheinander 6 bis 8 dünne Pfannkuchen bei mittlerer Hitze je 2 Minuten pro Seite goldgelb backen.",
      "Flädle aufrollen und in 5 mm breite Streifen schneiden.",
      "Brühe aufkochen und mit Salz, Pfeffer und Muskat abschmecken.",
      "Flädlestreifen auf vorgewärmte Teller verteilen, mit heißer Brühe übergießen und mit Schnittlauch bestreut servieren.",
    ],
    description: "Klare Rinderbrühe mit dünn geschnittenen Pfannkuchenstreifen, die klassische Vorsuppe im schwäbischen Sonntagsmenü.",
    source: "klassiker",
  },
  {
    name: "Dampfnudeln mit Vanillesoße",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Süddeutschland",
    veg: true,
    servings: 4,
    minutes: 120,
    ingredients: [
      "500 g Mehl",
      "20 g Hefe, frisch",
      "500 ml Milch, für Teig und Topf",
      "80 g Zucker, für Teig und Topf",
      "60 g Butter, für den Teig",
      "1 Ei",
      "1 Prise Salz",
      "3 EL Butter, zum Dämpfen",
      "500 ml Milch, für die Vanillesoße",
      "1 Vanilleschote",
      "3 Eigelb",
      "60 g Zucker, für die Vanillesoße",
      "1 EL Speisestärke",
    ],
    steps: [
      "Hefe in 250 ml lauwarmer Milch mit 1 TL Zucker auflösen, mit Mehl, restlichem Zucker, weicher Butter, Ei und Salz 10 Minuten zu einem glatten Teig kneten und zugedeckt 1 Stunde gehen lassen.",
      "Teig in 8 Stücke teilen, zu glatten Kugeln formen und auf einem bemehlten Brett zugedeckt 20 Minuten gehen lassen.",
      "Für die Vanillesoße 500 ml Milch mit dem Mark und der Schote der Vanille aufkochen; Eigelb, 60 g Zucker und Stärke verrühren, die heiße Milch einrühren, alles zurück in den Topf geben und bei kleiner Hitze unter Rühren andicken, nicht mehr kochen lassen.",
      "In einem breiten Topf mit gut schließendem Deckel 3 EL Butter schmelzen, 250 ml Milch, 1 EL Zucker und 1 Prise Salz zugeben und einmal aufkochen.",
      "Teigkugeln mit Abstand in den Topf setzen, Deckel auflegen und bei mittlerer bis kleiner Hitze 25 bis 30 Minuten dämpfen, den Deckel dabei nicht öffnen.",
      "Wenn es im Topf knistert und die Flüssigkeit verdampft ist, haben die Dampfnudeln eine knusprige Kruste; sofort mit der warmen Vanillesoße servieren.",
    ],
    description: "Hefeklöße, die im geschlossenen Topf in Milch und Butter gedämpft werden und unten eine karamellisierte Kruste bekommen, eine süße Hauptspeise aus Süddeutschland.",
    source: "klassiker",
  },
  {
    name: "Ofenschlupfer",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: true,
    servings: 4,
    minutes: 70,
    ingredients: [
      "300 g Brötchen vom Vortag",
      "500 ml Milch",
      "3 Eier",
      "80 g Zucker",
      "1 Päckchen Vanillezucker",
      "1 Prise Salz",
      "800 g Äpfel",
      "50 g Rosinen",
      "50 g Mandelblättchen",
      "1 TL Zimt",
      "2 EL Butter",
    ],
    steps: [
      "Backofen auf 180 °C Ober- und Unterhitze vorheizen und eine Auflaufform mit 1 EL Butter fetten.",
      "Brötchen in dünne Scheiben schneiden; Äpfel schälen, vierteln, entkernen und in dünne Spalten schneiden.",
      "Milch, Eier, Zucker, Vanillezucker und Salz verquirlen.",
      "Brötchenscheiben, Apfelspalten, Rosinen und Mandeln abwechselnd in die Form schichten, jede Apfelschicht mit Zimt bestreuen und mit Brötchen abschließen.",
      "Eiermilch gleichmäßig darübergießen, 10 Minuten einziehen lassen und die restliche Butter in Flöckchen darauf verteilen.",
      "Auf der mittleren Schiene 40 Minuten backen, bis die Oberfläche goldbraun ist, und warm servieren, nach Belieben mit Vanillesoße.",
    ],
    description: "Süßer Brotauflauf aus altbackenen Brötchen, Äpfeln, Rosinen und Eiermilch, in Schwaben eine klassische Resteverwertung und Hauptspeise.",
    source: "klassiker",
  },
  {
    name: "Krautkrapfen",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 90,
    ingredients: [
      "400 g Mehl",
      "4 Eier",
      "1 TL Salz",
      "2 EL Wasser",
      "800 g Sauerkraut",
      "150 g durchwachsener Speck",
      "1 Zwiebel",
      "3 EL Schweineschmalz",
      "1 TL Kümmel",
      "Pfeffer",
      "300 ml Fleischbrühe",
    ],
    steps: [
      "Mehl, Eier, Salz und Wasser zu einem festen Nudelteig kneten, in Folie wickeln und 30 Minuten ruhen lassen.",
      "Speck und Zwiebel fein würfeln und in 1 EL Schmalz bei mittlerer Hitze 5 Minuten auslassen, abgetropftes und grob gehacktes Sauerkraut mit Kümmel zugeben, 15 Minuten dünsten, pfeffern und abkühlen lassen.",
      "Teig auf bemehlter Fläche dünn zu einem großen Rechteck ausrollen, das Kraut gleichmäßig darauf verteilen und den Teig von der Längsseite her fest aufrollen.",
      "Die Rolle in 4 cm breite Scheiben schneiden.",
      "Restliches Schmalz in einem breiten Bräter erhitzen, die Krapfen mit der Schnittfläche nach unten dicht nebeneinander einsetzen und bei mittlerer Hitze 5 Minuten goldbraun anbraten.",
      "Brühe angießen, Deckel auflegen und 25 Minuten bei kleiner Hitze garen, bis die Flüssigkeit aufgesogen ist und die Böden knusprig sind; heiß servieren.",
    ],
    description: "Nudelteig mit Sauerkraut aufgerollt, in Scheiben geschnitten und im Schmalz knusprig gebraten, eine Spezialität aus dem schwäbischen Oberland und Allgäu.",
    source: "klassiker",
  },
  {
    name: "Rinderbraten mit Spätzle",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 190,
    ingredients: [
      "1.2 kg Rinderschmorbraten",
      "2 Zwiebeln",
      "2 Möhren",
      "150 g Knollensellerie",
      "3 EL Butterschmalz",
      "2 EL Tomatenmark",
      "500 ml Rotwein",
      "500 ml Rinderbrühe",
      "2 Lorbeerblätter",
      "1 TL Pfefferkörner",
      "1 TL Senf",
      "Salz",
      "Pfeffer",
      "500 g Spätzle",
    ],
    steps: [
      "Fleisch trocken tupfen, salzen und pfeffern und in einem Bräter in Butterschmalz bei starker Hitze rundum 8 Minuten kräftig anbraten, dann herausnehmen.",
      "Zwiebeln, Möhren und Sellerie grob würfeln, im Bräter 5 Minuten rösten und das Tomatenmark 1 Minute mitrösten.",
      "Mit der Hälfte des Rotweins ablöschen und fast vollständig einkochen, restlichen Wein und Brühe zugießen, Lorbeer und Pfefferkörner zugeben und das Fleisch zurücklegen.",
      "Zugedeckt im Ofen bei 160 °C oder bei kleiner Hitze auf dem Herd 2.5 Stunden schmoren, dabei zweimal wenden.",
      "Fleisch herausnehmen und in Alufolie 10 Minuten ruhen lassen; Soße durch ein Sieb passieren, das Gemüse dabei durchdrücken, auf etwa 500 ml einkochen und mit Senf, Salz und Pfeffer abschmecken.",
      "Spätzle in kochendem Salzwasser 2 Minuten erhitzen, Braten in Scheiben schneiden und mit Soße und Spätzle servieren.",
    ],
    description: "Langsam in Rotwein geschmorter Rinderbraten mit dunkler Soße, der schwäbische Sonntagsbraten, immer mit Spätzle.",
    source: "klassiker",
  },
  {
    name: "Schwäbischer Zwiebelkuchen",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: false,
    servings: 4,
    minutes: 100,
    ingredients: [
      "400 g Mehl",
      "20 g Hefe, frisch",
      "200 ml Milch",
      "50 g Butter",
      "1 TL Salz",
      "1 Prise Zucker",
      "1.2 kg Zwiebeln",
      "150 g durchwachsener Speck",
      "2 EL Butter",
      "1 TL Kümmel",
      "3 Eier",
      "200 g saure Sahne",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Hefe in lauwarmer Milch mit dem Zucker auflösen, mit Mehl, Salz und 50 g weicher Butter 8 Minuten zu einem glatten Teig kneten und zugedeckt 45 Minuten gehen lassen.",
      "Zwiebeln in feine Streifen schneiden, Speck würfeln; Speck in 2 EL Butter auslassen, Zwiebeln und Kümmel zugeben und bei kleiner Hitze 20 Minuten weich dünsten, ohne dass sie bräunen, dann abkühlen lassen.",
      "Backofen auf 200 °C Ober- und Unterhitze vorheizen, Teig auf einem gefetteten Blech ausrollen und einen kleinen Rand hochziehen.",
      "Eier mit saurer Sahne, Salz, Pfeffer und Muskat verrühren, mit den Zwiebeln mischen und gleichmäßig auf dem Teig verteilen.",
      "Auf der mittleren Schiene 35 Minuten backen, bis der Belag gestockt und goldbraun ist.",
      "Lauwarm in Stücke schneiden und servieren, traditionell zu neuem Wein im Herbst.",
    ],
    description: "Hefeteigboden mit einem dicken Belag aus gedünsteten Zwiebeln, Speck und Eierrahm, in Schwaben das klassische Herbstessen zum neuen Wein.",
    source: "klassiker",
  },
  {
    name: "Apfelküchle",
    category: "Hauptgericht",
    cuisine: "Schwäbisch",
    origin: "Schwaben",
    veg: true,
    servings: 4,
    minutes: 40,
    ingredients: [
      "4 Äpfel",
      "200 g Mehl",
      "250 ml Milch",
      "2 Eier",
      "1 EL Zucker, für den Teig",
      "1 Prise Salz",
      "250 g Butterschmalz",
      "4 EL Zucker, für den Zimtzucker",
      "1 TL Zimt",
    ],
    steps: [
      "Eier trennen; Mehl, Milch, Eigelb, 1 EL Zucker und Salz zu einem glatten, dickflüssigen Teig rühren und 20 Minuten quellen lassen.",
      "Äpfel schälen, das Kerngehäuse mit einem Ausstecher entfernen und die Äpfel in 1 cm dicke Ringe schneiden.",
      "Eiweiß steif schlagen und unter den Teig heben; 4 EL Zucker mit Zimt mischen.",
      "Butterschmalz in einer Pfanne etwa 1 cm hoch erhitzen, bis an einem Holzstäbchen kleine Blasen aufsteigen.",
      "Apfelringe durch den Teig ziehen und portionsweise bei mittlerer Hitze je 2 bis 3 Minuten pro Seite goldbraun ausbacken.",
      "Auf Küchenpapier abtropfen lassen, in Zimtzucker wenden und warm servieren, nach Belieben mit Vanillesoße.",
    ],
    description: "In Teig ausgebackene Apfelringe mit Zimtzucker, in Schwaben und Baden eine klassische süße Hauptspeise oder Nachspeise.",
    source: "klassiker",
  },
  {
    name: "Schweinebraten mit Semmelknödel",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Bayern",
    veg: false,
    servings: 4,
    minutes: 180,
    ingredients: [
      "1.5 kg Schweineschulter mit Schwarte",
      "Salz",
      "Pfeffer",
      "1 EL Kümmel",
      "3 Zehen Knoblauch",
      "2 Zwiebeln",
      "2 Möhren",
      "150 g Knollensellerie",
      "500 ml dunkles Bier",
      "500 ml Fleischbrühe",
      "300 g Semmeln vom Vortag",
      "300 ml Milch",
      "3 Eier",
      "1 Zwiebel",
      "1 Bund Petersilie",
      "1 EL Butter",
      "Muskat",
    ],
    steps: [
      "Backofen auf 160 °C Ober- und Unterhitze vorheizen; Schwarte rautenförmig einschneiden und das Fleisch rundum mit Salz, Pfeffer, Kümmel und zerdrücktem Knoblauch einreiben.",
      "Zwiebeln, Möhren und Sellerie grob würfeln und in einen Bräter geben, das Fleisch mit der Schwarte nach unten darauflegen, 300 ml Brühe angießen und 30 Minuten im Ofen garen.",
      "Fleisch wenden, mit dem Bier übergießen und weitere 2 Stunden braten, dabei alle 20 Minuten mit Bratensaft begießen und bei Bedarf Brühe nachgießen.",
      "Für die Knödel Semmeln in dünne Scheiben schneiden, mit der heißen Milch übergießen und 15 Minuten ziehen lassen; Zwiebel fein würfeln und in Butter glasig dünsten, Petersilie hacken.",
      "Zwiebel, Petersilie, Eier, Salz und Muskat unter die Semmelmasse kneten, mit nassen Händen 8 Knödel formen und in siedendem Salzwasser 20 Minuten ziehen lassen.",
      "Für die letzten 15 Minuten den Ofen auf 230 °C schalten, bis die Schwarte knusprig aufgeploppt ist, dann den Braten herausnehmen und 10 Minuten ruhen lassen.",
      "Bratenfond durch ein Sieb gießen, entfetten, 5 Minuten einkochen und mit Salz und Pfeffer abschmecken.",
      "Braten in Scheiben schneiden und mit Knödeln und Soße servieren.",
    ],
    description: "Der bayerische Krustenbraten aus der Schweineschulter mit dunkler Biersoße und Semmelknödeln, das Wirtshausgericht schlechthin.",
    source: "klassiker",
  },
  {
    name: "Semmelknödel mit Pilzrahmsoße",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Bayern",
    veg: true,
    servings: 4,
    minutes: 50,
    ingredients: [
      "300 g Semmeln vom Vortag",
      "300 ml Milch",
      "3 Eier",
      "2 Zwiebeln",
      "1 Bund Petersilie",
      "3 EL Butter",
      "Salz",
      "Muskat",
      "600 g Champignons",
      "1 EL Mehl",
      "200 ml Gemüsebrühe",
      "200 ml Sahne",
      "Pfeffer",
      "1 TL Zitronensaft",
    ],
    steps: [
      "Semmeln in dünne Scheiben schneiden, mit der heißen Milch übergießen und 15 Minuten ziehen lassen; Petersilie hacken.",
      "Eine Zwiebel fein würfeln und in 1 EL Butter 3 Minuten glasig dünsten, mit der Hälfte der Petersilie, den Eiern, Salz und Muskat unter die Semmelmasse kneten.",
      "Mit nassen Händen 8 Knödel formen und in siedendem Salzwasser 20 Minuten ziehen lassen, das Wasser darf nicht sprudelnd kochen.",
      "Champignons putzen und in Scheiben schneiden, zweite Zwiebel würfeln; Pilze in 2 EL Butter bei starker Hitze 5 Minuten goldbraun braten, Zwiebel 2 Minuten mitbraten und salzen.",
      "Mehl darüberstäuben, Brühe und Sahne angießen und 5 Minuten bei mittlerer Hitze köcheln lassen, bis die Soße leicht bindet.",
      "Soße mit Pfeffer, Zitronensaft und restlicher Petersilie abschmecken und über den Knödeln anrichten.",
    ],
    description: "Semmelknödel als vegetarisches Hauptgericht mit einer cremigen Soße aus gebratenen Champignons, ein Standard der bayerischen Wirtshausküche.",
    source: "klassiker",
  },
  {
    name: "Wiener Schnitzel",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Österreich",
    veg: false,
    servings: 4,
    minutes: 40,
    ingredients: [
      "600 g Kalbsschnitzel",
      "Salz",
      "100 g Mehl",
      "3 Eier",
      "200 g Semmelbrösel",
      "250 g Butterschmalz",
      "1 Zitrone",
      "4 EL Preiselbeeren",
    ],
    steps: [
      "Schnitzel zwischen zwei Lagen Frischhaltefolie gleichmäßig 4 mm dünn klopfen und von beiden Seiten salzen.",
      "Mehl, verquirlte Eier und Semmelbrösel in drei flache Teller geben; Schnitzel erst in Mehl wenden, überschüssiges Mehl abklopfen, durch das Ei ziehen und in den Bröseln wenden, ohne die Panade anzudrücken.",
      "Butterschmalz in einer großen Pfanne mindestens 2 cm hoch erhitzen, bis an einem Holzlöffel Blasen aufsteigen.",
      "Schnitzel schwimmend bei mittlerer bis starker Hitze pro Seite 2 bis 3 Minuten goldbraun backen und die Pfanne dabei leicht schwenken, damit die Panade Wellen wirft.",
      "Auf Küchenpapier abtropfen lassen und sofort mit Zitronenspalten und Preiselbeeren servieren, dazu passen Kartoffelsalat oder Petersilienkartoffeln.",
    ],
    description: "Das dünn geklopfte, in Butterschmalz schwimmend gebackene Kalbsschnitzel mit luftiger Panade, das bekannteste Gericht der Wiener Küche.",
    source: "klassiker",
  },
  {
    name: "Kaiserschmarrn",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Österreich",
    veg: true,
    servings: 4,
    minutes: 30,
    ingredients: [
      "6 Eier",
      "250 ml Milch",
      "150 g Mehl",
      "60 g Zucker",
      "1 Päckchen Vanillezucker",
      "1 Prise Salz",
      "50 g Rosinen",
      "3 EL Butter",
      "2 EL Puderzucker",
      "1 Glas Apfelmus",
    ],
    steps: [
      "Eier trennen; Eigelb mit Milch, Mehl, Vanillezucker und Salz zu einem glatten Teig rühren und 10 Minuten quellen lassen.",
      "Eiweiß mit 40 g Zucker steif schlagen und locker unter den Teig heben.",
      "2 EL Butter in einer großen beschichteten Pfanne schmelzen, den Teig eingießen, Rosinen darüberstreuen und bei mittlerer Hitze 4 Minuten backen, bis die Unterseite goldbraun ist.",
      "Schmarrn vierteln, die Stücke wenden und weitere 3 Minuten backen.",
      "Mit zwei Gabeln in mundgerechte Stücke reißen, restliche Butter und restlichen Zucker zugeben und 2 Minuten karamellisieren lassen.",
      "Mit Puderzucker bestäuben und mit Apfelmus servieren.",
    ],
    description: "Der zerrissene, karamellisierte Pfannkuchen aus Österreich, als süße Hauptspeise mit Apfelmus oder Zwetschgenröster serviert.",
    source: "klassiker",
  },
  {
    name: "Tafelspitz",
    category: "Hauptgericht",
    cuisine: "Klassisch",
    origin: "Österreich",
    veg: false,
    servings: 4,
    minutes: 200,
    ingredients: [
      "1.5 kg Tafelspitz",
      "3 l Wasser",
      "2 Zwiebeln",
      "1 Bund Suppengrün",
      "2 Lorbeerblätter",
      "1 TL Pfefferkörner",
      "Salz",
      "800 g Kartoffeln",
      "2 Äpfel",
      "3 EL Meerrettich, gerieben",
      "1 TL Zitronensaft",
      "1 Prise Zucker",
      "1 Bund Schnittlauch",
    ],
    steps: [
      "Zwiebeln ungeschält halbieren und mit der Schnittfläche in einer trockenen Pfanne 5 Minuten dunkel rösten.",
      "Wasser in einem großen Topf aufkochen, das Fleisch hineinlegen, erneut aufkochen und abschäumen; Zwiebeln, Lorbeer, Pfefferkörner und 1 TL Salz zugeben und bei kleiner Hitze 2.5 bis 3 Stunden leise sieden lassen.",
      "Suppengrün putzen, grob schneiden und in den letzten 45 Minuten mitkochen.",
      "Kartoffeln schälen und in Salzwasser 20 Minuten gar kochen.",
      "Für den Apfelkren die Äpfel schälen, fein reiben und mit Meerrettich, Zitronensaft, Zucker und 1 Prise Salz mischen.",
      "Fleisch herausnehmen und quer zur Faser in fingerdicke Scheiben schneiden, die Suppe mit Salz abschmecken.",
      "Fleisch mit etwas Brühe und Gemüse in tiefen Tellern anrichten, mit Schnittlauch bestreuen und Kartoffeln und Apfelkren dazu reichen.",
    ],
    description: "Gekochtes Rindfleisch aus dem Schwanzstück, das in Wien klassisch in der Brühe mit Apfelkren und Kartoffeln serviert wird.",
    source: "klassiker",
  },
  {
    name: "Brezenknödel",
    category: "Beilagen & Salate",
    cuisine: "Klassisch",
    origin: "Bayern",
    veg: true,
    servings: 4,
    minutes: 55,
    ingredients: [
      "6 Laugenbrezeln vom Vortag",
      "300 ml Milch",
      "3 Eier",
      "1 Zwiebel",
      "1 Bund Petersilie",
      "2 EL Butter",
      "Salz",
      "Pfeffer",
      "Muskat",
    ],
    steps: [
      "Brezeln in dünne Scheiben schneiden, Milch erhitzen, darübergießen und 15 Minuten ziehen lassen.",
      "Zwiebel fein würfeln und in 1 EL Butter 3 Minuten glasig dünsten; mit gehackter Petersilie, Eiern, Salz, Pfeffer und Muskat unter die Brezelmasse mischen, bis sie gut formbar ist.",
      "Masse auf Frischhaltefolie zu einer 6 cm dicken Rolle formen, fest einwickeln und die Enden verknoten.",
      "Rolle in einem breiten Topf in siedendem Wasser 30 Minuten ziehen lassen, das Wasser darf nicht kochen.",
      "Rolle auspacken, in 2 cm dicke Scheiben schneiden und nach Belieben in der restlichen Butter kurz anbraten; passt zu Braten und Pilzrahmsoße.",
    ],
    description: "Die bayerische Abwandlung des Semmelknödels aus altbackenen Laugenbrezeln, als Serviettenknödel gerollt und in Scheiben serviert.",
    source: "klassiker",
  },
  {
    name: "Obatzda",
    category: "Snacks",
    cuisine: "Klassisch",
    origin: "Bayern",
    veg: true,
    servings: 4,
    minutes: 45,
    ingredients: [
      "400 g Camembert, reif",
      "100 g Butter",
      "100 g Frischkäse",
      "2 Zwiebeln",
      "2 TL Paprikapulver edelsüß",
      "1 TL Kümmel",
      "3 EL helles Bier",
      "Salz",
      "Pfeffer",
      "1 Bund Schnittlauch",
      "4 Laugenbrezeln",
    ],
    steps: [
      "Camembert bei Zimmertemperatur mit einer Gabel grob zerdrücken.",
      "Weiche Butter, Frischkäse, eine fein gewürfelte Zwiebel, Paprikapulver, Kümmel und Bier zugeben und zu einer cremigen Masse verrühren, in der noch kleine Käsestücke bleiben.",
      "Mit Salz und Pfeffer abschmecken und zugedeckt 30 Minuten im Kühlschrank ziehen lassen.",
      "Die zweite Zwiebel in feine Ringe schneiden, Obatzda damit und mit Schnittlauchröllchen bestreuen und mit Brezeln servieren.",
    ],
    description: "Die bayerische Biergarten-Käsecreme aus reifem Camembert, Butter, Zwiebeln und Paprika, immer mit Brezeln auf den Tisch.",
    source: "klassiker",
  },
];
